### ISSUE TITLE
Unable to move Page to a new place  

### ISSUE THREAD

**Issue by NMuzaffar** [headwirecom/peregrine-cms#103]
**Reproduction**

- open pages tab in admin console
- click 'Move page' on any page

![Screenshot 2019-06-23 at 14 21 20](https://user-images.githubusercontent.com/24642899/59976302-bb4b9e80-95c2-11e9-8d31-fa5af207f324.png)

**Comment by devintuffy** [comment]
Pull request here:  https://github.com/headwirecom/peregrine-cms/pull/132
