### ISSUE TITLE
Changing page properties sets primaryType to nt:unstructured

### ISSUE THREAD

**Issue by NMuzaffar** [headwirecom/peregrine-cms#109]
Whenever you edit Page properties through admin console, it resets Page's content primaryType **from per:PageContent to nt:unstructured**. E.g. you change the title of page 

<img width="860" alt="Screenshot 2019-06-28 at 16 07 19" src="https://user-images.githubusercontent.com/24642899/60348108-31834300-99bf-11e9-8dc3-a0f6f2016620.png">

<img width="1311" alt="Screenshot 2019-06-28 at 16 07 50" src="https://user-images.githubusercontent.com/24642899/60348118-334d0680-99bf-11e9-8c0e-b574e5154c94.png">

**Comment by reusr1** [comment]
@bkheadwire please review if you see any other issues related to the nerge of this PR

**Comment by NMuzaffar** [comment]
@reusr1 I had no access to the project during last 2 weeks, and had no means to test the fix. But it seems the bug is still unresolved. Attaching images from the same use case -> Page title change

<img width="1383" alt="Screenshot 2019-07-17 at 08 56 04" src="https://user-images.githubusercontent.com/24642899/61353806-ee571a00-a870-11e9-8eca-78af8ee3bc25.png">

<img width="1387" alt="Screenshot 2019-07-17 at 08 56 27" src="https://user-images.githubusercontent.com/24642899/61353811-f1520a80-a870-11e9-8a0e-27252e1aa15b.png">
