### ISSUE TITLE
Text Component - Unordered list 

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#110]
*Steps to Reproduce*

1. Create a page.
2. Drop a `Text Block` component on the page.
3. Click the unordered list button, then enter some text.

*Actual Behavior*
Unordered list bullets are not displayed. However, if you view the markup,  `<ul>` and `<li>` elements are created.

*Expected Behavior*
Unordered list bullets should be displayed.

This is blocking the creation of editorial copy for the Peregrine documentation initiative.

CC: @reusr1

**Comment by reusr1** [comment]
@dna113p even after the resetCss fix for the editor the disc items dont show up - can you please look into what's going with the css here?

**Comment by achouhans** [comment]
I will be looking into this issue now.

**Comment by GastonGonzalez** [comment]
This appears to be fixed. Closing ticket. I can't reproduce this.
