### ISSUE TITLE
Unsaved component changes are lost if the user clicks on another component on the page

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#111]
*Overview*

This issue is critical as users will lose any work that has not been saved if they click on any other component while editing a component.

*Steps to Reproduce*

1. Edit or create a page.

2. Add at least two (2) Text Block components to the page. Note: This bug actually manifests itself with any set of components.

3. Edit the text for the first Text Block, but do not click the save button.

4. Click on the second Text Block component. At this point, a dialog box should appear that says "save edit."

5. Click the `cancel` button.

*Expected Behavior*
Component changes are NOT lost.

*Actual Behavior* 
Component changes are lost.

CC: @reusr1

**Comment by bkheadwire** [comment]
This is now part of the [action rewrite branch](https://github.com/headwirecom/peregrine-cms/tree/feature/actionrewrite). Will be fixed whenever that is merged.

**Comment by flx-sta** [comment]
feature/actionrewrite has been merged
