### ISSUE TITLE
Incorrect service worker defined when site uses the themeclean-flex template

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#113]
## Overview

While running a Chrome audit on https://blog.gastongonzalez.com/content/sites/gastongonzalez/2019/6/26/deploying-a-bare-metal-kubernetes-cluster-with-vagrant-and-virtualbox.html, I noticed that the service worker is misconfigured. 

```
Does not register a service worker that controls page and start_url
This page is controlled by a service worker, however the start_url ("https://blog.gastongonzalez.com/content/sites/themecleanflex/index.html") is not in the service worker's scope ("https://blog.gastongonzalez.com/content/sites/gastongonzalez/").
```

This demo site (https://blog.gastongonzalez.com) was created using the themeclean-flex template.

### Steps to Reproduce

1. Create a site and use the `themeclean-flex` template.
2. Launch Chrome Web Developer Tools > Audit. Run an audit with the defaults.
3. Once the audit is complete, scroll down to the `Progressive Web App` section.

*Actual Behavior*
`start_url` points to themeclean-flex site.

*Expected Behavior*
`start_url` should point to the actual site / tenant.

FYI: @reusr1  and @dna113p

**Comment by GastonGonzalez** [comment]
Pleas note: I manually corrected the references in `/content/sites/gastongonzalez/serviceworker.js` and `/content/sites/gastongonzalez/manifest.json` to point to my site/tenant. This issue is no longer testable via the demo site above however, it is still reproducible if you followsthe steps above.

**Comment by bkheadwire** [comment]
Fixed: https://github.com/headwirecom/peregrine-cms/pull/178
