### ISSUE TITLE
Add page-level support for meta tags

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#114]
# Overview

Peregrine currently only supports a limited set of HTML meta tag elements (e.g, keywords and description). Many web crawlers and social media platforms specifically look for additional metadata. When embedded on pages, these search engines and social networks will use this information to render rich media cards. These metadata elements include (but are not limited to):

1. Open Graph tags

```
<meta property="og:title" content="..." />
<meta property="og:description" content="..." />
<meta property="og:type" content="..." />
<meta property="og:url" content="..." />
<meta property="og:image" content="..." >
...
```

2. Twitter Cards

```
<meta name="twitter:card" content="...." /> 
<meta name="twitter:site" content="..." /> 
<meta name="twitter:creator" content="..." />
```
3. Facebook

```
<meta property="fb:app_id" content="your_app_id" />
```

## Implementation

To offer the most flexibility, the page properties dialog shall be updated to support a list of optional meta key/value pairs where the key is the value of the `meta property or name` attribute value (i.e. og:title) and the value is the meta content attribute value. Two lists may be needed: one for `meta name` and one for `meta property` as their use is driven by different specifications. The `meta name` attribute is part of the HTML 5 specification, while `meta property` attribute is part of the RDFa protocol specification.

On page creation, both the `meta name` and `meta property` lists should be configured with the salient set of key names. They should not have a value by default. If the value is empty, the front-end should not render the HTML meta element.
 
## Resources

* http://ogp.me/
* https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards.html
* https://developers.facebook.com/docs/sharing/webmasters/

FYI: @reusr1

**Comment by GastonGonzalez** [comment]
@reusr1  - When you have some time can you take a look this PR for this ticket. Here's the [commit](https://github.com/headwirecom/peregrine-cms/commit/be38b79430ee9a03e22350c1ff958f953eb0b570). I am running into a problem in which I can add meta elements via the page properties dialog and save them, but when I visit the page properties later, the dialog UI does not render them. They are persisted in the JCR. Unlike the other page-level properties, these are stored under jcr:content/metaproperties. I'm also using the sly list in page.html, but the meta properties do not render. I'm pretty sure that I am missing something small to get the collection type working in page properties. Thanks.

**Comment by GastonGonzalez** [comment]
I believe there is a bug when a page property uses a collection. The tags under the page property view exhibits the same behavior as my custom meta properties collection A user can add tags and save them. They are persisted to a child node under jcr:content (i.e. `jcr:content/tags`). If the page is reload it, the UI no longer renders the tags.

**Comment by bkheadwire** [comment]
Done: https://github.com/headwirecom/peregrine-cms/pull/171
