### ISSUE TITLE
Add support for Google PageSpeed replication service

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#124]
# Overview

The [peregrine-docker-apache-explore](https://github.com/peregrine-cms/peregrine-docker-apache-explore) project provides a reference implementation for fronting a single Peregrine author instance with two Apache servers: one for live (publish) and one for stage (author). The live Apache instance uses `mod_pagespeed` as a caching layer for Peregrine. The goal of this ticket is to introduce a PageSpeed replication service that invalidates single pages, groups of pages or an entire site's PageSpeed cache.

**Comment by reusr1** [comment]
this should be solved in a generic way to plug in invalidators as needed (for example if a cdn is used)

**Comment by reusr1** [comment]
@GastonGonzalez is this ticket still necessary?

**Comment by GastonGonzalez** [comment]
We can close this. Closing now.
