### ISSUE TITLE
Cannot paste or directly edit color string in color picker field

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#128]
Currently the only way to edit a color field is through the dialog that pops up. We should be able to type in a specific color value.

**Comment by flx-sta** [comment]
@dna113p could you provide an example component please?

**Comment by ehdatheadwire** [comment]
Closing issue and moving to peregrine-cms/enhancements respository.

Reference link: https://github.com/peregrine-cms/enhancements/issues/1
