### ISSUE TITLE
Teaser Components: Button alignment naming convention inconsistent

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/peregrine-cms#129]
With both teaser horizontal and teaser vertical, the "button alignment" control is named differently between the two. Should be consistent. 

Change Teaser Horizontal to match Teaser Vertical and have it say "Button Alignment."

<img width="1673" alt="Screen Shot 2019-07-09 at 3 37 50 PM" src="https://user-images.githubusercontent.com/51373617/60921443-1e466200-a260-11e9-96cd-64137b1c98d7.png">

<img width="1672" alt="Screen Shot 2019-07-09 at 3 38 12 PM" src="https://user-images.githubusercontent.com/51373617/60921447-21415280-a260-11e9-9f98-04ac1ce4ddfe.png">

**Comment by reusr1** [comment]
@ehdatheadwire seems to be a themeclean-flex issue, please open in https://github.com/headwirecom/themeclean-flex

**Comment by ehdatheadwire** [comment]
Aye.
