### ISSUE TITLE
Teaser Horizontal: Text alignment and button alignment aren't working as expected

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/peregrine-cms#130]
In Teaser Horizontal only, toggling Button Alignment elicits no results. And Content Align only aligns the text either left or right, but doesn't relocate the buttons to either side of the text. 

Steps to Reproduce:
1. Create page
2. Drag Teaser Horizontal component over to container
3. Under Align Content, select "Right"
4. Note that content realigns to the right, but buttons remain unmoved
5. Move down and select "Right" under Button Side
6. Buttons don't move

Expectations:
1. If text/content is realigned to the right, buttons should swap to left
2. If buttons are aligned using the radial select, then they should change alignment

**Comment by reusr1** [comment]
@ehdatheadwire it seems this is a themeclean-flex issue, right? should be opened in https://github.com/headwirecom/themeclean-flex

**Comment by ehdatheadwire** [comment]
Aye aye. I'll open it there. Thx.
