### ISSUE TITLE
Choosing "save edit" after canceling a component edit discards the changes anyway

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#133]
Steps to reproduce:
1. Drag a component onto the page
2. Make a change to the component in the editor
![01-edit](https://user-images.githubusercontent.com/5474176/61005264-bd309400-a31c-11e9-9aa5-759a91dca524.png)
3. Click the cancel button
![02-cancel](https://user-images.githubusercontent.com/5474176/61005280-c6216580-a31c-11e9-864b-ab83f00d1abf.png)
4. Choose "OK" on the "save edit" alerts

Expected result:
Changes made are saved

Actual result:
Changes are lost
![03-changeslost](https://user-images.githubusercontent.com/5474176/61005317-d9cccc00-a31c-11e9-8234-2682e6a6990c.png)

**Comment by devintuffy** [comment]
fixed in PR https://github.com/headwirecom/peregrine-cms/pull/135, will close ticket when that merges

**Comment by bkheadwire** [comment]
This is now part of the [action rewrite branch](https://github.com/headwirecom/peregrine-cms/tree/feature/actionrewrite). Will be fixed whenever that is merged.

**Comment by flx-sta** [comment]
feature/actionrewrite has been merged
