### ISSUE TITLE
Leaving page editor causes last component being edited to become unselectable upon return

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#134]
Steps to reproduce:
1. Add a component to a page
2. Use the browser's "Back" button (doesn't matter where "back" actually goes)
3. Navigate back to the page edit view
4. Attempt to select/edit the component you had open

Expected result:
The component is editable

Actual result:
The component cannot be selected for editing without first clicking on another component

**Comment by bkheadwire** [comment]
Updated the title to reflect the fact that it's not actually the back button that causes the issue - if you leave page edit mode in any way (e.g. by clicking "Pages" to return to the page list) and then come back, the component you last had selected won't be clickable until you select another component first.

**Comment by reusr1** [comment]
@bkheadwire issue should be fixed in develop branch. please close once you can confirm

**Comment by bkheadwire** [comment]
Confirmed fixed in developed.
