### ISSUE TITLE
Cannot recreate site with same name after deleting

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#136]
Steps to reproduce:
1. Create a site
2. Delete the site
3. Try to create another site with the exact same name

Expected result:
New site is created with the same name

Actual result:
Site creation fails

**Comment by reusr1** [comment]
workaround: go to composum and delete the site in /apps, /etc/felibs, /content/assets, /content/templates, /content/objects

**Comment by reusr1** [comment]
@bkheadwire please close as I think you resolved this issue?
