### ISSUE TITLE
Component drop targets missing from new pages

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#137]
This broke sometime in the last day. I checked out commit 596496b9230c097a3920ce1df636df66562ad666 and built and it doesn't occur with new pages created after that (although pages created with the latest version remain broken even after rolling back and deploying).

Steps to reproduce:
1. Create a new page with the themeclean template
2. Open the page for editing

Expected result:
There should be "page start" and "page end" placeholder blocks to drop components between

Actual result:
The page is totally blank and components cannot be dropped in the page

**Comment by reusr1** [comment]
@bkheadwire closing as this is not reproducible anymore
