### ISSUE TITLE
Edit panel organization and tooltips

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#139]
Right now all of the options in the component edit panel are in one big column, which makes it difficult to see which options are meant to be grouped together. It would be beneficial to have some kind of grouping system or even tabs.

It would also be good to have tooltips or inline descriptions for fields that aren't self-explanatory in what they do or what their valid values are. Things like "Anchor Name" and "Background Size Style" are not obvious to people who aren't frontend devs.

**Comment by flx-sta** [comment]
@reusr1 wasn' there a branch for that ?
feature/186 was it I think #186

**Comment by reusr1** [comment]
grouping of properties is working in peregrine itself, follow up ticket to group properties in the components can be found here: https://github.com/headwirecom/themeclean-flex/issues/160
