### ISSUE TITLE
Allow some fields to have different values for each responsive breakpoint

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#140]
There are certain editable options for which it doesn't make sense to have one value set across desktop, tablet, and mobile widths, e.g. the "cards per row" option on the cards component. Having three fields for the same property is an option but seems inelegant. Maybe have an optional wrapper for form elements that adds radio buttons for choosing which view the current value should apply to?

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/2
