### ISSUE TITLE
Insert image dialog for RTE doesn't look right

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#141]
![01-insertimagedialog](https://user-images.githubusercontent.com/5474176/61163155-58626e80-a4c1-11e9-8231-2b99fad8495c.PNG)

Labels/fields for this dialog look a bit off.

**Comment by reusr1** [comment]
@bkheadwire this issue should be resolved together with #97 - please validate

**Comment by bkheadwire** [comment]
Still has issues, see comments on the PR: https://github.com/headwirecom/peregrine-cms/pull/224
