### ISSUE TITLE
Leaving page properties editor without saving after changing field appears to persist changes but doesn't

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#146]
Steps to reproduce:
1. Click the 'info' button on a page in the pages admin
2. Click the 'edit page properties' button
3. Change the text in the description field
![01-changedproperties](https://user-images.githubusercontent.com/5474176/61253673-a1f7c700-a716-11e9-9e23-3f7846477cc4.PNG)
4. Click the 'cancel edit' button
![02-fakepersist](https://user-images.githubusercontent.com/5474176/61253628-7a086380-a716-11e9-8319-ba0ec3925f1d.PNG)
![03-clickedpages](https://user-images.githubusercontent.com/5474176/61253630-7d9bea80-a716-11e9-89ea-972fef3fc394.PNG)

Expected result:
The changes should not persist through the cancel

Actual result:
The changes appear to still be there in the frontend, but reloading the pages interface causes them to disappear again

Notes:
Beyond the bug of the frontend holding onto a value that wasn't actually saved to the repository, there's also a confusing UI experience here. Having the 'cancel edit' button use the 'info' icon is misleading and there's no warning that changes in the property editor will be discarded by leaving via any means other than the checkmark. The UI for the properties here should be consistent with the component edit UI (an 'X' button to cancel, a warning that lets you save your changes if you try to leave edit mode without saving).

**Comment by reusr1** [comment]
this issue is tackled in the https://github.com/headwirecom/peregrine-cms/tree/feature/actionrewrite branch

**Comment by flx-sta** [comment]
@reusr1 there is no cancel button anymore... ?

**Comment by reusr1** [comment]
there is indeed no cancel button at the bottom. the ;'cancel' is currently through the icon at the top that switches back to the view of the properties (its tooltip says cancel) - we should probably add a cancel button at the bottom of the form as well (same as in dialog editing) and introduce the same type of experience as exists for components, asking the user if he/she wants to save the changes when you cancel or select something else in the UI and would move away from the dialog. 

Same issue exists for pages (and templates), assets, and objects

**Comment by flx-sta** [comment]
@reusr1 fixed. please validate
