### ISSUE TITLE
Pathbrowser should make folders distinct from non-folders, allow selection by clicking on leaf node

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#150]
There are two somewhat related UX concerns with the pathbrowser. One is that every kind of node has the same icon regardless of whether it's a folder/has children or not. The other is that you can't make your path selection by clicking on the thing you want to select - you have to click the radio button for it instead. This is not a natural user interaction (compare to the OS filesystem browser - clicking on something selects it, some other action like double-clicking enters it).

**Comment by reusr1** [comment]
the path browser exposes the UX concept for selecting a path or selecting an item. This can also be difficult in the OS file system browser. While we agree with this issue nobody has taken this issue up in the past year - labeling this issue as tabled for now and closing it
