### ISSUE TITLE
Richtext copy paste bugs

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#151]
Copying from a rich text field with keyboard copies selected component.
- Select a component with a rich text field
- try to copy any text in the field using keyboard shortcuts
- try to paste that text w ctrl-v (results in a copied component on the page)

Pasting into rich text with keyboard shortcut no longer works
- Select a component with rich text
- Copy text from outside of the current page
- Paste with ctrl-v (text is pasted and then dissapears)

note: copy and paste with right-click menu option still works.

Seems like component copy paste are interfering 
Potentially introduced with #143

**Comment by reusr1** [comment]
@dna113p pushed a change into develop that should fix this. please confirm and close

**Comment by dna113p** [comment]
Look good now :)
