### ISSUE TITLE
Dialogs don't have any validation

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#152]
From: https://github.com/headwirecom/themeclean-flex/issues/42

Dialogs are not currently being validated at all. Vue-form-generator has some built in validators as well as ability to do custom validators but I don't believe we currently have any way to use those with the way we define dialogs in json.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/3
