### ISSUE TITLE
Component filter no longer works/does not sort components

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/peregrine-cms#155]
As authoring a page, if user wishes to display ONLY text components (e.g. Heading, Basic Text), selecting "Text Components" from the component group filter dropdown elicits no change/results. 

This appears to have been a bug back in May but the filter was definitely working as recently as last week, so something has changed between now and then. 

Dropbox link to issue screencast: https://www.dropbox.com/s/xmxx87xdw0ay90c/componentfilter.mp4?dl=0

**Comment by reusr1** [comment]
@ehdatheadwire the issue has been addressed and will be available next time a release is deployed to your environment
