### ISSUE TITLE
Cards component causes page bottom to get cut off

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#158]
Steps to reproduce:
1. Drag enough components onto the page to cause the vertical scrollbar to appear
2. Add the cards component to the page
3. Exit and reenter the page editor

Expected result:
Vertical scrolling should allow you to see the entire page

Actual result:
Vertical scrolling stops before the end of the page, leaving the bottom cut off

https://youtu.be/bNogYJBR20w

Note: I tried several combinations of components and cards was the only one that I found that caused this to happen. Furthermore, each additional copy of the cards component makes things worse. Switching to preview makes the whole page visible again, and it remains visible when exiting preview.

**Comment by reusr1** [comment]
@bkheadwire the fix from @dna113p for lazy loading images seems to have fixed this issue as well. can you please check develop to make sure you can not reproduce this issue anymore?

**Comment by bkheadwire** [comment]
Can't reproduce it now either.
