### ISSUE TITLE
Can't disable Pathbrowser button

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#159]
You can currently set disabled or readonly for the pathbrowser. Disabled just disables the input field but you can still select and image by using the button. Readonly also disables the input field but slightly different and you can still use the button but when you select an image it just doesn't get saved.

**Comment by reusr1** [comment]
seems in readonly we should not display the button at all

**Comment by reusr1** [comment]
fix has been merged, @FabianHaupt can you please make sure this works for your use case and close it if it does?

**Comment by flx-sta** [comment]
I can confirm that this works now!

- `disabled: true`: Button showing but disbaled.
- `readonly: true` Button not showing at all (but the gap that is reserved for the button is present)
