### ISSUE TITLE
Special characters in pasted text get mangled

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#164]
Steps to reproduce:
1. Add a teaser to a page
2. Paste in this text I borrowed from a random product launch page:

> You don’t have the same day every day – so why are you taking the same supplements?

3. Save the component
4. Click on the component again
5. Cancel the component edit

Expected result:
Text should remain unchanged

Actual result:
Text turns into this:

> You donâ€™t have the same day every day â€“ so why are you taking the same supplements?

https://youtu.be/Nd_b826oY4A

**Comment by reusr1** [comment]
@bkheadwire can you check out the issues/114 branch and see if it is fixed there?
