### ISSUE TITLE
Copied components lose changed properties when pasted

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#165]
Steps to reproduce:
1. Add a "teaser primary" component to a page
2. Change some properties, e.g. title, text, background
3. Save the changes
4. Copy the teaser
5. Paste the teaser

Expected result:
The pasted teaser should look identical to the copied one

Actual result:
The pasted teaser has the default properties of the teaser primary component.

https://youtu.be/qVvD3_pKIJk

**Comment by reusr1** [comment]
@schaefa this seems to be an issue in admin-base/core/src/main/java/com/peregrine/admin/servlets/InsertNodeAt.java - when creating a node through copy/paste the properties passed in the request do not get set anymore

**Comment by schaefa** [comment]
Will check it out

**Comment by schaefa** [comment]
Fixed it and pushed the changes to develop

**Comment by reusr1** [comment]
@schaefa please also check for example the card component with subnodes. copy paste is not successful if a card is changed

**Comment by schaefa** [comment]
Fixed the issue where properties of children are not applied to the copy's children

**Comment by schaefa** [comment]
Added support for this scenario. The issue at hand is that the children in themeclean container is that the component is not given as internal component name. So the code will look for the source node by the given path and then take this as a template on creating the containers' children.

**Comment by reusr1** [comment]
@schaefa can you also push this into develop, please?
