### ISSUE TITLE
Getting to the welcome page

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#166]
There's no obvious way to get back to the welcome page (/index.html) once you're in the admin interface (/content/admin.html). There should be a link back to the welcome page somewhere in the top bar. Also, the result of clicking on the peregrine logo should always be consistent. Right now, when you're on the welcome page, it points at /. Once you're under the admin section, it brings you back to the root admin page.

**Comment by reusr1** [comment]
moved some of the links from the / page to the Tools pod on /content/admin.html as a workaround

**Comment by bkheadwire** [comment]
https://github.com/headwirecom/peregrine-cms/tree/issues/166

I added our "about" blurb with the github and contact links, logo, etc to a modal that you can open from the top nav so we now have everything from the welcome page accessible somewhere in the admin UI and can get rid of it if we want.

(Whether it really needs its own top-level nav item is another question - I think it probably makes the most sense to have it as part of a dropdown with the help button)

**Comment by flx-sta** [comment]
@bkheadwire I've checked this and provided german translation for it.
I'd say we close this issue and create a follow-up issue to get rid of the welcome page
