### ISSUE TITLE
trumbowyg "remove format" not working properly

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#168]
### Bug
When I tried to use the richt-text editor "trumbowyg" i did try some stuff with "remove format".
Instead of removing the format though, It add it. 

I tried to reproduce it on the official website of trumbowyg but it's working fine there.

Maybe an old version of trumbowyg?

### Video
![Screen Recording 2019-08-02 at 12 47 16](https://user-images.githubusercontent.com/50131232/62365410-56218c00-b524-11e9-84a7-9dc005b4722d.gif)

**Comment by reusr1** [comment]
@Felix-Puetz I tried this on the trumbowyg website as well. it seems to not remove formats for paragraphs. Try this: select a text and make it a heading 1 then select the whole text and click on remove format. It does not work for me. It only removes styles but does not change html tags

**Comment by flx-sta** [comment]
I can confirm that. 
- Should I close the issue? 
- Should I create an issue in their Repo?
- Should we replace trumbowyg with another wysiwyg editor?

**Comment by bkheadwire** [comment]
Hi @Felix-Puetz, please go ahead and create an issue in their repo (or find one if it exists already) and link it here. We'll keep this ticket open with the cantfix label for now.

**Comment by flx-sta** [comment]
Trumbowyg issue: https://github.com/Alex-D/Trumbowyg/issues/1033

**Comment by bkheadwire** [comment]
Thanks!

**Comment by flx-sta** [comment]
trumbowyg issue has been created (and denied)
