### ISSUE TITLE
better organization of dialogs

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#186]
dialogs get a bit to complex with to many options - it would be better to support a concept of a group and provide a better way to organize the dialogs

**Comment by reusr1** [comment]
https://github.com/headwirecom/peregrine-cms/tree/issues/186 contains a sample of using groups in the dialogs - needs better styling

**Comment by flx-sta** [comment]
@reusr1 a little screenshot/gif/video to present it would be great 👍

**Comment by flx-sta** [comment]
@reusr1 
So I've tested it by merging it properly into our branch and it seems to work fine 👍 
(Except the styling, which you already mentioned)

**Comment by reusr1** [comment]
@Felix-Puetz can you merge this into the issues/93 and clean up the styling a bit?

**Comment by flx-sta** [comment]
Done @reusr1 please validate

**Comment by reusr1** [comment]
@Felix-Puetz thank you for merging
