### ISSUE TITLE
Pathbrowser should support filetypes

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#188]
For example, if we want to reference an asset, we should be able to limit it to video or image filetypes.

**Comment by reusr1** [comment]
is this not handled with https://github.com/headwirecom/peregrine-cms/pull/116 ?

**Comment by dna113p** [comment]
Oh yeah looks like that is at least a start.

**Comment by flx-sta** [comment]
Image file-type support is given.
Video should be implemented: #299
