### ISSUE TITLE
Parallel asset upload

### ISSUE THREAD

**Issue by Thomas-Pelster** [headwirecom/peregrine-cms#189]
User should be able to upload multiple assets (e.g. images) parallel.
1. User selects multiple assets
2. User starts upload
3. CMS simultaneously uploads assets and visualises individual progress of each upload

**Comment by reusr1** [comment]
@Thomas-Pelster not sure if it helps but the asset page allows you to drag and drop multiple files from your computer directly onto the browser to trigger an upload

**Comment by Thomas-Pelster** [comment]
@reusr1 Thanks for the information. Since the function is given via drap&drop we should assign this alternative way to the enhancements project.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/4
