### ISSUE TITLE
Error when trying to edit certain components

### ISSUE THREAD

**Issue by devintuffy** [headwirecom/peregrine-cms#19]
In the example site, when clicking on "Row Start", or other components, this error is displayed to the user:

<img width="1298" alt="screen shot 2019-02-19 at 9 11 43 am" src="https://user-images.githubusercontent.com/46942507/53033729-8f5ab980-3426-11e9-9532-7f64b4f43515.png">

Accompanied by this message in the console:

```
[debug] [editComponent]            Failed to show editor: TypeError: Cannot read property 'fields' of undefined
```

**Comment by dna113p** [comment]
Fixed with #23
