### ISSUE TITLE
template explorer-preview: no visual feedback on save/cancel

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#190]
### Description
There is not any visual Feedback when editing a templates information and clicking save or cancel.
Actually it looks like the save button does save (when checking the network tab in the dev tools) but it does not change back from the edit mode to the view mode.
The cancel button does not seem to do anything.

### Video
![template-info-no-feedback](https://user-images.githubusercontent.com/50131232/63320547-6b692980-c31e-11e9-9670-f03917357435.gif)

**Comment by reusr1** [comment]
this issue is also mentioned as part of https://github.com/headwirecom/peregrine-cms/issues/146

**Comment by flx-sta** [comment]
@reusr1 should i close it then?

**Comment by reusr1** [comment]
@Felix-Puetz let's leave it open as the other issue describes multiple issues

**Comment by flx-sta** [comment]
The 2 mentioned buttons dont't even exist anymore and visual feedback is now given by the new loading anmiation added by feature/actionrewrite
