### ISSUE TITLE
Multiple upload of asset(s) with the same name generates error

### ISSUE THREAD

**Issue by Thomas-Pelster** [headwirecom/peregrine-cms#192]
A user can upload one or more assets (via drap&drop) with the same name multiple times and an error occurs that is not handled.

What would be our expected behavior?
- An error with the name of the image is displayed. OR
- The user can decide via dialog whether the existing files should be overwritten. OR
- ....

**Comment by reusr1** [comment]
@schaefa while you are looking into #231 please also address this issue in the backend

**Comment by schaefa** [comment]
Added the replacement logic for already existing assets

**Comment by bkheadwire** [comment]
So to be clear, the solution that was adopted here is to simply replace the existing version without prompting/notifying the user. This addresses the actual error so I'm closing this, but we may want a future enhancement ticket to improve the UX.
