### ISSUE TITLE
Including of external javascript file for Internet Explorer

### ISSUE THREAD

**Issue by andreas-hauser** [headwirecom/peregrine-cms#196]
The shim.min.js file is included from an external source (it seems to be necessary for the Peregrine editor to work under Internet Explorer):
```javascript
if(/MSIE \d|Trident.*rv:/.test(navigator.userAgent))
   document.write('<script src="https://raw.githack.com/zloirock/core-js/v2.4.1/client/shim.min.js"><\/script>');
```
We might want to avoid including external sources, as these could come with cookies, etc.
Would it be a good idea to provide the specific javascript file within peregrine?

**Comment by flx-sta** [comment]
@reusr1 @GastonGonzalez @dna113p 

What's your opinion on that?

**Comment by reusr1** [comment]
We can insource it for sure. Should follow the same process as all other insourcings

**Comment by reusr1** [comment]
file is now insourced
