### ISSUE TITLE
apiImpl js: rename methods are redundant

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#199]
all the rename method in the `apiImpl.js` file are pretty much the same (except the name)

We should always avoid duplicate code

```
    renameObject(path, newName) {
        return new Promise( (resolve, reject) => {
            let data = new FormData()
            data.append('to', newName)
            updateWithForm('/admin/rename.json'+path, data)
                .then( (data) => this.populateNodesForBrowser(path) )
                .then( () => resolve() )
        })
    }
```
```
    renameAsset(path, newName) {
        return new Promise( (resolve, reject) => {
            let data = new FormData()
            data.append('to', newName)
            updateWithForm('/admin/rename.json'+path, data)
                .then( (data) => this.populateNodesForBrowser(path) )
                .then( () => resolve() )
        })
    }
```
```
    renamePage(path, newName) {
        return new Promise( (resolve, reject) => {
            let data = new FormData()
            data.append('to', newName)
            updateWithForm('/admin/rename.json'+path, data)
                .then( (data) => this.populateNodesForBrowser(path) )
                .then( () => resolve() )
        })
    }
```

**Comment by reusr1** [comment]
While they work the same against sling they could work differently against another backend in the future. I am against refactoring them into a single method

**Comment by flx-sta** [comment]
But isn't this the job of the api to handle it always the same in the backend?

If so we should re-think the logic we are using in the api.

**Comment by reusr1** [comment]
I think the mistake here is more that we do not expose individual endpoints in the backend for this as the implementation of a page rename could be quite different from the implementation of an asset rename.

**Comment by reusr1** [comment]
@bkheadwire can you please add endpoints for rename page, asset, object at /api/page/rename, /api/asset/rename, /api/object/rename and make sure the the apiimpl.js calls the right implementation? (also, does this path structure make sense with the rest of the api?)

**Comment by flx-sta** [comment]
@bkheadwire which pull request was it?

**Comment by bkheadwire** [comment]
@Felix-Puetz https://github.com/headwirecom/peregrine-cms/pull/250
