### ISSUE TITLE
Mixed Content http 

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#2]
Hello 
Thank you making a nice looking CMS. I'm trying to use Peregrine on AWS where SSL is handled by the load balancer and forwarded on with a header HTTP:X-Forwarded-Proto https  But I'm finding a lot of trouble with mixed content with these resources. 

/perapi/admin/access
/system/sling/info.sessionInfo

Generally what I'm finding is that any page below /content/admin.html will not load thru the intended https domain. Accessing thru a backdoor works. In the browser, I allowed the unsafe scripts to load and allowed xhr http paths by adding Access-Control-Allow-Origin header. But it will does not work. After doing that it appears a js alert executes stating "please login to continue"

Any advice?
Cris

**Comment by reusr1** [comment]
Chris, thank you for reporting this issue . Is this in an author or publish scenario and are you using one or multiple servers behind the ELB?

**Comment by cmrockwell** [comment]
This is in author mode. I'm using httpd on another instance between the peregrine instance and the ELB. When I use http only, everything seems fine. It might be a problem with the Authorization header. When the problem happens, the access.log at peregrine shows the request to /system/sling/info.sessionInfo from anonymous.

**Comment by reusr1** [comment]
just wondering - are you using 2 authors behind the elb or just one? If you install an out of the box sling instance - do you see the same issue?

**Comment by cmrockwell** [comment]
For now, I have taken httpd out of the mix. As of now there is only one author and one elb.  
No I don't think Sling or Composum have exactly this same problem. When I log in direct to https://access.rockwellcdn.com/bin/browser.html it will redirect after authn to http. But Sling and Composum still render when I request https URI's 

I feel the problem relates to 302 sent from com.peregrine.admin.servlets.AccessServlet, which seems to be giving the location fully qualified location including http protocol. When the front end requests /perapi/admin/access.json it is handled by AccessServlet and redirected to http://<domain>/system/sling/info.sessionInfo

Since the application is behind an ELB or proxy that is terminating SSL, the location could be given with only the path like Location: /system/sling/info.sessionInfo which should allow the browser to use the protocol and domain inherited from the requested document.

**Comment by cmrockwell** [comment]
I know this is not the best fix. But it avoids the problem and allows the app to render from https... 

![screenshot from 2018-10-07 14-26-54](https://user-images.githubusercontent.com/1811207/46585293-23f6e900-ca3d-11e8-8b37-cf83bc4ccac9.png)

**Comment by schaefa** [comment]
The current 'master' branch has a fix for this issue but it also contains other changes beside that.
