### ISSUE TITLE
'Save Changes' notification pops up even with no pending changes on some components

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#206]
Branch: feature/actionrewrite
Steps to reproduce:
1. Drag "Accordion (empty)" component onto page
2. Click on the component to open the editor
3. Cancel editing without changing anything

Expected result:
Editor should close without notifying user because nothing has been changed

Actual result:
"Do you want to save" dialog opens

Notes:
This issue is caused by the comparison at line 37 in editComponent.js:
https://github.com/headwirecom/peregrine-cms/blob/feature/actionrewrite/admin-base/ui.apps/src/main/js/stateActions/editComponent.js#L37

The json for the page view has an empty array as the value for accordiontoggle, while the editor has null.

![emptyaccordion](https://user-images.githubusercontent.com/5474176/63732364-c91ed980-c828-11e9-8b81-71c4dcad566f.PNG)

**Comment by flx-sta** [comment]
@bkheadwire what accodion component are you refering too?
- themeclean?
- themeclean-flex?
- example?

**Comment by reusr1** [comment]
this was due to the editor returning an empty array for some properties where the input to the form was null. Fixed the issue by treating empty array and null the same in the comparison
