### ISSUE TITLE
Assets with spaces in their name don't work

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#230]
When you upload an asset that has one or more spaces in his name you get the following Error in your browser console and the build doesn't get displayed:
Failed to load resource: the server responded with a status of 404 (Not Found)
![Bildschirmfoto 2019-09-19 um 09 19 45](https://user-images.githubusercontent.com/50013766/65223179-e7db5d80-dac0-11e9-8236-4e5a5b2308fc.png)

**Comment by reusr1** [comment]
@schaefa seems to be related to #231

**Comment by schaefa** [comment]
This issue is fixed in the Rendition Servlet

**Comment by reusr1** [comment]
@FabianHaupt this should be fixed in develop, please check if you have a moment and close the ticket if it's all good for you

**Comment by flx-sta** [comment]
@reusr1 seems to be working perfectly fine 👍
