### ISSUE TITLE
Assets with umlauts in their name don't work

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#231]
When you upload an asset that has one or more umlauts in his name you get the following Error in your browser console and the build doesn't get displayed:
Failed to load resource: the server responded with a status of 404 (Not Found)
![Bildschirmfoto 2019-09-19 um 09 20 05](https://user-images.githubusercontent.com/50013766/65223393-66d09600-dac1-11e9-8738-c143df569645.png)

**Comment by reusr1** [comment]
@schaefa seems to be a backend issue as the image gets uploaded and processed but the url to request it does not work.

**Comment by schaefa** [comment]
Created a fix for it that will force a conversion of the file name if the character encoding is not in UTF-8

**Comment by reusr1** [comment]
@FabianHaupt this should be fixed in develop, please check if you have a moment and close the ticket if it's all good for you

**Comment by bkheadwire** [comment]
The upload is fixed, but fetching the image with the non-ascii character in the name fails.

**Comment by bkheadwire** [comment]
Just confirmed that this is a windows issue - default property:
`file.encoding = Cp1252`

Adding
`-Dfile.encoding="UTF-8"`
to sling startup fixed the problem. Recommend adding this to percli start command.

**Comment by flx-sta** [comment]
@reusr1 seems to be working perfectly fine 👍
