### ISSUE TITLE
Add option to delete site package during site deletion

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#236]
When sites are created, we automatically create a package that includes all of the paths for that site's content and components. When sites are deleted, we don't delete those packages automatically (this is intentional - it's meant to act as a backup mechanism). We should make deleting the most recent package for that site an option when the site is deleted.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/5
