### ISSUE TITLE
RTE causes jumping when an image is present

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#246]
When editing text in the rich text editor with an image in the same RTE, there is sometimes a noticeable flashing effect caused by the image reloading the causing the content to jump around.

![lr2](https://user-images.githubusercontent.com/2624171/66145457-bdf56100-e5bf-11e9-9009-28b683e025d4.gif)

**Comment by FabianHaupt** [comment]
@dna113p Could you please elaborate why this issue was closed?

**Comment by reusr1** [comment]
@FabianHaupt the issue only happens if you disable caching in the devtool network tab - hence it is not really a defect

**Comment by FabianHaupt** [comment]
Ok good to know
