### ISSUE TITLE
Tags created outside /content/objects/tags are not available to use

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#247]
Steps to reproduce:
1. Go to the objects UI
2. Navigate into the folder for an individual site
3. Create a tag object
4. Go to the assets UI
5. Navigate into the folder for the same site you created the tag for
6. Select an asset and edit its properties
7. Attempt to apply the tag you created

Expected result:
The tag should be available in the dropdown to apply to the asset

Actual result:
The tag is not available in the list

Notes:
Currently tags are only global - if you create them under /content/objects/tags, any site can use them. If you create them anywhere else, they don't appear to be accessible at all. Unsure whether the solution is to disallow the creation of tags outside of /content/objects/tags OR to enable their use from other locations.

**Comment by flx-sta** [comment]
we should rethink the tag concept in whole.

I think it would be better to have like a general "tags" object with a collection in it. 
But i don't know what all behind the tag logic

**Comment by reusr1** [comment]
tags are now implemented per tenant as a sub node called tags in the tenants objects node
