### ISSUE TITLE
Object explorer/creation UI lacks clarity

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#248]
The UX around objects leaves a lot to be desired. Starting from the first tab of object creation, you're presented with a list of names of object types with no information about what any of them are meant to do or how they work.

![objecttype](https://user-images.githubusercontent.com/5474176/66244046-8ec41a00-e6bb-11e9-8213-7f4b79c686df.PNG)

There's a similar lack of information on the final tab - which is misleadingly called "verify" even though it's actually the part of the form where you enter the information for the object. There should be instructions or at least descriptions for how you're meant to use the individual fields.

![objectverify](https://user-images.githubusercontent.com/5474176/66244193-2b86b780-e6bc-11e9-853e-a8d3ea466f6b.PNG)

In the object explorer, you can create nonsensical hierarchies where objects of one type can exist under objects of another, unrelated type.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/6
