### ISSUE TITLE
Tag selection UI only shows tag names, doesn't scale well with lots of tags

### ISSUE THREAD

**Issue by bkheadwire** [headwirecom/peregrine-cms#249]
Right now, our UI for selecting tags for a page/asset is a dropdown that flattens all the tags into a single list. It only shows their names, not their display values.

![04-list](https://user-images.githubusercontent.com/5474176/66245809-ef0b8980-e6c4-11e9-88ee-1aa7da937eb9.png)

This strategy for picking tags doesn't scale well with large numbers of tags and multiple hierarchies in the same system. Would probably be better to replicate the pathbrowser experience, allowing for navigation of the hierarchies.

**Comment by flx-sta** [comment]
I don't know. Would be better to provide both ways

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/7
