### ISSUE TITLE
support for sitemap.xml

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#253]

**Comment by NMuzaffar** [comment]
Hello @reusr1, can you please add some description. Currently in meta:proc fork we have SitemapServlet (adapted from AC Commons) and RobotsServlet for robots.txt. Maybe we can use that.

**Comment by reusr1** [comment]
would be interesting to see what you currently have - themeclean flex and the k8s installhandles robots.txt already but does not handle sitemap. a simple servlet would be a good first cut but would have to be evaluated for larger sites.

**Comment by NMuzaffar** [comment]
* https://github.com/meta-proc/peregrine-cms/blob/metaproc-develop/platform/base/core/src/main/java/com/peregrine/seo/SitemapServlet.java 

* https://github.com/meta-proc/peregrine-cms/tree/metaproc-develop/admin-base/ui.apps/src/main/content/jcr_root/perapi/admin/sitemap

Currently we create servlet node under parent page and servlet gets invoked.

<img width="728" alt="Screenshot 2019-10-13 at 00 07 36" src="https://user-images.githubusercontent.com/24642899/66708232-9d5ea100-ed4d-11e9-98d1-ae8e2ff0ae12.png">

**Comment by flx-sta** [comment]
Sitemap has been implemented by @reggie7 and is merged into develop.

See #269
