### ISSUE TITLE
"Cannot read property 'experiences' of undefined" after first page load

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#261]
When opening the editor and trying to edit a component on the very first load of peregrine and the editor you can't press the "OK" Button because it's throwing an JS exception

<img width="606" alt="Screenshot 2019-11-08 at 08 18 46" src="https://user-images.githubusercontent.com/50131232/68457454-9fa70480-0200-11ea-9148-3f748a255c78.png">

**Comment by flx-sta** [comment]
@reusr1 its just a quick fix. please merge asap

**Comment by reusr1** [comment]
done
