### ISSUE TITLE
language selection for pages

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#271]
we'd love to provide the ability to set the language for a site structure. While https://github.com/headwirecom/peregrine-cms/pull/203 adds this feature its a bit heavy handed as it sets the language per page. This makes it hard to change the language at a later point. 

Looking for input from editors on how to provide this functionality and from developers to consider all uses cases that need to be covered

**Comment by flx-sta** [comment]
I'd say that setting per page is not completely wrong but a bit too much work if its not recursive.

So I'd say if you set the language of a page the sub-pages should inherit that language, EXCEPT they have a individual one set manually

**Comment by reusr1** [comment]
an additional way to handle this would be for example if the language is specified in the path of the page

/content/sites/mysite/en and /content/sites/mysite/de (or en_us, de_de) could serve as the language specifier

A general use case for a language switcher on the website itself driven from the language settings may be useful as well. 

We should also consider the use case where we translate content in place like in the admin interface.

**Comment by flx-sta** [comment]
see #297
