### ISSUE TITLE
Native support for SEO and social enablement

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#272]
Native support for SEO and social enablement came up during the first Peregrine-CMS Live Community Hangout (11/20/19). What are the community's thoughts around including first class support for meta tags (e.g., Open Graph, Twitter and Facebook), microdata formats (JSON-LD and Schema.org), canonical URL support, RSS feeds, site maps, etc.?  The goal should be to provide sensible defaults for instrumenting these features into Peregrine sites and pattern the "frictionless" experience of enabling SEO and social that is provided by platforms like Wordpress.

**Comment by flx-sta** [comment]
I'd say it would be better to have it as some kind of "plugin" but it could also be implemented by default

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/13
