### ISSUE TITLE
default content for pages

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#274]
we started a new feature currently called boilerplate. the idea is to be able to have a couple of already authored content pages like a home page, news article page, etc that use a template and provide a couple stubbed out components on the page an author can then change

current work is at
https://github.com/headwirecom/peregrine-cms/tree/feature/boilerplate

some questions that came up during the nov-20-2019 community hangout:

- would be nice to make sure some components can not be deleted
- would be nice to also control the components allowed to be added on a page when created from a boilerplate

**Comment by flx-sta** [comment]
Weren't you also looking for a better name for this feature?

**Comment by flx-sta** [comment]
Also @reusr1 small gifs to present the feature would be helpful (my opinion)

**Comment by reusr1** [comment]
issue was addressed in PR 305 (https://github.com/headwirecom/peregrine-cms/pull/305) and was renamed to skeleton-pages
