### ISSUE TITLE
you can delete templates that are used in sites/pages

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#282]
Currently it is possible to delete templates that are being used in a page/site (or multiple)

We should prevent 
### Slack Log 
![image](https://user-images.githubusercontent.com/50131232/73074445-f0ea9a00-3eb9-11ea-9ae2-5e375894f2cf.png)

**Comment by ehdatheadwire** [comment]
Closing issue and relocating to the enhancements queue here: https://github.com/peregrine-cms/enhancements/issues/37. This is likely not required for 1.0.0 release, although it's definitely something to look into.
