### ISSUE TITLE
example - Carousel: can't insert slides

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#290]
### Reproduction

1. open the example vuejs site in the editor 
1. put the `Carousel` component somewhere on the page
1. select it  (to open the editor panel) 
1. insert a slide by clicking the "+" icon at the bottom
1. click on the image-icon at the "image-source" input
1. http-status 500
<img width="661" alt="Screenshot 2020-01-24 at 22 18 09" src="https://user-images.githubusercontent.com/50131232/73104746-70e32500-3ef7-11ea-9b12-8cf3c756e66a.png">

-----------

_on develop & develop-sling11_

**Comment by ehdatheadwire** [comment]
Confirmed that this is still an issue and it's not a very good user experience. But is it required for 1.0.0? @reusr1 that's likely a question for you. I could see this as being a fast follow item that we'd want to ensure works.

**Comment by reusr1** [comment]
PR merged, issue fixed
