### ISSUE TITLE
sitemaps cache: Missing priviliges for system user "sitemaps-cache"

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#295]
When enabling the sitemaps feature there is an issue right now with the privileges.

A system user "sitemaps-cache" is supposed to write the sitemap file into `var/sitemaps` but does not have the required privileges initially.

This is the initial ruling inside `/var/sitemaps`

![image](https://user-images.githubusercontent.com/50131232/73262012-8f823e00-41cd-11ea-9b4b-3f8098095f20.png)

------------

_to work around this issue you can manually add the privileges_

**Comment by flx-sta** [comment]
@reggie7

**Comment by flx-sta** [comment]
@reusr1 can you assign reggie this issue?

**Comment by reusr1** [comment]
@schaefa can you please add the creation of the service user?

**Comment by reggie7** [comment]
The user gets created, but @Felix-Puetz didn't get the permisions for it on `/var/sitemps` within the deploy. It was working for me though since I've put [`rep:policy`](https://github.com/headwirecom/peregrine-cms/pull/269/files#diff-c9240cf9893363e5bb9f45f1b4bd6d57) in place...

**Comment by reggie7** [comment]
@Felix-Puetz I have checked it locally in both `issues/93` and `develop`. Works for me in there. Can you check on your side too? I ran it in a fresh instance.
