### ISSUE TITLE
Get rid of the "welcome" page

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#298]
After implementing the welcome page as a modal in #166 we should get rid of the welcome page

**Comment by reusr1** [comment]
the first 5 minute experience of peregrine has to be reevaluated, imho

**Comment by cmrockwell** [comment]
When I reinstalled Peregrine CMS, the 'Welcome' page /index.html is the one that comes with Sling. I was pretty sure something went wrong, but Home /content/admin.html works. 
I was looking for the link to Peregrine's Backend Javadocs. I think this used to be on the Welcome screen,

**Comment by reusr1** [comment]
the welcome page has been removed/combined with the tenant selector (part of issues/93 branch)
