### ISSUE TITLE
Very high number in input breaks component

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#300]
### Reproduction
- Open any page editor of a themeclean page
-  add Component `breadcrumb` to a page
-  set number of levels to something like `99999999999999999999999999999999999999999999999999999999999999`
- the number is converted by the system as seen in the Screenshot
- The component is not  renderer properly anymore

### Screenshot
![image](https://user-images.githubusercontent.com/50131232/73435698-71414d00-4349-11ea-8f31-a3e84693a111.png)

**Comment by ehdatheadwire** [comment]
@Felix-Puetz can this go into the FFF queue? (Fast Follow Fixes) Looks to be something we should still address but not necessarily for 1.0.0. Thanks!

**Comment by flx-sta** [comment]
@ehdatheadwire My opinion: not very important and not necessary for 1.0.0 because its a very much edge-case. A user that would encounter this was trying to push his luck anyway

**Comment by ehdatheadwire** [comment]
Great thanks @Felix-Puetz. I'll move to the enhancements queue and update this ticket with the new link.

**Comment by ehdatheadwire** [comment]
Relocated to: https://github.com/peregrine-cms/enhancements/issues/60
