### ISSUE TITLE
Color Palettes selector for "new site"

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#304]
## About
Creating a new site based on themeclean-flex should result in a palettes selector where you can choose the default palette

### themeclean-flex

https://slack-files.com/T67UM8P8F-FTZL3QG0Z-b9cf3d5cf2
![image](https://user-images.githubusercontent.com/50131232/75017345-1a80ec00-548d-11ea-82bc-a88eb530f7cc.png)

**Comment by reusr1** [comment]
closing this issue as the code has been merged
