### ISSUE TITLE
new name for "boilerplate" feature (POLL)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#310]
### Instructions

**Please put thumup on your favorite choice**

**Comment by flx-sta** [comment]
prototype

**Comment by flx-sta** [comment]
Stock

**Comment by flx-sta** [comment]
blueprint

**Comment by flx-sta** [comment]
skeleton

**Comment by Felix-Puetz** [comment]
### END OF POLL

**Comment by reusr1** [comment]
> Stock

**Comment by flx-sta** [comment]
The Winner is:

Skeleton (-pages)

------------------------------

![image](https://user-images.githubusercontent.com/50131232/76229378-61f3d000-6222-11ea-9c9f-d7d178e76663.png)
