### ISSUE TITLE
NPE happens when pages are replicated

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#321]
As I work on replication, I'm finding a common problem with pages that I replicate. Rendering breaks (white page) and an error is printed on author and publish instances. It happens whether the default replication is remote or local; other replication options were not tested 

**Note;** The problem seems to be related to `nt:unstructured` nodes under jcr:content having the `jcr:mixinTypes=per:Replication` Deleting jcr:mixinTypes from the node directly jcr:content fixes the problem.

The page does not render when the error below occurs. I have reproduced it on /content/sites/themecleanflex/index by taking the steps

1. go to /content/admin/pages/edit.html/path:/content/sites/themecleanflex/index
2. add a "container block" to the container
3. add a text component inside the container block. add some text
4. go to /content/admin/pages.html/path:/content/sites/themecleanflex and replicate the index page
5. observe that /content/sites/themecleanflex/index.html does not render, and there is the error below

> 08.03.2020 16:20:24.761 *ERROR* [0:0:0:0:0:0:0:1 [1583698824728] GET /content/sites/themecleanflex/index.html HTTP/1.1] org.apache.sling.scripting.sightly.render.AbstractRuntimeObjectModel Cannot access method mergedForScript on object com.peregrine.nodetypes.merge.PageMerge@7b1ab357
> java.lang.reflect.InvocationTargetException: null
>     at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.apache.sling.scripting.sightly.render.AbstractRuntimeObjectModel.getObjectNoArgMethod(AbstractRuntimeObjectModel.java:344)
>     at org.apache.sling.scripting.sightly.render.AbstractRuntimeObjectModel.getObjectProperty(AbstractRuntimeObjectModel.java:318)
>     at org.apache.sling.scripting.sightly.impl.engine.runtime.SlingRuntimeObjectModel.getProperty(SlingRuntimeObjectModel.java:47)
>     at org.apache.sling.scripting.sightly.render.AbstractRuntimeObjectModel.resolveProperty(AbstractRuntimeObjectModel.java:101)
>     at org.apache.sling.scripting.sightly.apps.pagerender.vue.structure.page.page_html.render(page_html.java:501)
>     at org.apache.sling.scripting.sightly.java.compiler.RenderUnit.render(RenderUnit.java:48)
> ...
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException: null
>     at com.peregrine.nodetypes.merge.PageMerge.mergeArrays(PageMerge.java:190)
>     at com.peregrine.nodetypes.merge.PageMerge.merge(PageMerge.java:160)
>     at com.peregrine.nodetypes.merge.PageMerge.mergeArrays(PageMerge.java:182)
>     at com.peregrine.nodetypes.merge.PageMerge.merge(PageMerge.java:160)
>     at com.peregrine.nodetypes.merge.PageMerge.getMerged(PageMerge.java:121)
>     at com.peregrine.nodetypes.merge.PageMerge.getMergedForScript(PageMerge.java:97)
>     ... 79 common frames omitted

<img width="1189" alt="Screen Shot 2020-03-08 at 2 26 14 PM" src="https://user-images.githubusercontent.com/1811207/76170790-a4060e80-615b-11ea-9205-c1d023183d43.png">

**Comment by cmrockwell** [comment]
Aside from deleting the property `jcr:mixinTypes=per:Replication` another way to resolve the error and rendering problem is to add `sling:resourceType=themecleanflex/components/container` which as the screenshot shows is missing

**Comment by cmrockwell** [comment]
Given I create a new page using the theme-clean-flex `base-page` template
And then open the new page in the page editor
And I add a container-block inside the main container
Then the parent container should have a sling:resourceType (but it does not)

<img width="1336" alt="Screen Shot 2020-03-09 at 4 06 50 PM" src="https://user-images.githubusercontent.com/1811207/76253103-6919de80-6220-11ea-850e-e23d940d777a.png">

I think the resource type is needed to help identify components for the `merge` method PageMerge.java line 156 seeks to continue...

private Map merge(Map template, Map page) {
        TreeMap res = new TreeMap();
        res.putAll(template);
        for (Object key: page.keySet()) {
            Object value = page.get(key);
            log.debug("key is {}", key);
            log.debug("value is {}", value == null ? value : value.getClass());
            **if(key.equals(COMPONENT) && value.equals(NT_UNSTRUCTURED)) continue;**
            if(value instanceof Map) {
            } else if(value instanceof ArrayList) {
                mergeArrays((ArrayList) res.get(key), (ArrayList) value);
            } else {
                res.put(key, value);
            }
        }
        return res;
    }

**Comment by reusr1** [comment]
@cmrockwell @schaefa I think there is a defect that the sling:resourceType for non existing parent nodes are not copied over from the template at this point

**Comment by cmrockwell** [comment]
@reusr1 @schaefa I was thinking about that yesterday, but it doesn't seem correct to copy resources and properties from templates to the pages; given that template components are merged in with page components. Maybe just copying the resourceType for template containers would be enough? 

Another option would be to investigate why `jcr:mixinTypes=per:Replication`  are added on every singe node. What is the purpose of putting the per:Replication mixin on component nodes instead of on specific parent types: per:PageContent, per:AssetContent, per:Asset, per:Page, per:Object or per:ObjectDefinition ?

**Comment by reusr1** [comment]
@cmrockwell was able to reproduce the issue, will dig into it deeper
