### ISSUE TITLE
landing page translation "scope" wrong

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#325]
![image](https://user-images.githubusercontent.com/50131232/77583723-d8125b00-6ee1-11ea-9f29-ee7c232614f9.png)
```
weired T[ 
] 
```

all over the place

**Comment by flx-sta** [comment]
fixed by chaning to never show T[] to the user only to devs (loglevel.fine)

**Comment by flx-sta** [comment]
@reusr1 please validate

**Comment by reusr1** [comment]
looks good - thank you
