### ISSUE TITLE
javadocs link ends in "404"

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#327]
![image](https://user-images.githubusercontent.com/50131232/77584672-82d74900-6ee3-11ea-8a25-50b671f6de31.png)

**Comment by reusr1** [comment]
that is normal if the javadocs are not built into the your instance

**Comment by cmrockwell** [comment]
I would suggest deleting stuff that does not work and simplifying the process even if that means generating the aggregated docs as html under the parent target directory. At least there should be one reliable way to view the API. It doesn't need to be fancy.

There is maven stuff related to this javadocs bug commented out.

 
`<plugin>`
`<groupId>org.apache.maven.plugins</groupId>`
`<artifactId>maven-javadoc-plugin</artifactId>`
...
`<id>attach-javadocs</id>`
...

`<module>autodocs</module>`
`<module>tooling/maven/archetypes/project</module>`

maybe think there is no way to build javadocs as html, let alone push them to the instance such that /content/apidocs/cms/index.html resolves. Running `mvn javadoc:javadoc` does not work.

maven-javadoc-plugin version is 2.10.4. It could be updated to 3.2.0
http://maven.apache.org/plugins/maven-javadoc-plugin/examples/aggregate.html

**Comment by reusr1** [comment]
@cmrockwell I have started looking into this a bit more and have been working on it but with a bit lower priority than other issues

I'd suggest we do the following: 

- if you install with percli or docker the javadocs are present
- if you run a local maven build the docs are only pushed when a profile is used to do so

also see https://github.com/headwirecom/peregrine-cms/commit/75d83ededbf29b88546df09c83d78b9092ce5217 for the upgrade to the maven site plugin and dealing with the doclint issue of newer java versions

**Comment by reusr1** [comment]
@Felix-Puetz the 404 error for the javadoc page should now be gone and was replaced by how to build and push the javadocs into your local environment - feel free to improve the html :-)

**Comment by cmrockwell** [comment]
@reusr1  Would it be possible for you to also post the instructions here to this ticket? Checking out and deploying the develop branch is inconvenient right now because the content restructuring. The develop branch is no longer compatible with the content in my instances. Thank you so much 👍

**Comment by reusr1** [comment]
@cmrockwell its actually in the issues/93 branch - just run `mvn site -PinstallDocs` to get the docs into your instance

**Comment by cmrockwell** [comment]
Thanks for instructions, Unfortunately it's not working for me. After pulling the latest issues/93 and running `mvn site -PinstallDocs` at the parent level, I get the following repeated 24 times.

[INFO] --- wcmio-content-package-maven-plugin:1.6.0:install (aggregate-install) @ parent ---
[INFO] Check bundle activation status...
[INFO] Upload and install (force) parent-1.0-SNAPSHOT.zip to http://localhost:8080/bin/cpm/
[INFO] ERROR: Call failed with HTTP status 400 Bad Request
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
<title>400 javax.jcr.RepositoryException: java.io.IOException: Read end dead</title>
</head>
<body>
<h1>javax.jcr.RepositoryException: java.io.IOException: Read end dead (400)</h1>
<p>The requested URL /bin/cpm/package.upload.json resulted in an error in com.composum.sling.core.pckgmgr.PackageServlet.</p>
<h3>Request Progress:</h3>
<pre>
      0 TIMER_START{Request Processing}
      4 COMMENT timer_end format is {&lt;elapsed microseconds&gt;,&lt;timer name&gt;} &lt;optional message&gt;
     12 LOG Method=POST, PathInfo=null
     20 TIMER_START{handleSecurity}
  18139 TIMER_END{18117,handleSecurity} authenticator org.apache.sling.auth.core.impl.SlingAuthenticator@131c5573 returns true
  21109 TIMER_START{ResourceResolution}
  21203 TIMER_END{92,ResourceResolution} URI=/bin/cpm/package.upload.json resolves to Resource=ServletResource, servlet=com.composum.sling.core.pckgmgr.PackageServlet, path=/bin/cpm/package
  21211 LOG Resource Path Info: SlingRequestPathInfo: path=&apos;/bin/cpm/package&apos;, selectorString=&apos;upload&apos;, extension=&apos;json&apos;, suffix=&apos;null&apos;
  21211 TIMER_START{ServletResolution}
  21215 TIMER_START{resolveServlet(/bin/cpm/package)}
  21228 TIMER_END{12,resolveServlet(/bin/cpm/package)} Using servlet com.composum.sling.core.pckgmgr.PackageServlet
  21230 TIMER_END{18,ServletResolution} URI=/bin/cpm/package.upload.json handled by Servlet=com.composum.sling.core.pckgmgr.PackageServlet
  21233 LOG Applying Requestfilters
  21241 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
  21245 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
  21249 LOG Applying Componentfilters
  21256 TIMER_START{com.composum.sling.core.pckgmgr.PackageServlet#0}
1027964 LOG Applying Error filters
1027976 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
1027995 TIMER_START{handleError:status=400}
1028403 TIMER_END{404,handleError:status=400} Using handler org.apache.sling.servlets.resolver.internal.defaults.DefaultErrorHandlerServlet
1028768 TIMER_END{1028763,Request Processing} Dumping SlingRequestProgressTracker Entries
</pre>
<hr>
<address>ApacheSling/2.6 (jetty/9.3.15.v20161220, OpenJDK 64-Bit Server VM 1.8.0_242, Mac OS X 10.13.6 x86_64)</address>
</body>
</html>
[INFO] ---------------
[INFO] HTTP call failed, try again (4/24) after 5 second(s)...

**Comment by cmrockwell** [comment]
Scratch that! I stopped and started using percli and upload worked via composum :-)
<img width="1070" alt="Screen Shot 2020-04-15 at 4 06 14 PM" src="https://user-images.githubusercontent.com/1811207/79383441-2c35bb80-7f33-11ea-94d8-6635a1a865fe.png">

**Comment by reusr1** [comment]
great! closing the issue for now
