### ISSUE TITLE
pathbrowser should show what you are moving (if moving)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#328]
Currently when moving a page you cannot see in the pathbrowser what you chose to move.. it think that inconvinient

![image](https://user-images.githubusercontent.com/50131232/77584940-f7aa8300-6ee3-11ea-9214-0666e7765834.png)

**Comment by flx-sta** [comment]
![image](https://user-images.githubusercontent.com/50131232/77897772-69832380-727a-11ea-9c2d-c097d9d80053.png)

@reusr1 please validate (ignore that weired black gap  on the left side below the tabs, that wasnt pushed or comitted)

**Comment by reusr1** [comment]
@Felix-Puetz looks good
