### ISSUE TITLE
help menu item should never be not shown

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#331]
the "help" icon is sometimes not rendered.

Probably because some conditions for it are not `true` but this makes the menu-length very inconsistent.

A simple disabled with some styling that makes it look disabled should work

**Comment by reusr1** [comment]
@Felix-Puetz the help menu item is bound to the tour node on the page. If no tour node is available the help menu item is not available either. I changed it for now to always show the help menu item but disable it if there is no tour available
