### ISSUE TITLE
assets links to objects or switching from object to assets doesnt update path

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#332]
this seems to happen after creating a new folder in objects and then switching to assets

very weired behaviour

**Comment by Felix-Puetz** [comment]
this seems to happen after creating a new folder in objects and then switching to assets

**Comment by reusr1** [comment]
this seems to happen when the create folder wizard for objects is called. check out state/tools/assets as soon as the wizard is opened

**Comment by reusr1** [comment]
@Felix-Puetz can you please validate and close if ok?

**Comment by flx-sta** [comment]
@reusr1 works perfectly fine now. could now reproduce 👍
