### ISSUE TITLE
themeclean-flex not showing as site-template nor as a tenant

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#333]
after uploading themeclean-flex it's not showing up anywhere anymore

**Comment by reusr1** [comment]
@Felix-Puetz themeclenflex and themeclean currently only show up as a selection to create a new site. The new UI does not allow to _play_ with the themes directly anymore unless you switch the template property on the tenant.

**Comment by flx-sta** [comment]
@reusr1 i know but its not showing up as an option when creating a new tenant.
Thats why I called it "site-template"

**Comment by reusr1** [comment]
@Felix-Puetz that works for me - did you use the right branch of themeclean-flex? branch is feature/contentrestructure

**Comment by flx-sta** [comment]
@reusr1 whops...
