### ISSUE TITLE
themeclean - article media- Overlay - 404 (Not Found)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#336]
GET http://localhost:8080/content/asdfg/pages/null 

![image](https://user-images.githubusercontent.com/50131232/77589702-79061380-6eec-11ea-9916-e372d08bc8ab.png)

**Comment by reusr1** [comment]
@Felix-Puetz ready to review, should work in both themeclean and themecleanflex now

**Comment by flx-sta** [comment]
could not reproduce in themeclean of themeclean-flex.
👍
