### ISSUE TITLE
themeclean - article pager - onAdd -"Update with Form request to undefined failed

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#338]
![image](https://user-images.githubusercontent.com/50131232/77589875-c97d7100-6eec-11ea-9e23-7c586a35cb8f.png)

**Comment by reusr1** [comment]
@Felix-Puetz issue should be addressed, please verify

**Comment by flx-sta** [comment]
same issue as in #340 
Further adressing will happen there!!
