### ISSUE TITLE
themeclean - Adding image in RTE throws 404: Not Found

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#339]
![image](https://user-images.githubusercontent.com/50131232/77589976-fb8ed300-6eec-11ea-8526-75171915cd84.png)

**Comment by flx-sta** [comment]
@reusr1 please validate

**Comment by flx-sta** [comment]
The Problem was l. 121
```javascript
 self.browserRoot = isImage ? `${getBasePath()}/assets` : `${getBasePath()}/pages`;
```
There was some unknown `getBasePath` method in use since the `self.` in front of it was misssing:
```javscript
 self.browserRoot = isImage ? `${self.getBasePath()}/assets` : `${self.getBasePath()}/pages`;
```

**Comment by reusr1** [comment]
@Felix-Puetz works like a charm - thank you
