### ISSUE TITLE
<tenant> -> Tools -> JCR Query Tool link wrong

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#343]
For me it linked to "objects" but maybe that was just the previously visited link that was chosen

![image](https://user-images.githubusercontent.com/50131232/77591117-9688ac80-6eef-11ea-93c7-f9c1fcfcff30.png)

**Comment by reusr1** [comment]
that one is weird, works the second time you click it

**Comment by reusr1** [comment]
bad key used for a v-for v-bind:key - should be fixed now, @Felix-Puetz please validate

**Comment by flx-sta** [comment]
@reusr1 could not reproduce 👍
