### ISSUE TITLE
rename asset throws "TypeError: currNode.split is not a function"

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#345]
![image](https://user-images.githubusercontent.com/50131232/77591517-6392e880-6ef0-11ea-93db-b8bab8b53b6e.png)

**Comment by reusr1** [comment]
@Felix-Puetz issue should be fixed, please validate

**Comment by flx-sta** [comment]
@reusr1 works perfectly fine now 👍
