### ISSUE TITLE
link to root in sub-path breadcrumbs missing

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#346]
We should give a link to the root path otherwise the only option to get there is to click ".." at the very top

![image](https://user-images.githubusercontent.com/50131232/77591872-3eeb4080-6ef1-11ea-9951-9ac239637d33.png)

**Comment by reusr1** [comment]
@Felix-Puetz I added one more level to the pathfield, however, there seems to be a bit of a styling issue - it changes the possition a bit depending on what tool you are on. Can you please have a look at that? thank you

**Comment by flx-sta** [comment]
@reusr1 fixed that with flexbox
take a look at it

**Comment by reusr1** [comment]
@Felix-Puetz did you push this change? I do not see this working on objects

**Comment by flx-sta** [comment]
I pushed it. yeah
You can see this in commit da97840b450fc255f434c00aab498b574838b068

**Comment by flx-sta** [comment]
Well now the sub-nav in the page-editor is wrong
![image](https://user-images.githubusercontent.com/50131232/77883021-90cdf680-7262-11ea-9939-efadb6406579.png)
