### ISSUE TITLE
objects created from "select" cannot be selected in explorer

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#347]
![image](https://user-images.githubusercontent.com/50131232/77592052-9b4e6000-6ef1-11ea-83f0-b36758298002.png)

**Comment by reusr1** [comment]
@Felix-Puetz was not able to reproduce this issue

**Comment by flx-sta** [comment]
@reusr1 i can reproduce it but can't really see why this is happening. seems to be an api issue
![image](https://user-images.githubusercontent.com/50131232/77782992-6c9ec980-7058-11ea-8e1e-de116a060cd9.png)

**Comment by reusr1** [comment]
@Felix-Puetz maybe I do not follow the same steps as you do but I am not able to reproduce

**Comment by flx-sta** [comment]
@reusr1 you go to:

1. objects
1. click "add object" button
1. in "select template" choose "select" at the very bottom
1. give it a name
1. finish the creation
1. try to select it in explorer

**Comment by reusr1** [comment]
@Felix-Puetz closing this issue - I removed the select object type from the list as it is missing it's java model - we have to rethink the objects anyhow with this content restructure
