### ISSUE TITLE
One Click Update

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#350]
There are main reasons WordPress is so popular: 
1) You don't need to be developer to use it.
2) You don't need IT to maintain it. They make updating very easy. 

<img width="996" alt="Screen Shot 2020-03-27 at 12 24 14 PM" src="https://user-images.githubusercontent.com/1811207/77777424-ecf80700-7025-11ea-8010-0b08b78cacf1.png">

Please consider adding a One Click Update for Peregrine CMS from the Welcome screen.
<img width="864" alt="Screen Shot 2020-03-27 at 12 17 02 PM" src="https://user-images.githubusercontent.com/1811207/77777516-13b63d80-7026-11ea-9987-2727a12a5b84.png">

There could be a process to check the core packages installed have the latest versions by fetching https://vagrant.headwire.com/peregrine/sling11/packages.txt and comparing to what is currently installed.

base.ui.apps-1.0-SNAPSHOT.zip
external-1.0-SNAPSHOT.zip
felib.ui.apps-1.0-SNAPSHOT.zip
replication.ui.apps-1.0-SNAPSHOT.zip
node-js.ui.apps-1.0-SNAPSHOT.zip
node-js.ui.apps.script-1.0-SNAPSHOT.zip
pagerender-vue.ui.apps-1.0-SNAPSHOT.zip
admin.ui.apps-1.0-SNAPSHOT.zip
admin.ui.materialize-1.0-SNAPSHOT.zip
admin.sling.ui.apps-1.0-SNAPSHOT.zip
example-vue.ui.apps-1.0-SNAPSHOT.zip
themeclean-ui.apps-1.0-SNAPSHOT.zip
themecleanflex.ui.apps-1.0-SNAPSHOT.zip

When a user (admin) clicks Update Now, they might go to a update page under Tools where they can see more details about the packages needing to be installed.

**Comment by reusr1** [comment]
@cmrockwell totally agree with you on the feature. As a first pass I however think it will be easier to add this to percli with `percli server update` as the command

**Comment by cmrockwell** [comment]
That would be awesome! Thanks for considering this. Do you think the project might also adopt versions on the packages sometime soon?

**Comment by reusr1** [comment]
@cmrockwell yes, semantic versioning of the packages is also in the cards. The goal of peregrine is to move away from the current starter and provide an option that is more - shall we say - cloud ready. The work on this is in progress right now.

**Comment by reusr1** [comment]
@cmrockwell I realized the option we need to update a running peregrine instance with the latest version from the download site already exists: `percli server install -e` will in fact download the latest assets and install them onto your local peregrine instance.
