### ISSUE TITLE
Change of tenant does not reset path

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#352]
Image you have 2 tenants:
1. tenant01
1. tenant02

tenant01 has one page with the path: [..]/pages/index/my-page/my-sub-page

If you now go back to the home-screen by clicking the peregrine icon, switch to tenant02 you go to "Pages" and you can see in the `<pathfield>` that the path cached from the tenant01 is still present although it doesn't exist in tenant02.

![image](https://user-images.githubusercontent.com/50131232/77997004-fa1b3b80-732e-11ea-943e-8e853798eaff.png)
![image](https://user-images.githubusercontent.com/50131232/77996966-ea9bf280-732e-11ea-899a-5a38ddea088d.png)

**Comment by flx-sta** [comment]
@reusr1 should be fixed now.please validate

**Comment by reusr1** [comment]
@Felix-Puetz works as expected, thank you
