### ISSUE TITLE
Clicking 'Edit' on website does not change the state value

### ISSUE THREAD

**Issue by NMuzaffar** [headwirecom/peregrine-cms#354]
Navigating to the website by clicking 'Edit' button on target site does not change the state value 

![Screenshot 2020-03-31 at 11 05 59](https://user-images.githubusercontent.com/24642899/78008684-415df800-7340-11ea-8c4f-10d496bcae8a.png)

![Screenshot 2020-03-31 at 11 08 01](https://user-images.githubusercontent.com/24642899/78008695-44f17f00-7340-11ea-9ebd-61df0aead42e.png)

**Comment by flx-sta** [comment]
This is the source of the problem
![image](https://user-images.githubusercontent.com/50131232/78010152-550a5e00-7342-11ea-8942-56c49296f649.png)

**Comment by flx-sta** [comment]
fixed.
@reusr1 or @NMuzaffar please verify

**Comment by NMuzaffar** [comment]
Fixed
