### ISSUE TITLE
Switch to show internal/template "tenants" (themeclean/-flex)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#355]
![image](https://user-images.githubusercontent.com/50131232/78070544-43ee3b00-739c-11ea-9828-03b9fef06991.png)

**Comment by flx-sta** [comment]
implemented.
please verify @reusr1

**Comment by reusr1** [comment]
@Felix-Puetz I think we should be able to filter by websites, templates and internal sites (maybe a dropdown or tabs may be good for that). Also make sure the colors you choose are ADA compliant (not sure if the blue text on the gray backround passes)

**Comment by flx-sta** [comment]
@reusr1 please verify

**Comment by reusr1** [comment]
@Felix-Puetz we also need to make sure the login page uses ada compliant colors and looks well on mobile devices and tablets

**Comment by reusr1** [comment]
@Felix-Puetz we need to make sure the page looks ok on smaller devices and make sure the colors are ada compliant

**Comment by reusr1** [comment]
went ahead and changed the columns for small and medium screen size to 12 - seems to work well
