### ISSUE TITLE
Login-Page rework

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#356]

**Comment by flx-sta** [comment]
### Desktop
![image](https://user-images.githubusercontent.com/50131232/78225959-531fd680-74cb-11ea-8bc2-7d4e2ca1a032.png)

### Mobile
![image](https://user-images.githubusercontent.com/50131232/78226079-78ace000-74cb-11ea-9261-ed90aa8c47fb.png)

**Comment by flx-sta** [comment]
TODO: remove image on left side in mobile view

**Comment by flx-sta** [comment]
@reusr1 fix mobile view layout

**Comment by reusr1** [comment]
@Felix-Puetz looks good, thank you!
