### ISSUE TITLE
page navigation in the page editing interface

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#357]
when editing a page we currently have to leave the editor and come back to the editor if we want to edit another page. We should add a page navigation element at the top right of the editor

![image](https://user-images.githubusercontent.com/779992/78275889-14881d00-74c7-11ea-94d7-5b6dc35e6821.png)

the dropdown should allow us to browse the page hierarchy of the site as a tree and allow for adding pages

**Comment by flx-sta** [comment]
@reusr1 as we agreed: you start off with this issue

**Comment by flx-sta** [comment]
@reusr1 is this now all oiled up and ready to go for you? (verify)

**Comment by reusr1** [comment]
@Felix-Puetz looks good to me except for 2 things:

1. when changing from page to page in preview mode we loose the preview
2. adding new pages as per the initial requirements is not implemented

I think we can leave the add new page item as it will be hard to implement it nicely in the tree but we have to look at the preview issues - please create a new ticket for 1) and we'll close this one

**Comment by flx-sta** [comment]
> ...
> when changing from page to page in preview mode we loose the preview
> ...

@reusr1 I've tried to reproduce this issue but i could not see this issue taking effect

**Comment by flx-sta** [comment]
Both error have been documented in new issues @reusr1 
Issue closed

**Comment by reusr1** [comment]
@Felix-Puetz looks like we missed implementing this correctly for the templates editor

**Comment by flx-sta** [comment]
Jup...

**Comment by flx-sta** [comment]
@reusr1 now supports templates.
please validate

**Comment by reusr1** [comment]
@Felix-Puetz we need to filter out any nodes that do not have the resourceType set to per:Page as otherwise we confuse the user (for example navigating to the robots.txt file does not work in this case).  I'd suggest we should add an array of allowed node types to the nodetreeitem component and filter against that list

**Comment by Felix-Puetz** [comment]
@reusr1 fixed

**Comment by flx-sta** [comment]
_was a bit quick there_


BUT NOW fixed

**Comment by reusr1** [comment]
@Felix-Puetz please add the list to filter by as a prop to the nodetreeitem - we should also not use v-if for this but change the list to a computed property with a filter - apparently that's better for performance in vue :-)

**Comment by flx-sta** [comment]
@reusr1 pre-filtering is now active

and new issue has been created for the edge-case of having `hasChildren = true` but no `per:Page` children presen (#377)

**Comment by flx-sta** [comment]
@reusr1 any new info about validation?

**Comment by reusr1** [comment]
closing this issue as it works as spec'd
