### ISSUE TITLE
page properties and the actions a user can take on page properties should be available while editing the page

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#359]
the area of the page editor where we expose the list of the components should allow us to also see and edit the same information currently exposed through the 'eye' icon on the /content/admin/pages/pages page (same should be applied to templates)

**Comment by flx-sta** [comment]
Add tabs to the right panel "components" on the page editor view to give the option of editing page properties and perform actions like "move" "rename"

**Comment by reusr1** [comment]
I think this issue should also take in concsderation https://github.com/headwirecom/peregrine-cms/issues/146 - the UX between the 2 panels where page properties will be available should be consistent.

**Comment by flx-sta** [comment]
okay then i have to strap out this part from the `explorerpreviewcontent` and put it into a new component to i can reuse it

**Comment by flx-sta** [comment]
<details>
  <summary>@reusr1 current concept:</summary>
 
 ![image](https://user-images.githubusercontent.com/50131232/78668389-e184c580-78da-11ea-8a4e-9b484af02bed.png)

![image](https://user-images.githubusercontent.com/50131232/78668402-e9446a00-78da-11ea-8d8f-f6d3025552b9.png)
![image](https://user-images.githubusercontent.com/50131232/78668571-2f013280-78db-11ea-8ae6-6878c46eaf8b.png)

</details>

**Comment by flx-sta** [comment]
@reusr1 I'd say you can validate the feature now 👍

**Comment by reusr1** [comment]
@Felix-Puetz looks and works well, the only thing I see is that we have to do something with the (X) in the editor: 
![image](https://user-images.githubusercontent.com/779992/78781034-6a8c1300-7954-11ea-9d49-1455285bffc8.png)
and once you click it we have to make sure people can still get to the scroll bar 
![image](https://user-images.githubusercontent.com/779992/78781110-90b1b300-7954-11ea-8540-e880a9cb2fc0.png)

**Comment by reusr1** [comment]
@Felix-Puetz thank you - looks great
