### ISSUE TITLE
new Navigation concept (menus etc.)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#360]
![image](https://user-images.githubusercontent.com/50131232/78279155-65bffd00-7517-11ea-9e6b-6a738e0280b1.png)

**Comment by Felix-Puetz** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/50131232/78279275-93a54180-7517-11ea-8a01-1092261cb361.png)

**Comment by flx-sta** [comment]
First concept is live in Branch [issues/93](https://github.com/headwirecom/peregrine-cms/tree/issues/93)

![image](https://user-images.githubusercontent.com/50131232/78798036-ce482780-79b8-11ea-9385-2f3e9c1f7520.png)

**Comment by flx-sta** [comment]
all drop-downs are implemented but still have to be styled properly

**Comment by flx-sta** [comment]
@reusr1 please validate

**Comment by reusr1** [comment]
@Felix-Puetz I like the changes, however I think we have to improve the visual on the website name (it's not clear that the tenant switcher and settings are hidden behind it)

`change tenant` should be renamed to `change website` imho

**Comment by reusr1** [comment]
@Felix-Puetz changes look good to me - closing the issue - thanks :-)
