### ISSUE TITLE
Upon creating a new page, the jcr:title property of the jcr:content node is being set to "undefined"

### ISSUE THREAD

**Issue by mckeehanheadwire** [headwirecom/peregrine-cms#361]
Upon creating a new page, the jcr:title property of the jcr:content node is being set to "undefined". The title given during the page creation wizard is stored in the "title" property of the jcr:content node.

This is with the "issues/93" branch of peregrine-cms and the "feature/contentrestructure" of themeclean-flex.

The issue appears to be related to the post to /perapi/admin/createPage.json; the form data is passing the title as "undefined".

**Comment by reusr1** [comment]
@mckeehanheadwire thank you for the fix, the PR has been merged
