### ISSUE TITLE
Restore Deleted Pages and Assets

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#365]
# Feature: Restore Deleted Pages and Assets
Background: 
A critical feature for any CMS is the ability to restore deleted pages and assets. Regularly, someone in our CMS user-base accidentally deletes something, and they need support to help restore whatever was deleted. 

Possible Solutions:
* Nightly AWS backups 
* Scripts that execute Composum to rebuild packages
* UI that enables restoring deletions

Of these possible solutions, the best one is obviously a set of built-in features that allow users to restore deleted stuff.

## Scenario Outline: Create Versions upon Deletion
Given I am a site author of the themecleanflex site 
I click the trash on a *Type* of *Resource* 
Then the system creates a new version of the Resource
And the <Resource> is deleted 

Examples
| Type | Resource |
| Single Page | /content/themecleanflex/pages/library/simpletext/sample-h1 |
| Page with Children | /content/themecleanflex/pages/library/tabs |
| Single Asset | /content/themecleanflex/assets/samples/anchored.jpg |
| Asset Folder | /content/themecleanflex/assets/icons |

## Scenario: Recycle Bin Console
Given I click the 'Dashboard' from the top menu and then 'Recycle Bin' (new)
Then I will see a console showing recently deleted Resources
And each item listed shows _Information_ about deleted resource 
| Information |
| Path |
| Date Deleted |
| Deleted by |
| Actions: Restore and Deleted Forever |

## Scenario: Click Restore 
Given I click an item's *Restore* button
Then I should see a user prompt asking to confirm the item and date to restore
Given I click Yes
Then the item is restored to the selected version
And the resource's children are all restored
And the item is removed from the recycle bin list

## Scenario Example: Click Restore Validation
Given the *Error Cause*
Then the operation fails and there is a notification to the user
Examples
| Error Cause |
| User has insufficient permissions to create the resource |
| A resource with the same name already exists |
| Path above the item being restored was deleted |

**Comment by cmrockwell** [comment]
https://github.com/cmrockwell/peregrine-cms/commits/issues/365

**Comment by cmrockwell** [comment]
Testing for this feature is based on Sling Junit Test Runner.

http://localhost:8080/system/sling/junit/com.peregrine.admin.slingtests.VersionsJTest.html

<img width="1419" alt="Screen Shot 2020-04-29 at 8 47 43 PM" src="https://user-images.githubusercontent.com/1811207/80660810-c5e48900-8a5a-11ea-8764-c75d7463ba51.png">

It's one of my favorite TDD tools in Sling's testing toolset.

**Comment by cmrockwell** [comment]
Dashboard button
<img width="1413" alt="Screen Shot 2020-05-14 at 10 19 23 AM" src="https://user-images.githubusercontent.com/1811207/82057804-e4b96100-9691-11ea-8595-6dbf56e0d6c9.png">

Information List and Restore button
<img width="1288" alt="Screen Shot 2020-05-14 at 1 49 24 PM" src="https://user-images.githubusercontent.com/1811207/82058057-395cdc00-9692-11ea-9d9b-46ca37a61fbc.png">

Ask user confirming item and date to restore 
<img width="1288" alt="Screen Shot 2020-05-15 at 9 53 52 AM" src="https://user-images.githubusercontent.com/1811207/82058084-44b00780-9692-11ea-86f8-1ecc9c8b9be9.png">

Parent path not found error 
<img width="1288" alt="Screen Shot 2020-05-15 at 9 57 07 AM" src="https://user-images.githubusercontent.com/1811207/82058255-804ad180-9692-11ea-8b33-7dacb3c8046b.png">

Restoring an item that already exists
<img width="1288" alt="Screen Shot 2020-05-15 at 9 54 04 AM" src="https://user-images.githubusercontent.com/1811207/82058410-b8eaab00-9692-11ea-8cfe-cb2992bf73a3.png">

**Comment by cmrockwell** [comment]
TODO 

- [X] `AskUser` has incorrect name (using parent’s name instead)
The prompt now uses the path of the item instead of the name
- [x] Delete Forever not implemented
- [x] Proper Recycle Bin set up when a a New Site is created  
- [x] Investigate tar compaction and maintenance considerations
- [x] Show recently deleted first (order by) 
- [X] ACL error scenario
Added back-end handling to check users permissions, and added related front-end error handling.
https://github.com/cmrockwell/peregrine-cms/commit/716ea460c9a494205b64ac813e8d3ba6d9e50737
<img width="1262" alt="Screen Shot 2020-05-26 at 1 24 54 PM" src="https://user-images.githubusercontent.com/1811207/82933002-4c579200-9f57-11ea-8f02-f338e31b5b23.png">

**Comment by cmrockwell** [comment]
Added a button and action to remove items from the Recycle Bin (Delete Forever)
<img width="1279" alt="Screen Shot 2020-05-27 at 2 14 03 PM" src="https://user-images.githubusercontent.com/1811207/83061456-feac5980-a02a-11ea-8d40-268e000a75c7.png">

**Comment by cmrockwell** [comment]
Revision and Compaction Study and considerations

**Procedure**

1. Ran a query and determined total number of before results (10,276)
`SELECT * FROM [nt:frozenNode] as n WHERE ISDESCENDANTNODE ([/jcr:system/jcr:versionStorage])`
2. Used **jconsole** from the command jconsole to launch the JMX GUI
Selected the Peregrine CMS instance running locally
Open the `SegmentRevisionGarbageCollection` and execute `startRevisionGC` 
Note: Based on the logs, the online operation did not have an impact on the repository size.
> TarMK GC #1: cleanup completed in 1.021 s (1021 ms). Post cleanup size is 23.6 GB (23616786432 bytes) and space reclaimed 0 B (0 bytes).
3. Performed offline compaction
* shutdown the instance
* downloaded oak-run (at same version as the oak-bundles) to the sling folder
* executed the command `java -jar oak-run-1.6.1.jar compact repository/segmentstore` and observed the output...
> Before size 24.9 GB (24892420721 bytes)
> After size 1.7 GB (1708361911 bytes)
> Duration Compaction succeeded in 7.659 s (7s).
4. Restarted the instance and analyzed two different site's Recycle Bin's
* “newsite“ site had 13 items in recycle bin before and after both online and offline compaction (revisionGC). Upon restart, all 13 items were restored without error.
* “example” site had just one item in the site’s recycle bin before and after both online and offline compaction (revisionGC). Upon restart, the item was restored without errors.
5. Executed query from step 1 and determined the result count as 10,466

**Comment by GastonGonzalez** [comment]
@cmrockwell - Once again, great work and thank you for the contribution. The corresponding PR has been merged into the `develop` branch.
