### ISSUE TITLE
Errors that break the UI

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#367]
**Improper JCR permissions failures need UI notifications** 
Consider handling a scenario where the user might pace a permission error when editing a page. Currently if the user lacks write permissions, the XHR returns 500, the pages UI breaks and the user needs to refresh the browser and there is no feedback.

<img width="1070" alt="Screen Shot 2020-04-15 at 1 02 29 PM" src="https://user-images.githubusercontent.com/1811207/79366101-97729400-7f19-11ea-922d-ef975bb2229b.png">

**Publishing Errors** 
Publishing content can fail for a variety of reasons, and if it does the UI breaks, there is no feedback and the user needs to refresh the page
<img width="1216" alt="Screen Shot 2020-04-15 at 11 17 08 AM" src="https://user-images.githubusercontent.com/1811207/79366265-ddc7f300-7f19-11ea-81fe-a3739936d76a.png">

**Comment by cmrockwell** [comment]
With the proposed fix when replication fails, there will be notice at the bottom. If the user clicks OK, then UI remains intact. They can try again or any other operations.

<img width="1216" alt="Screen Shot 2020-04-15 at 11 46 41 AM" src="https://user-images.githubusercontent.com/1811207/79376363-0e168e00-7f28-11ea-9d2a-a547bf0dd738.png">

**Comment by cmrockwell** [comment]
With the proposed fix when the user has insufficient permissions to make a change (save page edit), there will be notice about the error. They can click OK, and the UI should stay intact. The user can navigate away, click cancel or other operations.

<img width="1070" alt="Screen Shot 2020-04-15 at 2 43 41 PM" src="https://user-images.githubusercontent.com/1811207/79376495-428a4a00-7f28-11ea-8913-afd2da5ac282.png">

**Comment by cmrockwell** [comment]
Please add @Felix-Puetz and any others as assignee.

**Comment by reggie7** [comment]
@cmrockwell I guess we could actually close this issue already?
I remember that we have the error notification in place in `develop-sling12`. And for all the cases where we can see it (and we could fix the underlying reason), that I am aware of - there's a separate ticket.

**Comment by ehdatheadwire** [comment]
@reggie7 and @cmrockwell -- per Reggie's question on 1/14 -- can this be closed/listed as complete? If yes, let's close it out and that'll move us further to knocking down tickets ;) .

**Comment by ehdatheadwire** [comment]
@reggie7 and @cmrockwell -- I didn't see a response in my github spam -- can this be closed or does it need to be moved for future work? Thanks much.

**Comment by reggie7** [comment]
@ehdatheadwire - it's up to @cmrockwell

**Comment by cmrockwell** [comment]
Yes. This one can be closed. Thanks all!
