### ISSUE TITLE
Reloading a page in preview-mode causes the drop-targets to render

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#370]
Same behaviour when:
1. edit a page
1. change to preview-mode
2. select a different page in the tree-view (top-left)

<img src="https://user-images.githubusercontent.com/50131232/79720663-45e35400-82e1-11ea-8fc4-e5a967b1708c.png" width="600"/>

**Comment by flx-sta** [comment]
As referenced in #357

**Comment by reusr1** [comment]
I fixed the original issue but now the drop targets are not rendered when navigating to another page in preview mode and then exiting the preview mode

**Comment by reusr1** [comment]
fixed the remaining issue
