### ISSUE TITLE
Create Page button in tree-view

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#371]
As request by @reusr1 in #357 the tree-view should give the ability to create a new page

**Comment by reusr1** [comment]
now that the tree view is on the right we should be able to add a button next to it in the toolbar to create a child page or a sibling page (or child template or sibling template)

**Comment by flx-sta** [comment]
Could you provide a small Mock-Up of what your idea is

@reusr1

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/10
