### ISSUE TITLE
Create User / Group for a Site and Set Access to the Site

### ISSUE THREAD

**Issue by schaefa** [headwirecom/peregrine-cms#372]
When a Tenant is created then a Group is created under /home/groups/tenants as '<tenant>_group'. If the user creating the site is admin then a User is crated under /home/users/tenants as '<tenant>_user' and the admin can set the password. If not done then the user will become disabled.
Permissions are set on the group and limit access to just what is needed for the site.

**Comment by ehdatheadwire** [comment]
This enhancement was created in April 2020 and marked as HIGH but looks to have been possibly worked on as part of 1.0.0 release project. 

Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/11 

If further work is needed, we can address the priority and requirements in the new ticket.
