### ISSUE TITLE
enhanced editorial experience

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#375]
define an approach for an enhanced authoring experience tailored to the contend editor

**Comment by reusr1** [comment]
this work is partially around what Eileen talks about on http://webmeadow.com/presentations/authoring-experience.html (better integration of content guidelines into a cms)

**Comment by reusr1** [comment]
the feature can also be used to better tailor the experience for the editors (like remove features from peregrine)

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/16
