### ISSUE TITLE
Creating a Site Failure Ends in a Hung Call

### ISSUE THREAD

**Issue by schaefa** [headwirecom/peregrine-cms#376]
If a site creation fails at the final form (clicking 'finish') the call will hang forever.

To reproduce do:
1. Create a user
2. Take write permission away from /content for that user
3. The site creation will fail with a 500 call (NPE on AdminResourceHandlerService on copyResource(), line 1401)
4. Call hangs

**Comment by ehdatheadwire** [comment]
Closing original issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/38
