### ISSUE TITLE
TreeView: node.hasChildren does not include resourceType filtering

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#377]
Nodes with children but no children of type `per:Page` will show up as folder/collapsible in the treeview because `node.hasChildren` is set to `true` because there is not pre-check for the `node.resourceType`

![image](https://user-images.githubusercontent.com/50131232/80122426-d219a380-858d-11ea-8057-e747161f5523.png)

![image](https://user-images.githubusercontent.com/50131232/80122391-c62de180-858d-11ea-86b3-ec7bc1a729e5.png)

**Comment by reusr1** [comment]
this issue has a minimal impact on peregrine at the moment

**Comment by ehdatheadwire** [comment]
Closing original issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/39
