### ISSUE TITLE
og:image must be an absolute path

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#380]
**Overview**

Open Graph images are not recognized by any social media providers since a relative URL is currently used by a Peregrine.

<img width="1277" alt="Screen Shot 2020-04-27 at 12 02 23 PM" src="https://user-images.githubusercontent.com/1387966/80410389-59616280-887f-11ea-94ef-2bf524b7b0d8.png">

<img width="1241" alt="Screen Shot 2020-04-27 at 12 03 10 PM" src="https://user-images.githubusercontent.com/1387966/80410411-5d8d8000-887f-11ea-9509-dbc8f5ed47b7.png">

**Example Page:** https://www.thetechprepper.com/posts/2020/04/ham-radio-go-kit.html

A potential solution is to generate an absolute URL using the first element under "Public Domain Names" on the root settings page.

<img width="1278" alt="Screen Shot 2020-04-27 at 12 08 07 PM" src="https://user-images.githubusercontent.com/1387966/80410641-c7a62500-887f-11ea-850a-66872566575c.png">

**Comment by smcgrath0** [comment]
PR https://github.com/headwirecom/peregrine-cms/pull/410
