### ISSUE TITLE
add a styling toolbar to inline edit

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#381]
related to https://github.com/headwirecom/peregrine-cms/issues/273
explore the option to add a simple styling toolbar (features like the trumbowyg toolbar)

toolbar with styles should stay at top of the contentview area

example toolbar: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

**Comment by flx-sta** [comment]
There is no toolbar visible in the example.
Neither in Chrome nor in FF

**Comment by reusr1** [comment]
if I grab the example code on the page I see this: 
![image](https://user-images.githubusercontent.com/779992/81816091-b3009880-94df-11ea-8fa7-6e4b866b8ab4.png)

**Comment by flx-sta** [comment]
@reusr1 i've added the toolbar to the submenu on the left side (moved the pagtree to the right)

Question is: should it also include the fomatting/ font / size / color / bg dropdowns?
or are just the buttons good?
Because the dropdowns are hard to fit in with the given size of the subnav
![image](https://user-images.githubusercontent.com/50131232/82866815-e9033b00-9f29-11ea-8acb-9e1f21ed07a1.png)

**Comment by reusr1** [comment]
> Question is: should it also include the fomatting/ font / size / color / bg dropdowns?
> or are just the buttons good?
> Because the dropdowns are hard to fit in with the given size of the subnav

it should - maybe if we move the screen size selector and the preview mode buttons into the toolbar as well (first items) we would have enough space. 

also, we need to hook up link (and image) correctly and make sure the toolbar reflects the current style of the selection or where the cursor is.

**Comment by flx-sta** [comment]
- [x] merge viewport & preview button into Toolbar
- [x] always visible but disabled
- [x] Image Modal equivalent to the current trumbowyg implementation
- [x] linking Modal equivalent to the current trumbowyg implementation 
- [x] only enable`viewport` and `preview` button when in preivew mode
- [x] move`viewport` and `preview` button to the left
- [x] remove trumbowyg (Make ppl use the toolbar on the right side too)

**Comment by flx-sta** [comment]
A few bugs are still present (especially with inserting image/link via. pathbrowser) but all in all the main stuff/features have been implemented

**Comment by flx-sta** [comment]
### BUG List

- [x] removing an image removes all content
- [x] right panel and actual content do not sync
- [x] clicking into pathbrowser makes the caret loose its position

**Comment by flx-sta** [comment]
@reusr1 any more bugs?
just add them to the list

**Comment by reusr1** [comment]
@Felix-Puetz it seems we are missing the add page/add folder in assets and all the other buttons from the navigation of all the explorers in your branch?

**Comment by reusr1** [comment]
- [x] background of editable area in dialog should be white
- [x] dialogs should have their own small toolbar as before for the editables
- [x] observed: when moving the cursor between inline edit and the dialog edit the toolbar sometimes does not reflect the correct state
- [x] observed: sometimes the always insert at the first character issue is back

**Comment by flx-sta** [comment]
>  observed: sometimes the always insert at the first character issue is back

this is now consistently not working and i can't figure out why.
Nothing done different from the working one...
Will be looking into it tomorrow

**Comment by flx-sta** [comment]
>  observed: sometimes the always insert at the first character issue is back

Alright I found out how to 100% reproduce it but i can't really figure out how to properly fix it.
To not waste anymore time I've implememented a quick & dirty solution with some programmatic clicking.
I've created a followup issuie for it #420

**Comment by flx-sta** [comment]
- [x] max-height for text-editor
- [x] adjust/tweak fullscreen view
- [x] dynamic link handling (dyn. title/ icon for delete/add)

**Comment by Felix-Puetz** [comment]
- [ ] change form material-icons to font-awesome
- [ ] remove lefovers in project dir from trumbowyg

**Comment by reusr1** [comment]
@Felix-Puetz the link tool should not only be a toggle between add/remove - if you have an existing link you may want to change it (alt text, possibly other options). Trumbowyg switches to a dropdown with change/remove once you are on a link - that should be the way better user experience.

**Comment by flx-sta** [comment]
- [x] change form material-icons to font-awesome
- [x] remove lefovers in project dir from trumbowyg
-- admin-base/ui.apps/src/main/content/jcr_root/etc/felibs/admin/dependencies/node_modules.txt
- [x] add editablity of links (not only remove)
- [x] adjust alignment

**Comment by flx-sta** [comment]
- [x] fix outline highlight multiple present (nested components)
- [x] fix selected component should not be highlighted to prevent double highlighting

**Comment by flx-sta** [comment]
- [x] #453

**Comment by reusr1** [comment]
code has been merged to develop - any other issues related to inline edit and the toolbar should be tracked as individual tickets
