### ISSUE TITLE
Tags component should show display value instead of the tag name

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/peregrine-cms#383]
Please describe the problem.
Currently, the tags component shows the tags on the page by their names rather than their display values, which seems contrary to the purpose of having a display value in the first place.

Describe the solution you'd like
Display the display values for the tags instead of their names.

Additional context
https://user-images.githubusercontent.com/5474176/66245413-76a3c900-e6c2-11e9-9f47-57696cbddc70.PNG
https://user-images.githubusercontent.com/5474176/66245414-786d8c80-e6c2-11e9-9764-bc95b2208325.PNG
https://user-images.githubusercontent.com/5474176/66245417-7a375000-e6c2-11e9-9628-2a6a62cf8cf9.PNG

**Comment by GastonGonzalez** [comment]
`issues/383` has been merged for both projects: peregrine-cms and themeclean-flex.  

<img width="1678" alt="Screen Shot 2020-06-02 at 11 53 00 AM" src="https://user-images.githubusercontent.com/1387966/83558974-b2e52e80-a4c8-11ea-8978-5bcc77b0f3ea.png">
