### ISSUE TITLE
backup/restore of tenants with users

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#392]
since we now have tenants and users in the issues/93 branch we also need to update the backup/restore flow to support the backup of the users/groups for a tenant. We should allow for backup with or without users/groups and restore accordingly. We also have to evaluate the impact on security for such a backup

please first provide a proposal on how we want to handle this and ask for the peregrine community to review the proposed approach

**Comment by schaefa** [comment]
I will start with clamping down the access to tenant artifacts by other tenants:
- /apps/<tenant>
- /etc/felibs/<tenant>
- /etc/packages/<tenant>
This should prevent the ability of another tenant to download a backup package from another tenant

**Comment by GastonGonzalez** [comment]
This issue has been merged into develop. We'll create separate issues to address the review comments in https://github.com/headwirecom/peregrine-cms/pull/465
