### ISSUE TITLE
og properties in the head section of the page are not updated when navigating from page to page

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#396]
### to reproduce
- create 2 pages linking to each other
- configure the og:title for each page
- go to page 1
- click on link to page 2
- inspect the html dom

og:title for page 2 should be what was set for page 2

### actual
og:title is still the value set for page 1

### how to address
the og props are missing from the PageModel and should be update in the head section of the html the same way as the title and description of the page

### note
- no inheritance for the checkboxs for og:title and og:description from he template
- should the default be use the title and description for og: instead?

**Comment by ehdatheadwire** [comment]
Closing as this doesn't appear to be a priority for 1.0 -- please feel free to reopen and prioritize if I have that incorrect. Here's the new ticket: https://github.com/peregrine-cms/enhancements/issues/40
