### ISSUE TITLE
open link from main navigation in new tab does not initialize the tenant correctly

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#397]
### steps

- go to a site in the peregrine admin interface
- right click on one of the main navigation pillars, open in new tab

### expected
able to continue working with peregrine

### actual
tenant state is not set correctly and falls back to admin 

### how to address
we should make deep links and sharing urls of peregrine generally make it so peregrine work in a fresh browser tab

- http://localhost:8080/content/admin/pages/pages.html/path:/content/example/pages
- http://localhost:8080/content/admin/pages/pages.html/path:/content/themeclean/pages

**Comment by flx-sta** [comment]
- [ ] on open new-tab the tenant is lost (e.g. select any page-> right-click -> open in new tab)
- [ ] 3 tiny links on the website-card at the bottom of the card are broken (normal & new tab)

**Comment by reusr1** [comment]
@Felix-Puetz I started a lot of refactoring around this, all in feature/tenantstate - looks better already. We need to make sure our reload states are correct and use the suffixes in the urls correctly

**Comment by flx-sta** [comment]
I've created a pull request for this branch to link it to this issue
