### ISSUE TITLE
Content updates do not work as shown in video 

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#4]
Viewing the page editing video http://www.peregrine-cms.com/videos.html
I am not seeing this behavior. The screenshot shows my edits on the Jumbotron. The changes are not reflecting on the page preview. After submitting changes, the updates are  not reflected. But reloading the page does render the updates. 

![screenshot from 2018-10-20 14-58-33](https://user-images.githubusercontent.com/1811207/47259583-29125a00-d479-11e8-8f06-e39402ef0bc9.png)

**Comment by schaefa** [comment]
Locally I do not see these issues. Can you see if there are JS errors?

**Comment by cmrockwell** [comment]
I deleted my previous instance of pcms and reinstalled the project from scratch. Installed the latest from master. There is still no preview or refresh when editing. There are no JS errors or 404's. I tried Chrome and Firefox.

**Comment by reusr1** [comment]
we are still working on a good fix for this issue as it is a side effect of the combination of node modules used in peregrine, will update this thread once we have a better handle on the issue

**Comment by cmrockwell** [comment]
Has there been any update to this? I notice PCMS dependencies use the carrot ^  in the package.json. Are there certain packages which need to be locked to a specific version?
