### ISSUE TITLE
Objects list of references

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/peregrine-cms#400]
Similar to asset references list
![image](https://user-images.githubusercontent.com/49845255/83301100-e44eb900-a1ad-11ea-8b62-a67aa6fa3b48.png)

**Comment by GastonGonzalez** [comment]
@smcgrath0 - Please add steps to reproduce this issue.

**Comment by GastonGonzalez** [comment]
Confirmed issue resolved. Merged to develop.
