### ISSUE TITLE
Renaming objects and pages only changes paths, not names

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/peregrine-cms#409]
Assets and template renames seem to work, not objects and pages
![image](https://user-images.githubusercontent.com/49845255/83671716-03709080-a58a-11ea-8be5-a2767acc33a7.png)
Steps to reproduce: 
#1 go into themeclean-flex and under the pages tab selecta a page
#2 click actions tab on explorer-preview
#3 try to rename the page, and go back to info tab; name will not be changed

Same thing happens with tags in under the objects tab, but slightly different (see image)
![image](https://user-images.githubusercontent.com/49845255/83671991-6b26db80-a58a-11ea-912c-0a26f501023d.png)

**Comment by ehdatheadwire** [comment]
This appears to be fixed. Closing ticket.
