### ISSUE TITLE
collapse the references to show only unique values with a count

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/peregrine-cms#411]
<img width="1203" alt="Screen Shot 2020-06-03 at 12 00 38 PM" src="https://user-images.githubusercontent.com/49845255/83677996-d9bb6780-a591-11ea-911b-930125761541.png">

This should work for assets/pages/templates/objects

**Comment by GastonGonzalez** [comment]
Closing this issue. It was handled in PR #408
