### ISSUE TITLE
Reference list bugs/styling for assets/objects/pages/templates

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/peregrine-cms#413]
Few issues: 
#1 Console gives error when trying to edit something that is not a page
Steps: change to the example website and create an all fields object, you can then assign an image to that newly created object. go over to the assets view and look at the references for the image you selected
<img width="1786" alt="Screen Shot 2020-06-08 at 1 24 31 PM" src="https://user-images.githubusercontent.com/49845255/84076902-677cc580-a98b-11ea-9e3a-c145d3d7ded3.png">

To DO: just remove the object and asset references for now, only have pages/templates references show up in list to prevent error.
#2 '/' that is suppose to be at front of line, not end (css issue)
#3 Scrollbar appears when not necessary on list for windows

**Comment by smcgrath0** [comment]
New design issue: 
Have count be a badge 
![image](https://user-images.githubusercontent.com/49845255/84202437-22c15f00-aa5d-11ea-9845-33ccacd95abe.png)
so it will be (subscript count)path, edit icon

**Comment by reusr1** [comment]
looks good in feature/tenantstate
