### ISSUE TITLE
Caret jump to the top (inline-editing)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#420]
How to reproduce:
1.  open a fresh page
2. focus into an inline-edit component and move the cursor to the end of it and press enter about 2 times to create new lines
3. reload the page
4. now click exactly into the same inline-edit component to be at the very end with the caret (right away!)
5. now type: cursor will jump to the top

**Comment by reusr1** [comment]
maybe a small observation on this issue: the cursor only jumps if the element with the contenteditable is fully replaced

**Comment by reusr1** [comment]
it seems if the component is first selected (click outside the editable area) and then the edit area is clicked editing works without the cursor jumping

**Comment by flx-sta** [comment]
- [x] play around with timing to verify if this the problem
- [x] verify events/methods emitted (to check for missing calls on the initial click)

**Comment by flx-sta** [comment]
### What happens

- When focussing the first time and then typing the component is completly rerendered by the vue instance on the peregrine-app itself
- this behaviour should actually be prevented by this code:
```
const vnode = this.findVnode(this.component.__vue__, event.path)
const attr = this.isRich ? 'innerHTML' : 'innerText'
if (vnode.data.domProps) {
  if (this.isRich) {
    vnode.data.domProps.innerHTML = this.target.innerHTML.replace(/(?:\r\n|\r|\n)/g, '<br>')
  } else {
    vnode.data.domProps.innerHTML = this.target.innerText
  }
}
````
- why is it not prevented (but only on the first time):
  - I dont know 😭

**Comment by flx-sta** [comment]
New idea:

Replace all `this.target = ..` (which would call the watcher) with an actual call to the `this.selectComponent` method

**Comment by flx-sta** [comment]
@reusr1 I've provided a better solution based on the previous comment:

> New idea:
> 
> Replace all `this.target = ..` (which would call the watcher) with an actual call to the `this.selectComponent` method 

#467
