### ISSUE TITLE
Endpoint for updating user profiles

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#423]
Peregrine now supports returning robust user profile data as a service with the introduction of PR #422  (issues/419) . However, the only application code that currently populates the user profile is the Default Sync Handler. A flexible and native service endpoint should be added to Peregrine to support enhanced profile management. This service should have the ability to add and update user profile properties.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/17
