### ISSUE TITLE
Add JSON-LD support

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#424]
JSON-LD is a microdata format for encoding additional information about websites/webpages. Search engines like Google use structured data, like JSON-LD, to improve the quality of search results. Google in particular uses this data to deliver enhanced search results such as rich media results.

This feature shall add initial support for JSON-LD using common Schema.org objects. Subsequent issues shall be created to build on the Scheme.org objects and fields supported.

**Comment by reusr1** [comment]
@GastonGonzalez looks like this works, right? can you close the issue once you are satisfied with this initial approach?

**Comment by GastonGonzalez** [comment]
Closing issue. The `develop` branch has a short term implementation that provides minimal JSON-LD support in the page properties. 

CC: @reggie7
