### ISSUE TITLE
inline edit "[CTRL]+[ , ] and [CTRL] + [ . ]" support

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#425]
finish implementation of ctrl-. support for inline editing

- [x] overall styling should be nicer
- [x] while editing a component ctrl-. should bring up a list of all available components
- [x] selection of a component should be possible with the keyboard
- [x] after selecting a component focus should be on the first inline editable field of the component
- [x] if the newly inserted component does not support inline editing the component should be selected
- [x] user should have option to exit the component selection dialog by mouse or by hitting the escape key
- [x] ctrl-. should also work if not inline editing (if current component is a container add the new component as the last child of the container, if current component is not a container add after the current component) 
- [x] same for `ctrl` + `.` only that it inserts above and not below

**Comment by flx-sta** [comment]
@reusr1 is only meant for `ctrl` + `.` exclusively or should these changes include the + `,` case of inserting above too?

**Comment by reusr1** [comment]
you are right, ctrl-, was meant to insert above

**Comment by flx-sta** [comment]
@reusr1 Added this as a new task

**Comment by flx-sta** [comment]
@reusr1 plrease review

**Comment by flx-sta** [comment]
- [x] can't drop components into page-start/-end
- [x] should save state of current selected component before inserting the new one to prevent the "save" ask-user-modal from appearing
- [x] trying to enter an inline-edit element on vue-example causes a "Maximum call stack size exceeded"
- [x] hide editable when preview mode is active

**Comment by flx-sta** [comment]
- [x] wrong pathbrowser view when opened from subanv rich-toolbar

**Comment by flx-sta** [comment]
- [x] #449

**Comment by reusr1** [comment]
looks great! closing the issue
