### ISSUE TITLE
inline edit: find better solution for a hrefs on page while editing

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#426]
currently we replace all a href's on a page while editing. This however should not be necessary as the pagerender/vue javascript code already has a handler for clicks on the page. We should be able to prevent that mechanism while editing a page. 

this would also make sure that the functionality works outside of a href's

**Comment by flx-sta** [comment]
I've changed this behaviour here:
https://github.com/headwirecom/peregrine-cms/commit/4f17c68c50ffc0d7364597f7121309c152ae733e#diff-6f426f46f3dd44d95cce7233554acdf8R692

**Comment by flx-sta** [comment]
New Task
* Find a solution that works in `state.js`
https://github.com/headwirecom/peregrine-cms/blob/develop/pagerenderer/vue/ui.apps/src/main/js/state.js
