### ISSUE TITLE
Inline image not saving when added with sub-navigation

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/peregrine-cms#435]
![defects-inline-image-2](https://user-images.githubusercontent.com/49845255/86972776-50ff9080-c128-11ea-8077-a15cd8e28da1.png)

**When adding an image to a text block with the top image icon, it doesn't save to the text block after refreshing. Works fine in side panel.**

<img width="1067" alt="defects-inline-image" src="https://user-images.githubusercontent.com/49845255/86973689-d9326580-c129-11ea-839c-ff025477084e.png">

**Comment by flx-sta** [comment]
@smcgrath0 I don't really get it how to reproduce this or what exactly the problem is.

FYI right now you can not mark/select an existing image and the image-icon would turn to the highlight color. That might be a considrable feature for the future

**Comment by smcgrath0** [comment]
@Felix-Puetz Sorry about that, here are the steps to reproduce.
1. drop a richtext component on a page
2. try to add a inline image with the icon indicated above
3. refresh page after saving richtext component

The problem is that you will not see the inline image anymore in the component after refresh, but this feature works perfect in the side panel.

**Comment by flx-sta** [comment]
@smcgrath0 unfortunatly I'm still not able to reproduce it on my currently active development branch.

I'am working on branch `issues/425` .
Could you try if you can reproduce it on that branch? if not I may have already fixed it

**Comment by reusr1** [comment]
@Felix-Puetz the same issue existed with links - looks like you fixed both at the same time :-)
