### ISSUE TITLE
Inline image url selector not working

### ISSUE THREAD

**Issue by smcgrath0** [headwirecom/peregrine-cms#437]
![image](https://user-images.githubusercontent.com/49845255/86974423-2bc05180-c12b-11ea-8868-e72f61410be1.png)

^^old
New inline version lost the ability to put an inline image from a third-party url.
vv new

<img width="1279" alt="Screen Shot 2020-07-08 at 2 37 41 PM" src="https://user-images.githubusercontent.com/49845255/86974669-970a2380-c12b-11ea-9169-f6dedfdf52f4.png">

**Comment by flx-sta** [comment]
fixed in commit https://github.com/headwirecom/peregrine-cms/commit/f03472b02ad7a4b66f6afcb72e3e43f1768720a3
