### ISSUE TITLE
spec the feature 'invite a collaborator'

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#447]
- a tenant should be able to invite a collaborator to the sites he created
- the invited person should be able to see and accept or reject an invitation

the above requirements are rather simple. this ticket is meant to solicit input on how we should present the UX for this type of task

looking input from anybody that would like to participate

**Comment by flx-sta** [comment]
I'd just keep it simple and easy.
Just a modal-box with an input for an E-Mail. 
The e-mail then contains an activation link which will lead to a form of creating an account or login with an existing one.
After registration/login the given account gains access to the invited tenant

### Mockup
![image](https://user-images.githubusercontent.com/50131232/87906642-5089c280-ca63-11ea-8b24-16e8a00f3cef.png)
![image](https://user-images.githubusercontent.com/50131232/87906968-f3424100-ca63-11ea-9432-1efa49e94aa3.png)

**Comment by reusr1** [comment]
I think we need a bit more than that. usually it's a good idea to also see the invites you sent and if they were accepted or not (and copy a link to email) 

the invited user may also need a console to see all invitation for the user

**Comment by GastonGonzalez** [comment]
@reusr1 - Are you thinking that this feature would include support for invitations via email? If so, we would need to find a flexible solution for adding a mail interface and suppport for a pluggable mail service implementation (e.g. local MTA, configurable SMTP, third-party service like Sendgrid, a serverless function, API, etc.).

I performed a quick search and found this OSGi bundle for Sling: https://github.com/apache/sling-org-apache-sling-commons-messaging-mail

To simplify this use case, perhaps the system can generate an invitation link that the user can copy to their clipboard and share with the intended user(s) via whatever method they choose (email, SMS, Slack, etc.)

**Comment by reusr1** [comment]
@GastonGonzalez I think an invitation link should be sufficient for now

**Comment by ehdatheadwire** [comment]
@reusr1 this might be a candidate for post 1.0.0 release unless you think it's required. I can't tell from the updates if any enhancements/fixes have been deployed to support this.

**Comment by reusr1** [comment]
@ehdatheadwire we should move this to the enhancements, @cmrockwell also has a proposal for this, I think

**Comment by reusr1** [comment]
closing and opened as a discussion in https://github.com/peregrine-cms/enhancements/discussions/59
