### ISSUE TITLE
Huge offline loading time

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#448]
When triyng to load a page offline (e.g. developing offline in a train or something else)
The loading time of an empty page is around 1min.
- That is due to some (apparently synchronous) requests taking forever to realise that they don't have a connection.
- additionally alot of CDN links are used for some css
-- ![image](https://user-images.githubusercontent.com/50131232/87514288-4d18c480-c67a-11ea-847e-0f37368dc805.png)

**Comment by ehdatheadwire** [comment]
@reusr1 and @Felix-Puetz this ticket has been labeled "fixed" but not closed. Has it actually been fixed or is there additional work to be done? Thank you!
