### ISSUE TITLE
inlineedit: toolbar stacks on smaller viewport sizes

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#455]
![image](https://user-images.githubusercontent.com/779992/87854736-cd346980-c8c8-11ea-8859-070d3aa378b6.png)

we should make sure it stays as one line and once it does not fit anymore the overflow items should be in a dropdown as the last item of the toolbar

something similar how http://dojo.telerik.com/aBAPi moves overflow items into a dropdown

**Comment by flx-sta** [comment]
@reusr1 please check out #475 to be able to close this ticket 👍

**Comment by reusr1** [comment]
@Felix-Puetz I see some odd things with this: the toolbar in the dialog rail on the right changes as well at a smaller breakpoint, the super/subscript are for whatever reason right aligned and when on the smallest allowed window size the toolbar is gone (and the nav bar above is all messed up)

**Comment by reusr1** [comment]
![image](https://user-images.githubusercontent.com/779992/88547557-c85f6c00-cfd2-11ea-9bc5-26a8f4c3f058.png)

**Comment by flx-sta** [comment]
What is the smallest allowed window size ?

**Comment by reusr1** [comment]
> What is the smallest allowed window size ?

this seems to happen with window width between 600 and 635px

**Comment by flx-sta** [comment]
merged into [feature/tenantstate](https://github.com/headwirecom/peregrine-cms/pull/468)

**Comment by reusr1** [comment]
@Felix-Puetz thank you! looks great
