### ISSUE TITLE
inlineedit: component hover border looks odd while scrolling with mousewheel

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#456]
- create a page large enough for the scroll bar to show
- hover over a component
- use mouse wheel to scroll

expected: hover border (the green one) should scroll with the component

observed: hover border stays where the component was before until end of scrolling and the mouse is slightly moved

**Comment by reusr1** [comment]
note: also noticed a similar issue when resizing the browser window. the border does not update accordingly

**Comment by flx-sta** [comment]
This issue will also address #463

**Comment by flx-sta** [comment]
- [x] When resizing the whole browser-window the selected wrap does not update
- [x] When scrolling and having no component selected the hover-outlines are not updating while scrolling (green/orange ones)
- [x] When resizing the whole browser-window the hover-wrap does not update

**Comment by flx-sta** [comment]
@reusr1 check PR #469
