### ISSUE TITLE
backend activation status tracking

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#458]
when activating a page we currently do an async call but do not have a way to track the current activations and their status

we should (general)

- have a generic way to manage a list of async processes
- return a path to the monitoring endpoint of an async process when we make a call to an async service
- provide a synchronous and asynchronous way to poll for the status of an async process
- provide a way to list all async processes and their current status
- make sure we can secure the processes by tenant

we should (activation)

- retrofit the activation call and make it work with the above general feature

**Comment by ehdatheadwire** [comment]
Not marked as a priority or required for new 1.0.0 release (although comments note that automation moved this through to the old 1.0.0 Release project). Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/41. Please feel free to reopen and prioritize for 1.0.0 if need be.
