### ISSUE TITLE
Templates created when new site is created have the same name as original template

### ISSUE THREAD

**Issue by devintuffy** [headwirecom/peregrine-cms#46]
When creating a new site from a template, a new template gets created. This template always has the same name as the original template, leading to multiple copies of templates with the same name:

<img width="1417" alt="Screen Shot 2019-03-19 at 11 00 23 AM" src="https://user-images.githubusercontent.com/46942507/55251925-d64e8280-520e-11e9-9e18-6debcdba6d57.png">

Making sure that updateTitle() is called on the new template still results in the same thing, composum shows that this is because there is both a title attribute and a jcr:title attribute:

![Screen Shot 2019-03-29 at 10 39 24 AM](https://user-images.githubusercontent.com/46942507/55252101-4826cc00-520f-11e9-8b42-fbe2473f61de.png)

**Comment by devintuffy** [comment]
This results in two "title" fields in the JSON object that describes the templates:

```
{
          "name" : "mnnn",
          "path" : "/content/templates/mnnn",
          "resourceType" : "per:Page",
          "created" : "2019-03-29T10:31:55.558-07",
          "createdBy" : "admin",
          "lastModified" : "2019-03-14T09:00:37.586-07",
          "lastModifiedBy" : "admin",
          "lastModifiedBy" : "admin",
          "Replicated" : "2019-03-14T09:01:36.030-07",
          "ReplicatedBy" : "admin",
          "ReplicationRef" : "local-file-system:///Users/devin/percms/sling/staticreplication/content/templates/themeclean.html",
          "ReplicationStatus" : "activated",
          "title" : "mnnn",
          "siteJS" : "https://code.jquery.com/jquery-3.2.1.slim.min.js",
          "brand" : "themeclean",
          "title" : "themeclean template",
          "siteRoot" : "/content/templates/mnnn",
          "pagePath" : "/content/templates/mnnn",
          "siteCSS" : "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css",
          "component" : "mnnn-components-page"
        }
```

**Comment by bkheadwire** [comment]
I couldn't reproduce this. I think that since this ticket was created, we changed templates to be organized per-site so it's no longer an issue.
