### ISSUE TITLE
Backup and restore UI enhancements

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#466]
The backend for the "backup and restore" feature has been merged into `develop`, however, there are some UI issues that should be addressed:

1. Replace browser alert box with a modal for the various backup/restore functions
2. Add whitespace/padding around backup and restore buttons on settings page
3. Fix the default state for the "Result" value on the backup and restore settings page. If this is a new site and a backup has never been performed, it should read: "No backup created yet". At the moment, it reads "Build Failed".
4. Overlay is still present after "upload site backup file" operation is completed.

**Comment by ehdatheadwire** [comment]
Closing original ticket and relocating to: https://github.com/peregrine-cms/enhancements/issues/43

This will likely be grouped into a general UX/UI enhancements queue.
