### ISSUE TITLE
better dashboard

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#470]
the current dashboard is a bit simple (just a collection of cards linking out to other areas of peregrine) and does not add much value

![image](https://user-images.githubusercontent.com/779992/88310035-10754a80-ccc4-11ea-8d04-4b4ae0a647bd.png)

**Comment by flx-sta** [comment]
#474

**Comment by Thomas-Pelster** [comment]
The current dashboard repeats all entries from the navigation without offering any further value. I would like to see it offer a mix of KPIs, direct functionality and information.

KPIs
- How many hits this page had in the last 24 hours, e.g. a column chart.
- What were the most frequently accessed pages in the last 24 hours, e.g. a list?

Direct functionalities
- the last modified pages can be called up directly.

Information
- an overview of the last changes / bug fixes.

**Comment by cmrockwell** [comment]
My ideas are categories into easy and harder stuff as described below:

Easy Stuff: Perhaps each card could have a few "chips" that indicate the number of new and/or changes items. Clicking 'explore' could expand full screen or accordion down. Perhaps revealing recently edited or created items; similar to Firefox's 'Top Sites'

Harder Stuff: Peregrine could have a prescribed way to integrate analytics data. That idea has a few parts: 1) Make an interface for adding analytics to the tenant sites 2) Add an implementation for Google Analytics 3) Make an analytics reporting API 4) Add an implementation for GA 5) build basic reports from analytics data into the dashboard.

**Comment by reusr1** [comment]
@cmrockwell on analytics: 
we added https://getanalytics.io/ to themecleanflex - that should help us being more abstract about analytics in general. I am also hoping that we can use perfume.js (as a getanalytics plugin) to collect some RUM data (basically the data from the browsers about how fast the page loads, etc)

**Comment by reusr1** [comment]
one of the ideas for the dashboard could also be to use an accordion style or a columns and user selectable set of cards. I think what's interesting here is that everybody depending on their role in an organization and depending on the use-case of the website has a different opinion on what a dashboard should provide.

**Comment by ehdatheadwire** [comment]
Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/49 where it will be grouped together with other UX/UI improvement tickets.
