### ISSUE TITLE
Small dashboard button enhancement

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#474]
![image](https://user-images.githubusercontent.com/50131232/88487275-e18cfc00-cf83-11ea-9926-a53efddd8518.jpeg)
Pages: https://fontawesome.com/icons/file-alt
Template: https://fontawesome.com/icons/file?style=regular
Objects: https://fontawesome.com/icons/cube?style=solid
Assets: https://fontawesome.com/icons/photo-video?style=solid
Recyclebin: https://fontawesome.com/icons/recycle?style=solid or https://fontawesome.com/icons/trash?style=solid or combined
Tools: https://fontawesome.com/icons/tools?style=solid or https://fontawesome.com/icons/toolbox?style=solid
Documentation: https://fontawesome.com/icons/book?style=solid

**Comment by reusr1** [comment]
we may want to consider this together with #470

**Comment by flx-sta** [comment]
Okay
