### ISSUE TITLE
performance issue on refby api call

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#477]
the refby api call ( /perapi/admin/refBy.json ) seems to use a long time once a peregrine environment has a larger number of sites in it. The issue becomes more prominent for users with a large set of allowed websites.

- [x] check if we have an appropriate index for the query
- [x] check if we should limit the call to just the current tenant

**Comment by ehdatheadwire** [comment]
Is this required for 1.0.0? I'd wager it isn't, but rather that it should be a fast follow to be addressed in either a performance or api queue. @reusr1 and @GastonGonzalez - would you agree?

**Comment by reusr1** [comment]
I'd like to have this solved - while looking at this issue I also discovered that `admin-base/core/src/main/java/com/peregrine/admin/resource/ReferenceListerService.java` is probably in the wrong place as its used by the replication - code - looks like this should be moved and in conjunction with https://github.com/headwirecom/peregrine-cms/issues/657 and https://github.com/headwirecom/peregrine-cms/issues/720 we should start restricting the reference search to a single tenant.

**Comment by golinski** [comment]
The PR should be treated as a discussion starting point.

The PR uses an SQL2 (Lucene) query to find nodes that reference the given path. For my sample content tree with ~3000 pages it makes the endpoint almost 10 times faster.

There is a change with respect to the previous solution. For now I do not try to find the name of the property that makes the reference (this needs additional work, as the query itself does not return this info). This begs the question if this is really necessary and the info will be consumed by the caller. The "Pages" view in tenant Admin does not seem to use this additional, very precise, information. It might be a good idea to have two versions of this endpoint one for overviews, the other for more precise info when it's needed.
