### ISSUE TITLE
Issues displaying Umlaute in welcome-screen

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#479]
![image](https://user-images.githubusercontent.com/50131232/89035809-d1866b00-d33b-11ea-8d2e-a243b8ae69e5.png)

IT's supposed to read "**dämmerung**"

**Comment by ehdatheadwire** [comment]
@reusr1 did the commit you submitted on 11/20 fix this issue? If so, may we close this ticket?

**Comment by flx-sta** [comment]
@ehdatheadwire 
![image](https://user-images.githubusercontent.com/50131232/111121563-18447080-856d-11eb-9eef-afd4593e8b88.png)

its still present in `develop-sling12` and I couldn't get the mentioned branch working

**Comment by ehdatheadwire** [comment]
I'd say this needs to be fixed, then, as part of a 1.0.0 release -- or at least, attempted to fix. Pretty bad user experience, IMHO.

**Comment by reusr1** [comment]
updated PR and addressed comments, should be good to go now

**Comment by flx-sta** [comment]
> updated PR and addressed comments, should be good to go now

~~which PR? can you link it please~~
found it

**Comment by reusr1** [comment]
issue resolved and merged, validated in develop-sling12
