### ISSUE TITLE
switches in forms are not obvious for new users 

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#493]
our switches in the forms (admin-base/ui.apps/src/main/content/jcr_root/apps/field/materialswitch/template.vue) are not directly abvious to new users

![image](https://user-images.githubusercontent.com/779992/90012952-2fc71e00-dc59-11ea-99bc-7ef47ff6090a.png)

we could switch to either check boxes or a yes/no version

![image](https://user-images.githubusercontent.com/779992/90013047-613fe980-dc59-11ea-8591-e9f9621ff94d.png)

if we change to checkboxes we would have to think about the title of the field if it is necessary or not and what impact that has to the look of the forms

**Comment by ehdatheadwire** [comment]
Closing original issue as not required for 1.0.0 release; relocating to: https://github.com/peregrine-cms/enhancements/issues/44
