### ISSUE TITLE
Uncaught TypeError: Cannot read property '$children' of undefined

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#496]
### Issue
When reloading a page and then tabbing through the components to any component that has a collection in the dialog the following error is thrown:
`Uncaught TypeError: Cannot read property '$children' of undefined`

### Reproduction
- tcf homepage,
- click example inc
- go down to the cards
- click title of first card
- click rich text of first card
- -- finish --

**Branches**
peregrine-cms: feature/tenantstate
themeclean-flex: develop

**Comment by flx-sta** [comment]
Follow up ticket of #485

**Comment by flx-sta** [comment]
@reusr1 should be fixed. 
fix pushed into `feature/tenantstate`
could you verify pls?

**Comment by reusr1** [comment]
@Felix-Puetz looks great, closing
