### ISSUE TITLE
editor: switch between input field and rte input field confuses editor

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#497]
https://github.com/kestrel-1/report-an-issue/issues/10

> **Reproduction**
> 
> 1. "pages" > "home" > "edit 'home'"
> 2. click "Service 1" title --> Editor shows span, bold and left aligned for card text
> 3. click "Service 1" card text --> Editor shows span, bold and left aligned --> bold and left aligned are wrong
> 4. click "Service 1" title --> Editor shows correct informations
> 
> ![Screenshot](https://user-images.githubusercontent.com/50134764/89028162-17d3ce00-d32c-11ea-9264-57597d923ac2.gif)
> 
> **Error**
> 
> * If the first click is an input field and the second click is an rte input field, the rte input field will display the properties of the previous input field.

**Comment by Felix-Puetz** [comment]
https://github.com/kestrel-1/report-an-issue/issues/12

**Comment by flx-sta** [comment]
See #506
