### ISSUE TITLE
'logged in as' username display issues

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#498]
https://github.com/kestrel-1/report-an-issue/issues/1

- [x] when using long user names the display of the user name is not nice
- [x] in the single sign on usecase it would be better to use a profile property such as the email address instead of the actual system user name  

issues/498 branch created

**Comment by reusr1** [comment]
@Felix-Puetz the code for the backend work has been completed in https://github.com/headwirecom/peregrine-cms/commit/9a8c6f98cd2c87d0d9b52ed5104ab7583964291e

**Comment by flx-sta** [comment]
rename branch to `issues/498-logged-in-as-username-display-issues`

**Comment by Felix-Puetz** [comment]
> @Felix-Puetz the code for the backend work has been completed in [9a8c6f9](https://github.com/headwirecom/peregrine-cms/commit/9a8c6f98cd2c87d0d9b52ed5104ab7583964291e)

do I understand it correct that I dont have to change anything but the email is provided for single-signin users automatically?
