### ISSUE TITLE
materialize css needs to be re-deployed manually after scss updates

### ISSUE THREAD

**Issue by devintuffy** [headwirecom/peregrine-cms#50]
Steps:
- Change one of the .scss files located in /admin-base/materialize/custom
- run "percli compile -d" from /admin-base

Result: css changes are not deployed to the app with the rest of the changes. If I go into materialize/target I can see that sass has run and the css files are built, but they are not deployed to sling.

In order for these changes to take effect, I need to go into /materialize and run "percli compile -d" in order to deploy the css.

For this ticket: make sure when deploy flag is set, materialize deploy step also happens.

**Comment by bkheadwire** [comment]
Couldn't reproduce - I went through the steps as stated and my css change showed up on the server.
