### ISSUE TITLE
cards: card image: deviating behavior in the editor

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#501]
https://github.com/kestrel-1/report-an-issue/issues/9

> * It is possible to select a card by clicking on the title or text. By trying to click on a card image, you select the entire card container.
> * A click on the title or text allows direct editing and the editor jumps to the place in the menu. A click on a card image will jump to the place of the card container and does not allow direct editing of the image.

**Comment by reusr1** [comment]
I think the big question here is what we really would want to happen. should we bring full inline editing to images as well and rethink that part or only support click an image and focus the field? What happens when we click in the padding of a card outside of an editable?

**Comment by ehdatheadwire** [comment]
@Felix-Puetz I was going to close this OG issue and relocate to here: https://github.com/peregrine-cms/enhancements/issues/19 but it looks like you might be working on it or want to work on it? Could you let me know when you get a chance? I don't want to move it if it's in progress :). Thanks!

**Comment by flx-sta** [comment]
@ehdatheadwire not working on it. Go ahead 👍

**Comment by ehdatheadwire** [comment]
Fab thanks, @Felix-Puetz. Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/19
