### ISSUE TITLE
feature request: download site backup: naming of zip archive

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#503]
https://github.com/kestrel-1/report-an-issue/issues/6

> * Currently the zip archive is called "NAME-full-package-VERSION.zip", it would be nicer to add the backup timestamp "YYYY-MM-DD-HH-MM-NAME-full-package-VERSION.zip".

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/21
