### ISSUE TITLE
backup site: layout success message

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#504]
https://github.com/kestrel-1/report-an-issue/issues/5

> * The positive feedback seems very cryptic and does not fit the rest of the layout.
>   ![Screenshot](https://user-images.githubusercontent.com/50134764/89024394-51eda180-d325-11ea-8a15-57d9cb2a2665.png)

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/22
