### ISSUE TITLE
create a website: choose name: labeling, behavior and question

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#505]
https://github.com/kestrel-1/report-an-issue/issues/4

> **Label**
> 
> * The asterisk is very far away from the actual label.
> * The "Site Titel" is marked with an asterisk, but there is also no hint that this field must be filled, when you click next Why the asterisk?
> * Little typo in the hint "site names may only contain lowercase letters, numbers, and underscores" - the last comma is not necessary
> 
> **Behavior**
> 
> * The "Site Titel" is marked with an asterisk, but you can go to the next step without. Why the asterisk?
> 
> **Question**
> 
> * The field "tenant user password" comes here unexpectedly and one does not know which purpose it has.
> 
> ![Screenshot](https://user-images.githubusercontent.com/50134764/89023952-a8a6ab80-d324-11ea-8283-863457e9f7cd.png)

**Comment by reusr1** [comment]
@Felix-Puetz I already addressed the descriptions and removed the tenant user password for non admin users. The only thing remaining would be to do something about the spacing of the asterisk

**Comment by flx-sta** [comment]
![image](https://user-images.githubusercontent.com/50131232/90246268-85a3ed80-de34-11ea-8252-a2b381fcf25e.png)
