### ISSUE TITLE
placeholder ticket to overhaul website settings screen

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#507]
we need to rethink the settings screen for a tenant. This ticket is a collection of tickets and tasks that should be looked at together

- https://github.com/headwirecom/peregrine-cms/issues/504
- https://github.com/headwirecom/peregrine-cms/issues/503
- remove the need to go to root page template to change domain names, css and js, etc
- better status reporting of backup before the first backup is created

**Comment by flx-sta** [comment]
Maybe include:

* #509 
* #510

**Comment by ehdatheadwire** [comment]
Closing original issue and relocating to enhancements queue: https://github.com/peregrine-cms/enhancements/issues/45

This will likely be grouped together with other UX/UI enhancements.
