### ISSUE TITLE
Backup info not updating when finishing a backup

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#509]
**Before reload and after "done" of create backup**
![image](https://user-images.githubusercontent.com/50131232/90227581-1cf94880-de15-11ea-8f27-c1c115b36ae2.png)

**After reload**
![image](https://user-images.githubusercontent.com/50131232/90227611-271b4700-de15-11ea-81f2-4e55b359db5b.png)

**Comment by ehdatheadwire** [comment]
Closing original issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/46

This will be part of a new UX/UI improvement queue as there are many tickets related to that subject.
