### ISSUE TITLE
"configure your website" page has wrong <title>

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#510]
![image](https://user-images.githubusercontent.com/50131232/90227941-b0327e00-de15-11ea-8ab0-44adbaff4902.png)

**Comment by ehdatheadwire** [comment]
Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/47 where it will be grouped together with other UX/UI tickets and further filtered to the website settings screen for ease of address later.
