### ISSUE TITLE
Sling 12: Everyone ACL on Root, Initial start page, and /content in URL optional

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#513]
Related to [SLING-6130](https://issues.apache.org/jira/browse/SLING-6130) Peregrine is still using jcr:read for everyone on root. This is problematic in a number of ways.  The most obvious concern is that the default inheritance of that read ACL for everyone throughout the repo. Read access of rep:password values from nodes under /home/users is obviously not ideal. Based on my analysis, Peregrine CMS does not need read on root for everyone if the following ACL's were used

| Path  | Principle  | ACL   | Rule  | Comment  |
|---|---|---|---|---|
| /perapi/admin  |  everyone | jcr:read  | allow  |  new |
| /apps  |  everyone | jcr:read  | allow  |  new |
| /i18n  | everyone  |  jcr:read |  allow |  new |
| /content  | everyone  |  jcr:read | allow  | latest Sling default  |

Peregrine works with the ACL's above and avoiding requests to root. For example this URL  http://localhost:8080/content/admin/pages/index.html will render and work properly.

**Root Mapping**
Visiting localhost:8080/ currently uses a redirect properties on the root node. For that to work, read access on root is required. There are other ways. Peregrine CMS could follow the example set by Sling (/conent/starter) to avoid setting any properties on jcr_root.  For example, the existing sling:target and sling:redirect properties should be removed from root, so it looks like this...
`{"jcr:primaryType":"rep:root","jcr:mixinTypes":["rep:AccessControllable","rep:RepoAccessControllable"]}`

then change the property `sling:target` on the /content node from "/starter.html" to "index.html"

and index.html should be moved under /content.

**Make /content optional**
The above changes should just work since Sling 12 has default mappings that make /content optional.

Peregrine should consider making "/content" optional in too! It is setup by default, which is why  Sling 12 /starter.html opens for root requests. "/starter.html" is actually the /content/starter resource.

Here is Resource Resolver console shows the root mappings that make /content optional
http://localhost:8080/system/console/jcrresolver?msg=JcrNodeResource%2C+type%3Dsling%3Aredirect%2C+superType%3Dnull%2C+path%3D%2F&test=%2F

![image](https://user-images.githubusercontent.com/1811207/90288926-d887a000-de48-11ea-93df-ac1ca9588551.png)

As a test, a visit http://localhost:8080/admin/pages/index.html currently shows a blank screen, because http://localhost:8080/perapi/admin/content.json/admin/pages/index.data.json responds 500. But a few minor changes could make the URL's more friendly.

**Comment by cmrockwell** [comment]
Here are three commits added to make these improvements

- https://github.com/cmrockwell/peregrine-cms/commit/ecea0de68d680cded859fe16868738ab56880be2
- https://github.com/cmrockwell/peregrine-cms/commit/37836c397a603fc95cd16bc9b15804f0fc821e92
- https://github.com/cmrockwell/peregrine-cms/commit/a98349bcdd89347bafe4d8aece0af6d99067e835

This resolves a need to have an ACL for everyone on root, by taking advantage of the default resolver mappings making /content in the path essentially optional. 

<img width="1682" alt="Screen Shot 2020-08-17 at 3 32 56 PM" src="https://user-images.githubusercontent.com/1811207/90437939-36aec000-e0a1-11ea-8f8a-bad0f0f2489f.png">

Note: Clicking around the UI, paths will continue to have `/content/` in the URL bar. That's a frontend change that could come later.

**Comment by reusr1** [comment]
@cmrockwell I assume this is all addressed in the sling12 branch, right? should we close this ticket?

**Comment by cmrockwell** [comment]
Yes. We can close this one.
