### ISSUE TITLE
show image-icon on images to directly enter pathrbowser

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#515]
e.g:
![image](https://user-images.githubusercontent.com/50131232/90507944-09bce480-e157-11ea-9867-e55340701747.png)

For now the only option to change it is to do it on the right-dialog.

Add an option to do this directly in the content:

![image](https://user-images.githubusercontent.com/50131232/90508397-fa8a6680-e157-11ea-9702-36dcd3cb1658.png)

**Comment by reusr1** [comment]
We should also consider additional 'inline' edit functionality for the editor such as drag and drop an image from the computer directly onto the existing image and support for upload/create folder in the image path browser

**Comment by flx-sta** [comment]
> We should also consider additional 'inline' edit functionality for the editor such as drag and drop an image from the computer directly onto the existing image and support for upload/create folder in the image path browser

Wouldn't it be better to shift these into the opened up pathbrowser?

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/30

@Felix-Puetz once we're through cleaning up/closing out the remaining bugs, we can add back in any future enhancements you want to work on.
