### ISSUE TITLE
add special-characters insert button

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#516]
Example:

![image](https://user-images.githubusercontent.com/50131232/90634410-f0d03400-e227-11ea-9890-5e7f4e64f5b7.png)
![image](https://user-images.githubusercontent.com/50131232/90634433-f9286f00-e227-11ea-9a80-3519830ac7fb.png)

(Source: https://html-online.com/editor/)

**Comment by flx-sta** [comment]
![image](https://user-images.githubusercontent.com/50131232/91537955-61a5d900-e917-11ea-8c77-c291a4be4131.png)
![image](https://user-images.githubusercontent.com/50131232/91537994-6f5b5e80-e917-11ea-8053-acb2431a2b52.png)

**Comment by reusr1** [comment]
closing as this has been merged
