### ISSUE TITLE
open live version

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#523]
add button to page explorer and page editor to open the current live version of a page (using the first domain name configured for the site)

![image](https://user-images.githubusercontent.com/50131232/91974140-a2d62880-ed1d-11ea-8969-83bae31e1be6.png)

**Comment by flx-sta** [comment]
~~@reusr1 what is the "first domain name configured"?~~

~~I can't find such a configuration on the website settings page~~
