### ISSUE TITLE
Add Copy Page support to Actions pane under Pages 

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#529]
Problem:
Currently, copying a page is only supported via Composum.

Solution:
Update the "actions" pane under "Pages" to support a copy operation. The UI flow should re-use the same experience as the "move" action.

**Comment by ehdatheadwire** [comment]
This could be very very helpful to me personally as I produce component skeleton pages while we figure out how we want those to operate. Any chance we can get this implemented sooner rather than later?

**Comment by GastonGonzalez** [comment]
> This could be very very helpful to me personally as I produce component skeleton pages while we figure out how we want those to operate. Any chance we can get this implemented sooner rather than later?

@ehdatheadwire This has been implemented and merged to the feature/tenantstate branch.

**Comment by ehdatheadwire** [comment]
I believe this ticket can be closed -- I've personally used it so I'm going to close!
