### ISSUE TITLE
code-style standard (maybe only JS code for now)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#532]
We should agree on a code-style standard.

At least for the javascript code.

**Comment by reusr1** [comment]
I agree we should agree on that (for front end code and backend code). But we really should do this in my opinion once we are fully merged into the develop-sling12 branch because right now a reformat of the codebase would make it nearly impossible to merge

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/23
