### ISSUE TITLE
Site Map Scheduled Cache Re-builder is not invalidating the cache

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#533]
**Issue:**
_Site Map Scheduled Cache Re-builder_ is not invalidating the cache for tenant sites.

**Branch:** feature/tenantstate

**Steps to Reproduce:**
1. Set the _Site Map Scheduled Cache Re-builder_ OSGi configuration to `0 45 * ? * * *`. This should run every hour at the 45 minute mark.

**Observed Results**
Cache is not invalidated and sitemap remains unchanged.

**Expected Results**
Cache is invalidated every hour and the sitemap is updated accordingly.

**Work Around:**
Manually delete `/var/sitemaps/files/site` and `/var/sitemaps/structure/site` in Composum when a sitemap update is needed.

Customer Reference: https://github.com/kestrel-1/report-an-issue/issues/20

**Comment by reggie7** [comment]
Hey, I have checked it locally on the given branch. [com.peregrine.sitemap.impl.ScheduledSiteMapStructureCacheReBuilder](http://localhost:8080/system/console/configMgr/com.peregrine.sitemap.impl.ScheduledSiteMapStructureCacheReBuilder) defines a **Scheduler Expression** and at the given time the task calls [com.peregrine.sitemap.impl.ScheduledSiteMapStructureCacheReBuilder](http://localhost:8080/system/console/configMgr/com.peregrine.sitemap.impl.ScheduledSiteMapStructureCacheReBuilder) which has a **Debounce Interval** configuration. The actual page rebuilding will occur at the time given by CRON expression plus the debounce interval (by default it's 5m, please check and confirm in your environment). I believe this should call the rebuilding process at an equivalent of `0 50 * ? * * *`. Could you check that for me?

**Comment by reggie7** [comment]
Additional issue noticed to get fixed:
1. Re-builder removes cache
2. It marks stuff to be rebuild
3. Debouncer starts counting time
4. Only when the debounce interval elapses - the cache gets back in place
The problem: in the meantime the cache dissapears.

**Comment by GastonGonzalez** [comment]
@reggie7  - I reviewed this branch in dev and the cache invalidation works now. Before I merge this, here's what I'd like to see.

1. Please create a branch off `feature/tenantstate`  so that we have a cleaner merge.
2. Fix this new issue: The cache gets removed after the rebuilder marks stuff to get re-cached and before the debounce time elapses.
3. Check the replication state when adding items to the sitemap. If the page is not replicated, it should be excluded. I am ok if this needs to be a separate ticket.

**Comment by GastonGonzalez** [comment]
This issue has been resolved with this PR: https://github.com/headwirecom/peregrine-cms/pull/541.
