### ISSUE TITLE
Document replication use cases

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#534]
The goal of this ticket is to identify all of the peregrine replication use cases. For now, let's ignore the actual replication implementation (i.e. Local FS Replication, Local Replication, Remote Replication, etc.) and focus on defining the use case on how replication should work.

1. Document use cases under the `docs/public/replication` folder.
2. Create `docs/public/replication/index.md`. This shall reference individual use case markdown files as a list.
3. Create one markdown file per use case (i.e. docs/public/replication/use-case-replicate-new-page.md)

```
# Replicate New Page

Created By: Gaston Gonzalez
Date Created:  1 September 2020
Date Updated: 1 September 2020
Actor(s): Peregrine CMS Author
Description: Author creates a new page and replicates it after initial editing. 

## Preconditions:
1. Page does not exist in system.

## Postconditions:
1. All assets referenced by the page are replicated along with the page. 

## Main Course:
1. Author creates new page
2. Author adds themeclean-flex components (heading and text)
3. Author replicates page

## Alternate Course:
1. ...

## Exceptions:
1. ...
```

Please use the above template as a reference. Please come up with a list of other use cases. Some that come to mind are:
* Replication status icon changes on replication
* Replicate updated page
* Replicate root site
* Replicate asset
* Replicate object
* Replicate template
* Replicate sitemap
* Template updated
...

**Comment by GastonGonzalez** [comment]
@reggie7 - Please add a use case that covers how the sitemap is updated upon replication. My opinion is that we should only include pages in the sitemap that have been replicated.

**Comment by reggie7** [comment]
@GastonGonzalez can we close?

**Comment by GastonGonzalez** [comment]
Closing ticket.
