### ISSUE TITLE
special characters in node creation

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#54]
we need to make sure when we create nodes (new page, new template, new object, new asset) that we handle special characters correctly. As it stands right now creating a page with a question mark in the name results in a node that can break peregrine. 

In general we should keep the display name as typed and change non alphanumeric characters to a dash and make sure we do not have a conflict when creating such a node (does a node exist already with the node name we are trying to create)

**Comment by devintuffy** [comment]
Also with this ticket I will fix handling of duplicate names. If the user re-uses  name, they get a notification that the name is already in use:

<img width="1077" alt="Screen Shot 2019-04-08 at 1 10 05 PM" src="https://user-images.githubusercontent.com/46942507/55753630-ab7ae000-59ff-11e9-94ae-40c62804df0c.png">

which is a great first step, but it doesn't block the input; the user can click through to the end of the wizard where they generate a javax.jcr.ItemExistsException and the page breaks.

As part of this ticket, will block user from proceeding forward if a name is in use. 

This will also take into account the escaping done as described above; so if a user previously created an item named "hello?123" that gets persisted as "hello-123", anything that would eventually persist the same way should also trigger the same name-already-in-use error, e.g., "hello?123", "hello%123", "hello-123"

**Comment by devintuffy** [comment]
Pull request for this: https://github.com/headwirecom/peregrine-cms/pull/61
