### ISSUE TITLE
Referenced page assets not replicating

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#545]
Assets referenced on a page are not replicated during page replication.

**Steps to Reproduce**
1. Upload a new image asset
2. Create a new page
3. Open page properties and set the og:image  to the newly uploaded image
4. Publish the page

**Actual Behavior**
Page is replicated, but associated image is not. Check replication by visiting the `sling/staticreplication` directory on the filesystem.

**Expected Behavior**
Any assets referenced by the page should be replicated when the page is replicated. 

**Notes**
1. og:image is used an example. The fix for this issue should handle any asset references (i.e. component references)
2. @cmrockwell - I checked your working [PR](https://github.com/headwirecom/peregrine-cms/pull/508) and confirmed that this issues exists on your fork as well. I'm copying you here so that we don't duplicate effort.

**Comment by cmrockwell** [comment]
What's interesting is that following these steps, I was not able to reproduce the problem on my fork when using the Web Publishing modal. The new asset referenced in the og:image property was included in the replication package. 

<img width="1515" alt="Screen Shot 2020-09-14 at 12 26 32 PM" src="https://user-images.githubusercontent.com/1811207/93112610-35fc5000-f686-11ea-93c8-a950d149f4bd.png">


But I think many issues like this will occur when using the quick publish button (and I was able to reproduce this when clicking the globe button from the nav / explorer)

**Comment by GastonGonzalez** [comment]
Interesting. I haven't tried the web publishing modal on your branch, just the quick publish global icon. I'll have to look at your branch again. At any rate, @reggie7 has a fix that I'll be reviewing later today.

**Comment by cmrockwell** [comment]
I was going to take a look and merge it into mine as well, but this branch comes from feature/tenant and not develop, so it is hard to evaluate.

**Comment by GastonGonzalez** [comment]
Confirmed fix. Fix merged into feature/tenantstate.
