### ISSUE TITLE
Unhide child pages from sitemap

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#546]
The `excludeFromSitemap` page property currently hides pages set to `true` as well as its children. We need to provide the ability for child pages to be included in the sitemap if desired.

Many sites have the concept of bucket pages that may be used for organizing content. For example:

```
/content
  /pages
    /site
      /posts
        /2020 (bucket) => hide
          /09 (bucket) => hide
            /post1 => allow
            /post2 => allow
            /postN => allow
```

We need the ability to allow child pages under a parent page to be allowed, if desired by the user, to be included in the sitemap. 

There may be a number of ways to solve this problem, so let's discuss the approach here first before starting on the implementation.

Some questions that we should ask ourselves.
1. Should we preserve the existing interface? As it stands, `excludeFromSitemap=true` excludes the current page and all children.
2. This flag is somewhat overloaded as it is also honored by a number components. I believe the pager, but there could be others. We need to think about how the components may be impacted.
3. Should we introduce a second property called `excludePage` that only excludes a single page, but allows the children to be evaluated. In this model, we can still use our current property  `excludeFromSitemap=true` to exclude itself and its children to preserve the behavior used by current Peregrine site. For sites that have bucket pages, they can opt to set `excludeFromSitemap=false` (remove it) and add `excludePage=true` to the bucket pages.

My thought is that `excludeFromSitemap=true` stops the evaluation of child nodes where as `excludePage=true` marks the page to be hidden, but still allows children pages to be evaluated.

**Comment by reggie7** [comment]
I would go with the last solution too. I can see 2 places where the [peregrine-cms](https://github.com/headwirecom/peregrine-cms) ([explorer](https://github.com/headwirecom/peregrine-cms/blob/feature/tenantstate/admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorer/template.vue#L537) + [explorer_dialog](https://github.com/headwirecom/peregrine-cms/blob/feature/tenantstate/pagerenderer/vue/ui.apps/src/main/content/jcr_root/apps/pagerendervue/structure/page/explorer_dialog.json#L119)). I don't know about other usages elsewhere. But I would save the current understanding of the property in those places (I believe we are still free to interpret it the way we want in `sitemaps`). Based on what we decide - I'd only change the other name to be more precise, either `excludeFromSitemapRecursively` / `excludeFromSitemapWithChildren` / `excludeTreeFromSitemap` or `excludeFromSitemapNonrecursively` / `excludeFromSitemapWithoutChildren` / `excludePageFromSitemap`

**Comment by reggie7** [comment]
I also see another case that we have to treat the same way I guess. Let's take an example of the structure from above. Let's say we have published `/content/pages/site/posts/2020/09/post1` only, but we have not done that for `/content/pages/site/posts/2020/09`. The current replication mechanism will neither replicate ancestor pages to `staticreplication` nor mark them with `per:Replicated` in the repo. Thus `/content/pages/site/posts/2020/09` will be recognised as non-published and consequently `/content/pages/site/posts/2020/09/post1` and its siblings and subsequently - all descendants will not be grabbed into the sitemap cache. We would need to decide on a coherent interpretation of the situation when the ancestor page does not go into the sitemap - what do we do with the descendants?

**Comment by reggie7** [comment]
Additional issue: we should not hide pages that are excluded from sitemap to be revealed only as secondary items.

**Comment by ehdatheadwire** [comment]
@reggie7 are you still waiting on a PR review? Looks like this was moved to that state about a week ago but has yet to be reviewed.

**Comment by reusr1** [comment]
@ehdatheadwire we just need a second approval on this one to merge. It is a front testable issue

**Comment by ehdatheadwire** [comment]
> @ehdatheadwire we just need a second approval on this one to merge. It is a front testable issue

I can test it then, I suppose. I'll assign to myself and check the PR#781.
