### ISSUE TITLE
when creating a website as a non admin user we do not check if the website name is available

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#549]
the current check at https://github.com/headwirecom/peregrine-cms/blob/d9123cdd93d5f317ac70e473127925443c8a8c21/admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/createtenantwizard/template.vue#L199-L213 should call the backend to see if the name is available, we probably should dedupe the call to avoid a lot of requests while typing

**Comment by reusr1** [comment]
@GastonGonzalez we really need to address this one due to kestrel1

**Comment by GastonGonzalez** [comment]
Thanks, @reusr1. I'll take this.

**Comment by reusr1** [comment]
@reggie7 @KWoloszczuk  could you please check if this made it to sling-develop12 and can be closed? thank you

**Comment by reggie7** [comment]
Yes, fixed in #690 and merged. Confirmed now to be sure.
