### ISSUE TITLE
Site Setup Replication needs better UI/UX

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#556]
When an author presses **site setup replication** there is not enough visual indication of what's actually going on. The process might take a while and the only thing that happens is that the page gets a bit gray. It's not even disabled from interaction. When I come back to it after e.g. switching tabs I have no idea whether the process succeeded or failed. I don't even know whether it has finished.

**Branch**: [develop-sling12](https://github.com/headwirecom/peregrine-cms/pull/508)

## Steps to Reproduce
1. Grab a new peregrine instance with e.g. themeclean-flex theme installed.
1. Create new website _A_.
1. Invoke **Site Setup Replication**.

**Expected Result**: The page buttons are not interactive. There is a clear indication of what is currently happening.
**Actual Result**: The page is grayed. The buttons are active.

## Analysis
Maybe we should see a list of resources being currently processed. Maybe a kind of console updating in real time. Or maybe simply a spinner or progress bar? And the result has to be shown for the user after they switch context.

**Comment by reggie7** [comment]
It's in progress: ![progress](https://user-images.githubusercontent.com/5563546/93452727-0f822300-f8d9-11ea-8055-961542eecc43.png)
It's gray, but one could easily think it's the default look'n'feel. And we have no idea what is going on.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/24
