### ISSUE TITLE
Site replication does not delete removed resources

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#557]
When an author performs **site setup replication**, the process does not handle removed resources.

**Branch**: [develop-sling12](https://github.com/headwirecom/peregrine-cms/pull/508)

## Steps to Reproduce
1. Grab a new peregrine instance with e.g. themeclean-flex theme installed.
1. Create new website _A_.
1. Invoke **Site Setup Replication**.
1. Remove some pages from your website.
1. Invoke **Site Setup Replication**.
1. Check `staticreplication` directory.

**Expected Result**: The removed pages are not cached.
**Actual Result**: The pages removed in Peregrine were not removed from the replication cache.

**Comment by reggie7** [comment]
Works for pages, does not work for assets, but it might actually come from #658

**Comment by ehdatheadwire** [comment]
@reggie7 you've moved this from in progress to todo -- is this required for 1.0.0 release and, if so, is there work to be done?

**Comment by reusr1** [comment]
@ehdatheadwire this ticket should be moved and added to the discussion at https://github.com/peregrine-cms/enhancements/discussions/58

it seems the problem is that we should also unpublish when deleting a page and not with the site replication as indicated here .

**Comment by ehdatheadwire** [comment]
Moved to: https://github.com/peregrine-cms/enhancements/issues/61
