### ISSUE TITLE
'Unpublish' does not work for page / object / template

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#559]
When an author tries to unpublish a page / object / template, the process does not succeed.  
There is also no visual indication of the process in progress.

**Branch**: [develop-sling12](https://github.com/headwirecom/peregrine-cms/pull/508)

## Steps to Reproduce
1. Grab a new peregrine instance with e.g. themeclean-flex theme installed.
1. Create new website _A_.
1. Create a page / object / template.
1. Replicate it.
1. Unpublish it.
1. Check `staticreplication` directory.

**Expected Result**: There is some progress information.  The unpublished resources are not cached anymore.
**Actual Result**: We don't know that the process is running. The resources were not removed from the replication cache.

**Comment by reggie7** [comment]
![unpublish](https://user-images.githubusercontent.com/5563546/93476955-b0cda100-f8fa-11ea-87cd-5181ca2b555e.png)

**Comment by cmrockwell** [comment]
Thank you @reggie7 for reviewing this work. It's a big help because most of my focus is on the remote replication use-case. I will review your procedure and report back.

**Comment by GastonGonzalez** [comment]
Thanks for looking into this, @cmrockwell. Let us know if you need help with it or want us to take it.

**Comment by cmrockwell** [comment]
So, I'd like to take this opportunity to add more Sling Junit tests. It would be useful IMO to have this kind of coverage for each replication use-case. I've found these tests indispensable for redeploying instances using the remote replication. Having test suites for each replication use-case should allow refactoring with more assurances.

**Comment by cmrockwell** [comment]
I have a branch for this....
https://github.com/headwirecom/peregrine-cms/tree/issues/559-deactivate-not-working-for-localFS

The tests are passing
![image](https://user-images.githubusercontent.com/1811207/93651553-e0a2a480-f9df-11ea-9921-378bf0dd3be8.png)

Deactivate seems to work
![image](https://user-images.githubusercontent.com/1811207/93651590-0334bd80-f9e0-11ea-81b5-72b74bc72c14.png)

Still need to test it a bit more before opening a PR

**Comment by GastonGonzalez** [comment]
Merge complete for this PR: https://github.com/headwirecom/peregrine-cms/pull/575. It resolved the issues described.
