### ISSUE TITLE
Removing a referenced template breaks its pages

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#560]
When an author removes a referenced Template - its pages get locked for editing.

## Steps to Reproduce
1. Grab a new peregrine instance with e.g. themeclean-flex theme installed.
1. Create new website _A_.
1. Create a template _T_.
1. Create a page P out of _T_.
1. Remove _T_.
1. Open _P_.

**Expected Result**: _P_ is editable or _T_ cannot be removed.
**Actual Result**: _P_ is locked _T_ is gone.

**Comment by reggie7** [comment]
![template-gone](https://user-images.githubusercontent.com/5563546/93479600-cb087e80-f8fc-11ea-97ad-f2251d1c36d0.png)

**Comment by ehdatheadwire** [comment]
Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/48

This is possibly only relevant for developers or non-author-only people. So it should be fixed, but it may not impact the immediate end user.

**Comment by reggie7** [comment]
Hmm, I would say it might actually impact authors as well. The steps are all what an author could do. They'd usually not fiddle so much around templates though, so it's not high impact, but a possibility for inconsistency remains. I'd leave it up to @reusr1 to evaluate the priority here.

**Comment by reusr1** [comment]
while it is relevant for authors as well we need to come up with an overall strategy on the UX for publish/unpublish/delete - https://github.com/peregrine-cms/enhancements/discussions/58
