### ISSUE TITLE
block input on slow operations

### ISSUE THREAD

**Issue by devintuffy** [headwirecom/peregrine-cms#57]
When I click on the 'edit' button for a page, there is sometimes a brief (~1 second) pause before the edit screen appears; during this time I am still able to interact with the page. For such operations, we should react to the click immediately with some sort of loading layer or similar to 1) prevent the user from performing any further actions until the action completes and 2) indicate to the user that the app got the request

**Comment by reusr1** [comment]
this issue should be tackled in the actionrewrite branch

**Comment by reusr1** [comment]
support for blocking input on long running stateActions is now in the feature/actionrewrite branch

**Comment by flx-sta** [comment]
feature/actionrewrite has been merged 👍
