### ISSUE TITLE
Prevent delete operation if published

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#577]
The goal of this ticket is to ensure that Peregrine does not allow users to delete a resource if it's in a published state. This should be enforced in the admin UI as well as the API. This change should help mitigate state issues related to replication.

**Use Case**
TODO: @reggie7 - please consider the impact and changes needed for delete|move|copy|rename|...

**Comment by reggie7** [comment]
Looking at how the structures will be affected - _move_/_rename_ will be painful to implement :( Both of these operations should probably not be blocked for the author by the replication status. Tha's my gut feeling.
_Copy_ only requires us to skip the replication properties.

**Comment by reusr1** [comment]
@reggie7 @GastonGonzalez @cmrockwell it feels to me like pages probably should not be deletable/movable once published until they unpublished again?

**Comment by GastonGonzalez** [comment]
> @reggie7 @GastonGonzalez @cmrockwell it feels to me like pages probably should not be deletable/movable once published until they unpublished again?

@cmrockwell I agree. Anything that puts the published cache or publish/live server in a stale/invalid state should be prevented. We'd like to handle the move/rename in a separate ticket as a fast follower.

**Comment by GastonGonzalez** [comment]
This issue has been resolved. A new issue will be logged to provide similar support for move and copy operations.
