### ISSUE TITLE
Removing component from page does not mark it as updated for replication

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#578]
Just as the title suggests, deletion of a component within a pge does not trigger replication status icon update
# Steps to reproduce
1. Create a new page,
1. Add an image to the page,
1. Publish all the changes,
1. Remove the image.

**Expected result**: the world icon button indicates that the page got updated and needs re-publishing.
**Actual result**: the world icon button indicates that the page is still published and not updated.

**Comment by GastonGonzalez** [comment]
Good catch, @reggie7.

**Comment by reggie7** [comment]
@reusr1 - reproducible in [`develop`](https://github.com/headwirecom/peregrine-cms/tree/develop) + [`develop`](https://github.com/headwirecom/themeclean-flex/tree/develop).
