### ISSUE TITLE
sling11 deployment, peregrine logo on login screen missing

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#58]
when using https://github.com/headwirecom/peregrine-cms/tree/upgrade-to-sling-11 the logo on the login screen is missing (seems to be protected where in sling9 this was unprotected), 

on a running peregrine instance when logged out, go to: http://localhost:8080/system/sling/form/login
notice the logo missing, reference to image is http://localhost:8080/etc/felibs/admin/images/peregrine-logo.png

**Comment by schaefa** [comment]
Is fixed on branch develop-sling11
