### ISSUE TITLE
use title instead of name in admin UI

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#581]
A couple of areas in the admin UI default to the node name for display instead of the title (such as the display of the current tenant or the page navigation while editing a page. Please go through the UI and make sure we always display the title if available instead of the node name (node name should be fallback).

**Comment by flx-sta** [comment]
@reusr1 went through the pages to fix that

see #583

**Comment by GastonGonzalez** [comment]
Local testing looks good. Confirmed friendly title on tenant page and on dropdown while editing page.
