### ISSUE TITLE
"loadToolsNodesPath" causes title of parent to change

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#582]
### Initial state
![image](https://user-images.githubusercontent.com/50131232/95198621-cccab100-07db-11eb-9dd5-800026efe856.png)

###expanded state
![image](https://user-images.githubusercontent.com/50131232/95198640-d6541900-07db-11eb-8231-6d374e572ad7.png)

**Comment by flx-sta** [comment]
I've added a watch to `item.title`
```javascript
watch: {
  'item.title'(newVal, oldVal) {
     console.log('item.title:', newVal, oldVal)
   },
   //...
}
```
getting this output:
![image](https://user-images.githubusercontent.com/50131232/95198821-2206c280-07dc-11eb-8f31-e1c77152c720.png)

**Comment by ehdatheadwire** [comment]
Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/51
