### ISSUE TITLE
sling11 - after login does not take you to the peregrine welcome screen

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#59]
on a peregrine instance built with https://github.com/headwirecom/peregrine-cms/tree/upgrade-to-sling-11 after logging in through http://localhost:8080/ you are taken to the sling default homepage instead of the peregrine index.html file. This is due to the move of the starter content.

**Comment by schaefa** [comment]
Is fixed on branch develop-sling11
