### ISSUE TITLE
breaking rendering of pages through dropping component on page

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#591]
steps to reproduce: 

- create a site with themecleanflex
- create a page based on the article skeleton page
- drop a rich text component onto the 'related content' tile

result: page rendering is broken

**Comment by reusr1** [comment]
@Felix-Puetz not sure why we even allow dropping of a component onto that title - the component itself does not allow children - the only place we really should be allowed to drop a component is in the container (and the component should be added after the components from the template)

**Comment by flx-sta** [comment]
@reusr1 
I've tested a bunch of stuff out and checked out what unwanted behaviours my change would cause but it seems like this case was never fully relevant till now.
Here is what i changed:
![image](https://user-images.githubusercontent.com/50131232/95750024-d43b0000-0c9c-11eb-8278-17a83020a20a.png)


with that components given from the template and not beeing a droptarget can no more the droped above/below
