### ISSUE TITLE
Migrate Sling12 Feature Model Launcher to Kickstarter

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#605]
The `develop-sling12` branch is currently using the Feature Model Launcher to start Sling12. The goal of this ticket is to move to the [Kickstarter](https://github.com/apache/sling-org-apache-sling-kickstart).

**Comment by GastonGonzalez** [comment]
@schaefa - What is needed to move this forward?

**Comment by ehdatheadwire** [comment]
@GastonGonzalez and @schaefa -- what state is this ticket in and is it required for 1.0.0 release? If not required, let's close it and move it to the enhancements queue. Thanks!

**Comment by reusr1** [comment]
@ehdatheadwire @GastonGonzalez @schaefa closing this ticket for now since the docker setup uses the launcher for now - we can revisit this at a later point
