### ISSUE TITLE
Version does not refresh on replication

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#607]
# Steps to Reproduce
1. Create a new site,
1. Open Pages,
1. Select a Page,
1. Open **page-versions** tab on the right,
1. Replicate the page with the _world_ button,
1. Dismiss the _Success_ dialog.

**Expected Result**: The right panel gets refreshed and a new version is shown.
**Actual Result**: There's no new version until we refresh the view ourselves.

![versions](https://user-images.githubusercontent.com/5563546/96084507-7d614080-0ebf-11eb-8116-1b8aff1d37c9.png)

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/26
