### ISSUE TITLE
Site Setup Replication does not create versions

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#608]
# Steps to Reproduce
1. Create a new site,
1. Perform **Site Setup Replication**,
1. Check versions tab of any page.

**Expected Result**: The page has a new version with **Published** label.
**Actual Result**: There's no new version.

![action](https://user-images.githubusercontent.com/5563546/96083774-2c048180-0ebe-11eb-891c-6b9ffb6ad657.png)

![result](https://user-images.githubusercontent.com/5563546/96083787-2f980880-0ebe-11eb-902f-229178f7c332.png)

**Comment by GastonGonzalez** [comment]
@reggie7 - Please address this as part of https://github.com/headwirecom/peregrine-cms/pull/610.

**Comment by GastonGonzalez** [comment]
@reggie7 - We should also consider how we create version labels when the "Site Setup Replication" is used. Since the Site Setup Replication can be invoked at any time in the tenant site's life cycle (e.g. existing site vs newly created site), I think we should only create a version label if a given resource does not have one.

**Comment by reusr1** [comment]
@GastonGonzalez you probably mean to only create a new version if the page has been changed since the last replication or has never been replicated, right?

**Comment by reggie7** [comment]
I'd suggest to keep the logic similar, if not the same, to what happens after we click replicate in the Pages UI: page gets published, new version gets created and it is assigned _Published_ label. After all isn't _Site Setup Replication_ more or less just a batch publish/activate/replicate action?
But since we do such batch here - maybe additionally we could indeed add a unique label, consisting e.g. of the current timestamp, so that we can even roll back to this consistent site state somewhere in the future?

**Comment by GastonGonzalez** [comment]
> @GastonGonzalez you probably mean to only create a new version if the page has been changed since the last replication or has never been replicated, right?

Yes. Thanks for clarifying. @reusr1

**Comment by GastonGonzalez** [comment]
> I'd suggest to keep the logic similar, if not the same, to what happens after we click replicate in the Pages UI: page gets published, new version gets created and it is assigned _Published_ label. After all isn't _Site Setup Replication_ more or less just a batch publish/activate/replicate action?
> But since we do such batch here - maybe additionally we could indeed add a unique label, consisting e.g. of the current timestamp, so that we can even roll back to this consistent site state somewhere in the future?

@reggie7 , Great suggestion. Let's use the same behavior as used when you manually publish a resource. I think adding a unique label with a simple timestamp would be good if it does not complicate the implementation too much.

**Comment by reggie7** [comment]
Fixed in #648.
