### ISSUE TITLE
Replication icon does not refresh after page edit

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#609]
# Steps to Reproduce
1. Create a new page,
1. Publish the page,
1. Select the page in Pages console,
1. Edit the page in the right panel,
1. Save changes.

**Expected Result**: The replication status icon updates to modified.
**Actual Result**: The icon does not refresh.

![props](https://user-images.githubusercontent.com/5563546/96097032-c66dc080-0ed0-11eb-986c-c234cc31e3a7.png)

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/27
