### ISSUE TITLE
Unable to delete tenant

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#611]
**Branch:** develop-sling12

**Steps to Reproduce**

_Preconditions:_
1. One or more tenant sites already exist.

_Steps:_
1. Open a clean browser session.
2. Log into Peregrine as admin.
3. Click the delete icon.

Observed Behavior:
1. Site is not deleted.
2. The following JavaScript error is thrown:
```
admin.js:45228 Uncaught (in promise) TypeError: Cannot set property 'page' of undefined
    at deleteTenant (admin.js:45228)
    at admin.js:48539
```

_Expected Behavior:_
1.. User is prompted to confirm tenant deletion.
2. If accepted, tenant is removed.

_Work Around_
1. Click on the tenant.
2. From the tenant admin screen, select _Change Website_
3. Delete site.

**Comment by flx-sta** [comment]
This bug has been annoying me while trying to write some tests for drag & drop so I've provided (as usual) a fix for develop and develop-sling12
