### ISSUE TITLE
"Create new ... version" could allow a label input

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#612]
Maybe we could allow the user to input version labels?

![versions](https://user-images.githubusercontent.com/5563546/96227672-b9b2a080-0f94-11eb-990d-241e07e9b545.png)

**Comment by reusr1** [comment]
@reggie7 is there a specific purpose for that? and since we're using version labels now for other purposes (such as marking a replication) could that not lead to trouble?

**Comment by reggie7** [comment]
@reusr1 it's a proposal from my side to enhance the functionality of versions, something to discuss (did not necessarily have to be a ticket, but such form allows to better contain stuff on a single topic).
Anyway, since we already allow the authors to see labels and they can create versions, I thought - why not allow them to label new versionsas they wish. Maybe we could actually allow a name instead of the version, if that's technically possible.

**Comment by reusr1** [comment]
@reggie7 nothing against the idea - I am more wondering what the use case for it would be (other than its nice to be able to set labels when versioning) and how we would deal with the `published` label so we dont have accidentally somebody label  a version `published` and create issues due to that.

**Comment by reusr1** [comment]
@reggie7 @cmrockwell @GastonGonzalez one good point this brings up: should we somehow namespace our 'published' label to begin with so we do not run into an issue with this in the future in case we do want to add the ability to label versions through the UI?

**Comment by GastonGonzalez** [comment]
@reggie7 - Thanks for proposing the idea. Here are my thoughts:
1. We should absolutely consider using a namespace for encoding version labels created on publish events. As @reusr1 mentioned, this will give us flexibility in the future. If we take up this work, I would handle this as a separate PR.
2. I have concerns around user-defined labels. This has UI, validation and consistency implications. I would hold off on this. Implementing #1 would allow us to move in this direction.

**Comment by reusr1** [comment]
@reggie7 I think this issue needs a discussion and a final decision on how we all would like to handle this use case

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/28
