### ISSUE TITLE
Links in Text Editor 

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#613]
There are a couple of edge cases that produce weird results in the Text Editor

### Scenario 1
Given I am editing a site based on Theme Clean Flex
And I add a Rich Text component to a newly created blank page 
Given I enter text 'paragraph' and do not save the component

Given I highlight the text and click either link button
After I select a page creating the link
Then the selected text is linked to the selected page 

_Actual result is shown. There is a JS error._
<img width="1666" alt="Screen Shot 2020-10-16 at 9 45 23 AM" src="https://user-images.githubusercontent.com/1811207/96266386-97b91e00-0f94-11eb-9fd9-965733ea0b22.png">

### Scenario 2
Given I enter some text and apply formatting including headers and lists
And I save the component
<img width="1214" alt="Screen Shot 2020-10-16 at 9 29 47 AM" src="https://user-images.githubusercontent.com/1811207/96266636-de0e7d00-0f94-11eb-8dbd-c7a97407e869.png">

Given I select the first line which is a an h2
And I attempt to link the h2 
Then the selected h2 should be linked to the selected page

_Actual result is shown. The selected h2 is removed._
<img width="1521" alt="Screen Shot 2020-10-16 at 9 30 08 AM" src="https://user-images.githubusercontent.com/1811207/96266847-22018200-0f95-11eb-9694-fda747b17e9c.png">

### Scenario 2B
Same setup as Scenario 2
Given I select the first list item (li) and attempt to link it
Then I expect the markup to have a structure li -> a -> 'li Link 1'
_Actual result is shown. The li format removed._
<img width="1299" alt="Screen Shot 2020-10-16 at 9 32 06 AM" src="https://user-images.githubusercontent.com/1811207/96267267-99371600-0f95-11eb-930d-536ae730f049.png">

**Comment by flx-sta** [comment]
@cmrockwell I assume it's back?
