### ISSUE TITLE
Copy operations fail on versioned resources

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#615]
Copy operations fail if a version label exists for a resource. This issue manifests itself in multiple areas, but the root cause exists in the core resource copy methods in Peregrine. Here are three use cases that fail:

1. Page copy (develop-sling12)
1. Skeleton copy (issues/603-update-sitemap-to-support-replicated-version)
1. Site replication (issues/603-update-sitemap-to-support-replicated-version)

Any other use case where the internal Peregrine copy code is invoked.
 
# Steps to Reproduce (page copy)
1. Switch to the `develop-sling12` branch 
1. Create a site.
1. Create a version for any page.
1. Copy the page.

**Expected Result**: success
**Expected Behavior**: exception

The next set of use cases manifest this problem more  quickly as they are tied to replication. The `issues/603-update-sitemap-to-support-replicated-version` branch is now creating version labels by design and exposes the issue much quicker since version labels are heavily used.

# Steps to Reproduce (skeleton page copy use case)
1. Switch to the `issues/603-update-sitemap-to-support-replicated-version` branch
1. Create a tenant,
1. Create a page from a skeleton page.

![skeleton](https://user-images.githubusercontent.com/5563546/96505692-c9f9a280-1256-11eb-9c4d-0f4801973f0f.png)

![finish](https://user-images.githubusercontent.com/5563546/96505697-cbc36600-1256-11eb-9091-a7379b215634.png)

**Expected Result**: success.
**Actual Result**: Exception

![exception](https://user-images.githubusercontent.com/5563546/96505703-ce25c000-1256-11eb-8e98-e98462144bb3.png)

# Steps to Reproduce (site replication copy use case)
1. Switch to the `issues/603-update-sitemap-to-support-replicated-version` branch.
1. Publish themeclean-flex
1. Create a site (s1)
1. Publish  s1

**Comment by reusr1** [comment]
@reggie7 are you trying to create a page in the skeleton page area or outside of the skeleton page area?

**Comment by reggie7** [comment]
Initially I tried outside, but I've just confirmed the same issue inside `skeleton-pages` folder. Is that what you meant by the _area_ @reusr1?

**Comment by GastonGonzalez** [comment]
@reggie7 - Please fix this issue first. Create a new branch off `develop-sling12`. Once the core copy issue is resolved we can revisit [PR 610](https://github.com/headwirecom/peregrine-cms/pull/610).

**Comment by GastonGonzalez** [comment]
Resolved by this [PR](https://github.com/headwirecom/peregrine-cms/pull/616).
