### ISSUE TITLE
Filter secondary items toggle and exclude from site map

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#617]
The *exclude from sitemap* page property and *filter secondary items* should not be bound together. Exclude from sitemap should only be used to prevent a page from appearing in the sitemap. Instead, *filter secondary items* uses this field to hide pages from page navigation.

**Use Case**
1. Create a skeleton page (i.e Blog with Recommendations)
2. Set the *exclude from sitemap* property to `true` to prevent it from appearing in the sitemap.
3. Create a page (p1) based on the skeleton page.

*Observed Behavior*
User is unable to see their page while navigating Pages.

*Expected Behavior*
User can see their new page.

*Work Around*
1. Toggle the *secondary items filter*
2. Your page (p1) should be visible.
3. Set *exclude from sitemap* = `false`

This issue is not critical, but IMHO, breaks the flow in the creative editing process.

**Comment by reusr1** [comment]
@GastonGonzalez makes sense to decouple the two use cases - unfortunately we do not have a overall way right now to filter out the supporting files in the folder as well as the supporting directories like **errors, css** and **js** - the solution therefore has to include a fix for these folders as well

**Comment by GastonGonzalez** [comment]
Sounds fair, @reusr1. Thanks for the speedy response. This one can wait, but thought I would raise it while creating content this morning as it took me out of the creative writing process. Do we have a design ticket for handling supporting files?

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/29
