### ISSUE TITLE
Theme HTL

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#623]
**Please describe the problem.**
Currently the only way to use HTL in Peregrine is to deploy `pagerenderserver` module. While this can be extended, it is currently quite limited. New HTL sites cannot be created through the UI

**Describe the solution you'd like**
Create a simple theme called 'Theme HTL' 

Page components
- working RTE component
- image component

Template components
- drop down nav
- footer [where it belongs](https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/)

Documents

1. how to create new htl components 
1. how to compile styling  as .less 
1. how to concat and deliver theme js 

**Additional context**
The intent for this ticket is to create structure and begin a theme project based on htl

**Comment by reusr1** [comment]
@cmrockwell would be great to start this in https://github.com/peregrine-cms - maybe we can reuse the fragments from themeclen-flex [1] and update the hatch process at the same time. If we use that approach any site can switch from server to clientside rendering and it would be a great showcase to hatch to vue or htl. 

[1] https://github.com/headwirecom/themeclean-flex/tree/develop/fragments

**Comment by cmrockwell** [comment]
Sure, the HTL theme could definitely live under the per-cms repo. Tooling for creating new components that allows both styles is an interesting idea, and probably deserves a separate ticket. In the scope of this ticket, I hope to model a few patterns that could inform both updates to the percli processes, and manual processes developers can use to create new components.
