### ISSUE TITLE
Select (checkbox) to move/delete multiple elements at once in explorer

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#626]
RIght now if you want to delete, lets say 10, pages you'll have to delete every single one separately.
Not a good user experience.

We should add a like a button to activate the `select-mode` which will show checkboxes in front of (selectable) elements in the explorer  and change the "explorer-preview" on the right side to be only select-actions (move/delete)

### 1 . Approach (Client-Sided)
Just send multiple requests in an interval and block the user-interface with a loading animation while he waits.
Show the user a progress-bar of how many requests are done/left

### 2. Approach (Server-Sided)
Extend the edit node to be able to handle bulk deletes as array

**Comment by flx-sta** [comment]
@reusr1 @reggie7 @GastonGonzalez is bulk delte server-sided already supported?

**Comment by reggie7** [comment]
@Felix-Puetz usually we should be able to check the available BE endpoints at [/perapi/swaggereditor/index.html](http://localhost:8080/perapi/swaggereditor/index.html), remembering to double check though, in case some docs are missing or out-of-date. But yeah, I checked the code and only single-element operations are supported at the time.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/31
