### ISSUE TITLE
port is not checked before starting up the server

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#627]
If there is another application running on port `:8080` and you start sling/peregrine there is no check whether the port is actually available.

**Comment by reusr1** [comment]
@Felix-Puetz how do you start sling/peregrine?

**Comment by flx-sta** [comment]
```bash
cd /resources
java -jar com.[...]
```

**Comment by reusr1** [comment]
in that case this is a sling issue and not a peregrine issue - the official way to start sling is through percli and that version tracks the port (but is not fully ready yet for the sling12 version of peregrine)

**Comment by reusr1** [comment]
@Felix-Puetz since this is a sling issue and not a peregrine issue, should we close this ticket? The main entry point to starting/stopping peregrine is percli - percli checks if the port is available before launching

**Comment by flx-sta** [comment]
Sure
