### ISSUE TITLE
Updating the peregrine-builder to the sling-feature model

### ISSUE THREAD

**Issue by DimitriPlotnikov** [headwirecom/peregrine-cms#63]
Since the old sling provisioning doesn't support content packages, perigrine content was installed manually on top of sling. The feature-model that was released this April does support provisioning of content packages (zips) and would enable to build a "self-contained" single jar peregrine distribution without any supplementary steps. 

There is a preliminary work on adoption the sling features and it would be a great benefit if the work started in https://github.com/headwirecom/peregrine-cms/tree/feature/sling-feature-builds/sling-feature would be accomplished.

**Comment by DimitriPlotnikov** [comment]
The work seems to be done in: https://github.com/headwirecom/peregrine-cms/tree/develop-sling11

**Comment by schaefa** [comment]
The Sling Feature Model is currently developing. That said the develop-sling11 has a version available even though it is not built on the latest.

**Comment by reusr1** [comment]
this ticket is not necessary anymore now that we have develop-sling12 and a feature model for peregrine
