### ISSUE TITLE
Refactor Site Settings

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#636]
**Current Condition.**
Site settings are accessed by clicking the upper-left icon then Settings.

It reveals this page
<img width="1186" alt="Screen Shot 2020-10-26 at 2 57 04 PM" src="https://user-images.githubusercontent.com/1811207/97216264-f43de980-179b-11eb-9307-7f6f51ba38a2.png">

Configuring the site domain, css, js and pre-fetch domains requires configuring the Website Root Template. 
Clicking that button reveals
<img width="1341" alt="Screen Shot 2020-10-26 at 2 57 28 PM" src="https://user-images.githubusercontent.com/1811207/97216455-454ddd80-179c-11eb-8661-4da3c5233f37.png">

Configuring these properties is confusing, buggy and hard to extend.

- The user may be confused as they must click an empty container on an empty page to access the properties shown. 
- There are bugs. such as when you want to remove items from the list by clicking the trash icon. The item list does not show the item as removed until the dialog is saved and the page is refreshed.
- There is no way to republish just the site settings

**Describe the solution you'd like**
It would be a better design to avoid the page editor for site settings, and to avoid using the base template. There is nodetype `per:Site` It would be much nicer to put site settings at this node. Placing settings here ensures all site resources can inherit any properties, because this node is ancestor of every page, template, object and assets within the site. per:Site nodes are located consistently at /content/site[per:Site], which would allow component and site developers a consistent way to extend for their needs providing a basic consistent pattern.

Steps
1. add method getSiteResource() to `platform/base/adaption/PerBase.java` which shall return the `per:Site` ancestor Resource
1. Where base template properties are used, refactor these getters to seek hierarchically upward for the properties. This should allow the site content with the base template architecture to continue working. and new sites to utilize setting properties at the per:Site node
1. add form elements for an tenant configuration interface which facilitates setting siteCSS and other properties. for example
`/content/admin/pages/tenants/configure.html/path:/content/example` would be the URL to set tenant settings for the Example site. 
1. Provide a lightweight method of publishing just the tenant settings from /content/admin/pages/tenants/configure.html. Current "Site Setup Replication" can be a very heavy operation. Site Setup Replication is not intuitive, as the word setup implies from sort of configuration, but clicking the button runs a big operation that cannot be confirmed or cancelled

**Comment by ehdatheadwire** [comment]
Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/53 where it will get grouped together with other UX/UI enhancements and refactoring.
