### ISSUE TITLE
rich-toolbar state not updating properly

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#638]
### Reproduction
* Open Page "article/welcome"
* click on teaser-headline
* click on inline-edit at the bottom (long lorem ipsum text)
* ![image](https://user-images.githubusercontent.com/50131232/97302818-d9ca4580-1859-11eb-96f9-f2e51ddffbdc.png)

### Expected Result
![image](https://user-images.githubusercontent.com/50131232/97302934-ff574f00-1859-11eb-87b2-d9c22433239c.png)

**Comment by flx-sta** [comment]
### Verify if bug is still present: **STILL PRESENT**
![image](https://user-images.githubusercontent.com/50131232/103766017-5e85cc80-501e-11eb-8f08-058c8122ab96.png)

![image](https://user-images.githubusercontent.com/50131232/103766457-27fc8180-501f-11eb-9016-e4d18e958b6f.png)
the big one seems to update properly. the small one not

**Comment by reusr1** [comment]
@Felix-Puetz is this still an issue? seems the PR has been merged
