### ISSUE TITLE
Page Component is missing after creating new site

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#64]
When creating new site through *percli create project <name>* the created site doesn't include the page component which makes it impossible to drag components onto the page.

**Comment by reusr1** [comment]
@FabianHaupt this problem should be solved. Please rebuild the peregrine-cms project to update your archetype locally and then create a new project with `percli create project`

**Comment by FabianHaupt** [comment]
It works 👍
