### ISSUE TITLE
rich-editor reactivity impaired upon "finish and edit!" of new page

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#640]
### Description
Creating a new page and directly editing it (`finish and edit` button) causes rich-texte editor reactivity to not work properly.
A simple reload of the page fixes with issue (which is the current workaround too #637)

### Reproduction
- Create a new page
- go through the create wizzard as usual BUT WAIT AT THE LAST STEP
- at the last step click on `finish and edit!`
- select any rich-inline-edit component and type into it.
  - you will see that the editor on the right side does not update accordingly
- reload the page
- try the same again: works

**Comment by ehdatheadwire** [comment]
Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/52
