### ISSUE TITLE
Integrated feedback button

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#646]
### As suggested in the weekly-water-cooler meeting 2020-11-10:

- implement a simple "Feedback" Button into the admin-interface
- Provide minimum of 2 fields: name & message
- This content is then converted into an issue using some sort of github bot/hook 
- the issues get a specific tag to be able to filter them

**Comment by reusr1** [comment]
it would be nice to check if there is an open source version of a tool such as https://www.userback.io/ available, as this would make feedback in general easier for everybody.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/35
