### ISSUE TITLE
Support for step-by-step lists

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#647]
While the rich text editor is a decent approach for creating small lists, it's not particularly well-suited for article-length lists that may require mixed content (i.e. text + image + video as an item within the list). A good example of list-based articles are step-by-step articles as used on  https://www.instructables.com/.

One approach to solve this is to create a list container and and list item container. The List Container can control the type of list (ordered list, unordered list, other presentation format) and accept one or more List Item components. The list item components are just simple containers for any other component available in Peregrine.

```
List Container Component
|_List Item
   |_Text Component
|_List Item
   |_ Text Component
   |_ Image Component
   |_ Text Component
|_List Item
   |_ Text Component
   |_ Video Component
|_ List Item
   |_ Text Component
   |_ Card Component
```

**Comment by reusr1** [comment]
@GastonGonzalez would this not be a themecleanflex ticket?

**Comment by GastonGonzalez** [comment]
> @GastonGonzalez would this not be a themecleanflex ticket?

It is. I will close and re-open.

**Comment by GastonGonzalez** [comment]
themeclean-flex issue created: https://github.com/headwirecom/themeclean-flex/issues/171
