### ISSUE TITLE
Unable to create site in admin.dev-kestrel-1.dev (if the name was used before)

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#655]
I was unable to create a new site titled _Test_ in [admin.dev-kestrel-1.dev](https://admin.dev-kestrel-1.dev/). The reason is most likely the fact that before trying it out today I already had a tenant under the same name a while back. A different name worked properly.

![kestrel-test](https://user-images.githubusercontent.com/5563546/99505664-665fb380-2981-11eb-9785-e5929d59e326.png)

**Comment by GastonGonzalez** [comment]
@reggie7 - There is already a ticket for this issue. Would you mind scanning the issues and assigning it to yourself? We need to update the validation in the UI to check if a tenant already exists. We'd like the to capture this condition at the time the user enters the tenant name.

**Comment by reusr1** [comment]
https://github.com/headwirecom/peregrine-cms/issues/549

**Comment by GastonGonzalez** [comment]
> #549

Thanks, @reusr1 !

**Comment by reggie7** [comment]
Ok, thanks, I'll take #549 then
