### ISSUE TITLE
Tenant user can't replicate themecleanflex assets: NPE is thrown

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#657]
**Steps to reproduce**
1. Create a new tenant with password and log in as its user,
1. Open Website Themes → ThemeCleanFlex Site → Assets → samples,
1. Open browser DevTools,
1. Replicate e.g. `beach-bird-s-eye-view-daytime-1249586.jpg`.

**Expected Result**: that's actually a good question what the expected result should be. We want the tenant user to be able to replicate referenced assets, but on the other hand it's a shared space.
**Actual Result**: I'm pretty sure though, that the current course of actions is not desired. We get a console error:

![console-error](https://user-images.githubusercontent.com/5563546/99788398-58489900-2b21-11eb-812b-58e35a5439c9.png)

that comes from an [NPE](https://github.com/headwirecom/peregrine-cms/files/5572798/error.log):

![NPE](https://user-images.githubusercontent.com/5563546/99788423-5e3e7a00-2b21-11eb-8635-ca90a325fc9e.png)

**Comment by reggie7** [comment]
Branch: `develop-sling12`

**Comment by reusr1** [comment]
a site has a relation to a theme (in /content/[tenant]). In general, the theme needs to be activated in order for a site to work. I think we should limit replication to a single tenant and not allow cross tenant replication. Best would be to make this an osgi config in the replication settings (cross tenant replication on/off)

**Comment by reusr1** [comment]
@reggie7 before we start addressing this ticket lets come to an understanding of how we are going to solve the issue

I suggest:
- replications are limited to a single tenant and do not cross into other tenants
- we expect that themecleanflex (or the basic theme sites are built from) are replicated when setting up a production environment

This can be of course discussed in a larger group. My main concern: 

if site a uses themecleanflex nd site b uses themecleanflex and they both re published, why would we publish themecleanflex 2x and could this lead to larger issues especially in the future when themeclenflex changes. 

To me the easiest for now is to control the replication of themecleanflex independently from the replication of tenants.

**Comment by reggie7** [comment]
Fixed in [issues/657-tenant-site-setup-replication-NPE](/headwirecom/peregrine-cms/tree/issues/657-tenant-site-setup-replication-NPE). Once [773](https://github.com/headwirecom/peregrine-cms/pull/773#issuecomment-814195222) is merged, I'll open the next PR for this one here.
