### ISSUE TITLE
Assets do not replicate properly

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#658]
**Steps to reproduce**
1. Create a new tenant with password and log in as its user,
1. Open Assets of the site,
1. Open browser DevTools,
1. Replicate an image.

**Expected Result**: The asset gets replicated, version is created, icon indicates published status.

**Actual Result**: The asset gets partially replicated, only 1 out of 3 `per:Replication...` properties get set, the globe icon indicates nothing, console displays an error:

![console-log](https://user-images.githubusercontent.com/5563546/99791419-df980b80-2b25-11eb-8681-284a1c93d63f.png)

that comes from [an NPE](https://github.com/headwirecom/peregrine-cms/files/5572968/stacktrace.log):

![NPE](https://user-images.githubusercontent.com/5563546/99791456-f0488180-2b25-11eb-87c0-55d8abf5e664.png)

**Comment by reggie7** [comment]
Found in `develop-sling12`, partially solved in #648 but it still gets deeper than that.

**Comment by reggie7** [comment]
To do: `com.peregrine.slingjunit.localFS.LocalFSJTest#replicateOneAsset`

**Comment by reggie7** [comment]
@KWoloszczuk please test the branch [issues/658-assets-do-not-replicate-properly](https://github.com/headwirecom/peregrine-cms/tree/issues/658-assets-do-not-replicate-properly)

**Comment by ghost** [comment]
Hey @reggie7 I found this while testing your branch:

https://user-images.githubusercontent.com/1230506/107504925-49abd400-6b9c-11eb-89db-a475afde2560.mp4

**Comment by ehdatheadwire** [comment]
@reggie7 is this still in need of PR review? Last note was from 11 days ago so if it's still in need of a review, let us know and we'll push it through so we can close it out.

**Comment by reggie7** [comment]
Yes, PR #773 is prepared and waiting for reviews. It's available for front-facing testing too, so both you @ehdatheadwire and @KWoloszczuk could give it a spin.

**Comment by ehdatheadwire** [comment]
Great, thank you. Will take a look.
