### ISSUE TITLE
Old user gets access to new site

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#660]
**Steps to reproduce**
1. Grab a fresh instaance with `develop-sling12` on board,
1. Create a new site `Test` with password,
1. Optionally check that you have access as the `test_user`,
1. Remove the site,
1. Create the same site again, this time without any password,
1. Log in as `test_user`.

**Expected Result**: The old `test_user` should not see the new `Test` site / tenant.
**Actual Result**: They do see the new site.

Also - what happens if one does create the site again with the password actually?

**Comment by reusr1** [comment]
@reggie7 I think we should address this issue together with https://github.com/headwirecom/peregrine-cms/issues/447 - we need a way to invite others to collaborate on a site and handle removal of users/sites accordingly

**Comment by ehdatheadwire** [comment]
Judging by your last comment, @reusr1, this might be something to consider as required for 1.0.0 release as we'd like to make it as easy as possible to invite collaborators to the platform and manage users/sites. I'm marking it as such but feel free to adjust or move as warranted.
