### ISSUE TITLE
ResourceResolver.revert could follow exception on ResourceResolver.commit

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#662]
During my work on #614 I have stumbled upon a problem that we might want to solve in general. We have to perform a sequence of method calls that effectively lead to the following:
1. Do some repo changes and commit them,
1. Do some repo changes and commit them.

Most often than not, these steps use the following code:
```
try {
    resourceResolver.commit();
} catch(PersistenceException e) {
    return;
}
```
Once we catch the exception - we leave the `ResourceResolver` with the changes. Then in the next step - when we try to `commit` another set of changes on the same `ResourceResolver` - it will also fail on the previously made changes even if our current changes are fine.
I believe we should add `resourceResolver.revert()` in the `catch` block. And perform an analysis of this issue in the whole basecode.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating here: https://github.com/peregrine-cms/enhancements/issues/32

@reusr1 and @reggie7 if you think this needs to be included as part of the Sling12 work, we can pull it back in; but as it's not strictly a bug, I moved it for now. Thx.
