### ISSUE TITLE
Input value not synchronized with inline-edit (non rich-text)

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#679]
## Reproduction
1. Have a tenant ready or create a new one
1. create a new page 
1. drop `teaser-vertical` component in
1. select the newly added component
1. change the title of the component via edit-panel (richt side)
1. the view won't update

## Info
Upon further investigation: the vue-object does update though so it's either broken `reactivity` or missing `watchers`

**Comment by reusr1** [comment]
PR merged, looks good and editor feels faster
