### ISSUE TITLE
Own Component has no Text

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#68]
I followed the quickstart guide and created my own site and own component. I can drag the component onto the page but it its just an empty div with no text.

**Comment by reusr1** [comment]
@FabianHaupt do you have maybe some more information about this? I just ran through the steps and they seem to work just fine for me. Would love to maybe see your project

**Comment by reusr1** [comment]
sorry, after further review there is an error in the docs: 

```module.exports = {
  convert: function($, f) {
    f.bindPath($)
    f.mapField($, 'text')	
  }
}```

should be 

```module.exports = {
  convert: function($, f) {
    f.bindPath($)
    f.mapField($, 'model.text')	
  }
}```

**Comment by FabianHaupt** [comment]
It works 👍
