### ISSUE TITLE
Reference link does not work

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#689]
We click here:
<img width="347" alt="originator" src="https://user-images.githubusercontent.com/5563546/102884193-7ae80d80-4451-11eb-882e-ca3ae6353521.png">
And get this:
![error](https://user-images.githubusercontent.com/5563546/102884220-889d9300-4451-11eb-9b3e-41d0ca35a24b.png)

**Comment by flx-sta** [comment]
Could not reproduce
@reggie7

**Comment by reggie7** [comment]
Hey @Felix-Puetz I have good news and bad news. The bug is actually still in there unfortunately, but it's fairly easy to reproduce:

https://user-images.githubusercontent.com/5563546/104940380-f0dc8780-59b1-11eb-94b0-724285a59f5b.mov

My instance was freshly built from `develop-sling12` branches both PCMS and TCF. It's hard for me to say why I couldn't get it on Monday.
