### ISSUE TITLE
Swagger Editor not available for tenant user

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#691]
[/perapi/swaggereditor](http://localhost:8080/perapi/swaggereditor/) yields a `404` under a tenant user, but works for admin.

**Comment by reusr1** [comment]
PR opened for this issue, tenant users will now have access to the swagger api (everyone is still declined access)

**Comment by reusr1** [comment]
confirmed issue is resolved in develop-sling12
