### ISSUE TITLE
pathbrowser: add/upload assets on the fly

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#697]
Implement upload support for pathbrowser to add assets on the fly

**Comment by reggie7** [comment]
I think the refresh has a hickup in my instance:

https://user-images.githubusercontent.com/5563546/104244007-d9f1de80-5461-11eb-8305-08cdc6e0349b.mov

**Comment by reggie7** [comment]
Other than that, as a UX side-note to @reusr1 - personally I don't fancy the `OK` button one has to click after the upload is done. I'd rather see it like this: after the upload ends we pre-select the new file. The same could happen in Assets console actually.

**Comment by Felix-Puetz** [comment]
@reggie7 thanks for your review but I'd rather put bugs related to the PR Into the pr.

I'll look into the bug thanks alot.

About the user-experience: In my first scratch of this I actually made it that after finishing the upload the whole overlay would disappear. Thing is here: the upload is so fast that the overlay was barely visible. So I stuck to the known format for now but I agree that the current experience is not my favorite

**Comment by flx-sta** [comment]
@reggie7 I've moved the comments into the PR #701 👍

**Comment by reggie7** [comment]
> @reggie7 I've moved the comments into the PR #701 👍

Ah, sorry @Felix-Puetz - I must have used the wrong tab in my browser 😒 The comments were obviously meant to go to the PR 😏
