### ISSUE TITLE
Copy/Paste works incorrectly

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#702]
When we copy Cards component with <= 3 items we'll get 4 in return.
When we copy Accordion with >4 cards we'll get a `js` error.
In general the `insertNodeAt` methods are combining incoming content with variants, which might actually not make sense anymore in some places where it's used.

**Comment by reusr1** [comment]
@Felix-Puetz @reggie7 can this ticket be closed as the corresponding branch has been merged?

**Comment by reggie7** [comment]
Yes, just checked it in `develop-sling12`, merged and fixed.

**Comment by reusr1** [comment]
cool, closing the issue :)
