### ISSUE TITLE
Remove RemoteS3SystemReplicationService and dependencies

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#705]
Amazon Replication is obsolete now. `platform/external` should go too.

**Comment by reggie7** [comment]
To do: notify @GastonGonzalez to check the PR result against Karaf.

**Comment by GastonGonzalez** [comment]
@reggie7 was this merged?

**Comment by reggie7** [comment]
No, but I figure there is no point in keeping this one open together with #706 especially that we have [the board](https://github.com/headwirecom/peregrine-cms/projects/7#card-52744898) now. We could discuss this version of the workflow obviously if others see it differently.
