### ISSUE TITLE
materialchecklist field not working

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#71]
I've added the following JSON to my mode.json in a custom component: 

```
"checklist": {
  "type": "string",
  "x-source": "inject",
  "x-form-label": "Choose Type",
  "x-form-type": "materialchecklist",
  "properties": {
    "type1": {
      "x-form-name": "Type 1",
      "x-form-value": "type1"
    },"type2": {
      "x-form-name": "Type 2",
      "x-form-value": "type2"
    }
  }
}
```

Then I added my custom component to a page, clicked on it to open the editor-panel and everything I could see was this:

<img width="290" alt="Screenshot 2019-05-07 at 07 56 28" src="https://user-images.githubusercontent.com/50131232/57367626-a7221e00-7189-11e9-9e53-5a76e9ca2e54.png">

According to [the documentation](http://www.peregrine-cms.com/docs/sitedev/addcomponent/formfields.html) it should look something like this:
![image](https://user-images.githubusercontent.com/50131232/57367708-cc169100-7189-11e9-8af9-272029ab0a12.png)

**Comment by dna113p** [comment]
@Felix-Puetz Currently looking into this, looks like the checklist component is missing some recent updates.

**Comment by bkheadwire** [comment]
@dna113p I see that there's a branch for this (issues/71) but it doesn't appear to have been merged. Is it done?

**Comment by flx-sta** [comment]
I've merged the newest develop into the issue/71 branch. 
But i couldn't get the "materialchecklist" field to work at all
![image](https://user-images.githubusercontent.com/50131232/73372329-50c8b280-42b7-11ea-9053-7154e17c68ae.png)

**Comment by flx-sta** [comment]
dismissed
