### ISSUE TITLE
Remote replication UI Times-out

### ISSUE THREAD

**Issue by cmrockwell** [headwirecom/peregrine-cms#718]
When using remote replication, the UI does not work. 

Given the author and publisher configured with remote repl, and junit tests passing
<img width="996" alt="Screen Shot 2021-01-21 at 6 14 01 PM" src="https://user-images.githubusercontent.com/1811207/105424054-968f3100-5c14-11eb-85fc-38274e2f62e9.png">

Using the UI nothing gets replicated, nothing gets replicated and the polling times-out.
<img width="1399" alt="Screen Shot 2021-01-21 at 6 12 37 PM" src="https://user-images.githubusercontent.com/1811207/105424091-b292d280-5c14-11eb-816e-a4727211a075.png">

the list `toBeReplicated` is getting set to an empty list by the default implementation.
<img width="1310" alt="Screen Shot 2021-01-21 at 6 18 40 PM" src="https://user-images.githubusercontent.com/1811207/105424390-4a90bc00-5c15-11eb-9700-40cf57647d0a.png">

**Comment by ehdatheadwire** [comment]
Unclear to me if this is required for 1.0.0 release. If yes, we'll mark it as such. If no, we'll move it to the enhancements queue and get it grouped with other replication tickets, of which there are several. Thanks!

**Comment by cmrockwell** [comment]
This one was fixed in PR719 which was merged into PR717, and then into sling-develop12 on Jan 21, 2021.
After updating my systems, I confirmed the issue is still fixed as of 3/14/2021. There does seem to an issue replicating asset folders... but this ticket is about UI operation timing out during pages and assets remote replication.
