### ISSUE TITLE
how to use sling-11.jar?

### ISSUE THREAD

**Issue by hanbi918** [headwirecom/peregrine-cms#72]
Now peregrine-cms use sling-9, when to upgrade to sling-11? I also found a branch for sling-11,how can i use it? thanks!

**Comment by reusr1** [comment]
we plan to be on sling11/java11 by the time we release peregrine 1.0.0. You can use https://github.com/headwirecom/peregrine-cms/tree/upgrade-to-sling-11 for sling11/java11
