### ISSUE TITLE
Site Setup Replication takes forever in LocalReplicationService

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#720]
Found in #658. **Site Setup Replication** in `LocalReplicationService` takes too long, I had it work for over 28 minutes. The problem arises from the amount of resources that `replication.findReferences` returns. It's the full tree of the initial list plus its references. There can be even 12k of them. `LocalFileSystemReplicationService` does the same on ~500 resources. I think there's no point in having different implementations of the reference search. Let's fix it.

This is a log from my test, time in seconds (`t` = time since the start, `dt` = time since the previous log):
1. Starting `TenantSetupReplicationServlet.performReplication`, t = 0, dt = 0
2. Starting `extractSiteFeLibs`, t = 0, dt = 0
3. Finished `extractSiteFeLibs`, t = 0, dt = 0
4. Starting `replication.findReferences`, t = 0, dt = 0
5. Finished `replication.findReferences`, t = 1, dt = 1
6. Starting `replication.prepare`, t = 1, dt = 0
7. Finished `replication.prepare`, t = 1, dt = 0
8. Starting `resourceManagement.createVersion`, t = 1, dt = 0
9. Finished `resourceManagement.createVersion`, t = 242, dt = **240**
10. Starting `replication.replicate`, t = 242, dt = 0
11. Finished `replication.replicate`, t = 1720, dt = **1478**
12. Starting `siteMapFilesCache.build`, t = 1720, dt = 0
13. Finished `siteMapFilesCache.build`, t = 1720, dt = 0

**Comment by reggie7** [comment]
@cmrockwell I have noticed similar behavior in **remote replication**, though not so severe, 5 minutes or so.

**Comment by reggie7** [comment]
@reusr1 let's evaluate that after the decision to leave od remove the `local` replication approach.

**Comment by ehdatheadwire** [comment]
@reggie7 and @reusr1 is this required for 1.0.0 release and, if not, should it be moved to the enhancement queue for future work/discussion?

**Comment by reusr1** [comment]
added to 1.0.0 release - 12k resources seems high - do we have dulpicates or items that can not be replicated in the list? Should we limit the site setup replication to the tenant?

**Comment by reggie7** [comment]
@reusr1 it's `local` though, so we need to remember that we were also considering dropping it altogether.

**Comment by reggie7** [comment]
Fixed in [issues/657-tenant-site-setup-replication-NPE](/headwirecom/peregrine-cms/tree/issues/657-tenant-site-setup-replication-NPE). Once [773](https://github.com/headwirecom/peregrine-cms/pull/773#issuecomment-814195222) is merged, I'll open the next PR for this one here.
