### ISSUE TITLE
Folders' replication fails

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#722]
Assets console allows folders to be added to the structure, but default system settings prevent them from replication - one always gets _Action timed out when publishing_. We could simply add `sling:OrderedFolder` + `sling:Folder` + `nt:folder` to [ReplicationMixinNodeTypesOverride](http://localhost:8080/system/console/configMgr/com.peregrine.replication.impl.ReplicationMixinNodeTypesOverride), but this might cause unwanted side effects elsewhere.
Same applies to tags, though there is [another UI/UX related inconsistency](723) there.

**Comment by reusr1** [comment]
@reggie7 seems to me we should all discuss what a folder replication would mean - if the folder replication just creates the subfolder on the target I am not sure how much value it is to the user. On the other hand we also do not have folder properties at the moment nor are we allowing for folders to be deep replicated? 

@cmrockwell you also may have some opinions about this topic?

**Comment by reggie7** [comment]
@reusr1 yes, let's discuss it. I say we either figure out together what it would mean to replicate a folder or we simply do not display the respective icon for the operation.

**Comment by ehdatheadwire** [comment]
Assuming that this is not required for 1.0.0 release and will involve more discussion, I'm marking it as "move" rather than just relocating it in case I'm incorrect in my assumption.

**Comment by reusr1** [comment]
@ehdatheadwire decision needs to be made if we can publish folders in assets or not and around the UX for this.

options:
- publishing a folder publishes all its children assets, optionally all the assets in child folders recursively)
- publishing a folder is not allowed and the UI has to be updated to reflect that

note: we also have to define the behavior for unpublish at the same time

for simplicity: 
- I think its best to create an enhacement ticket on publishing/unpublishing trees (pages, assets, objects, templates, ...) 
- move this ticket forward by disabling the publishing of folders in assets (should probably be a new ticket and this ticket can be closed)

**Comment by ehdatheadwire** [comment]
New issue created in enhancements: https://github.com/peregrine-cms/enhancements/issues/62.

New ticket created for disabling publishing of folders in assets here: https://github.com/headwirecom/peregrine-cms/issues/790
