### ISSUE TITLE
Objects console is inconsistent with folders

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#723]
When we create a new tenant from Theme Clean Flex - we'll get an OoTB `tags` folder, but we can't add a new one:

<img width="329" alt="objects" src="https://user-images.githubusercontent.com/5563546/106458763-2349b280-6491-11eb-924e-8be672f10eab.png">

Assets console allows that though:

<img width="360" alt="assets" src="https://user-images.githubusercontent.com/5563546/106458783-2775d000-6491-11eb-9b7c-3c6d9ee57bbe.png">

**Comment by reusr1** [comment]
@reggie7 add folder for objects in the top bar and not below the list. For assets we only keep the create folder at the bottom, upload a file, find an asset is at the top right. I dont think it makes sese to list every action possible on the list at the bottom of the list.

**Comment by reggie7** [comment]
Oh, yes, my bad. Forgot about the top right bar. Though it raises a UX issue - as a user I was expecting coherent UI among all consoles. So I think one would expect to either see _add object_ and _add asset_ respectively or _add folder_ in both consoles. I'd say the former would be used more often.

**Comment by ehdatheadwire** [comment]
Closing and relocating to: https://github.com/peregrine-cms/enhancements/issues/55
