### ISSUE TITLE
Unpublishing does not work

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#724]
Local File System:
* Unpublish Object does not work

Local Replication:
* Unpublish Page does not work
* Unpublish Asset does not work
* Unpublish Object does not work
* Unpublish Template does not work

Remote Replication:
* Unpublish Page does not work
* Unpublish Asset does not work
* Unpublish Object does not work
* Unpublish Template does not work

And, what is important, by **does not work** we only mean that upon clicking _Unpublish_, the following error is displayed:
<img width="1785" alt="unpublish error" src="https://user-images.githubusercontent.com/5563546/107279213-0ac03600-6a57-11eb-8c2a-3026c73035a1.png">

**Comment by reggie7** [comment]
@KWoloszczuk please test the branch [issues/724-unpublishing-does-not-work](https://github.com/headwirecom/peregrine-cms/tree/issues/724-unpublishing-does-not-work)

**Comment by reggie7** [comment]
I have confirmed this ticket to be solved for **localFS** and **local** modes within PR #773. I can't get the **remote** option to properly run as described in [the docs](https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/docs/public/distribution/index.md#peregrine-to-peregrine-copies). I guess this has to do with our latest changes to [`peregrine-builder`](https://github.com/peregrine-cms/peregrine-builder).

@cmrockwell could you check unpublishing within your review of #773? I remember that it was all fine back when I could easily set up author-publish env myself, but would be nice to confirm that. Can you check what is missing in [the docs](https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/docs/public/distribution/index.md#peregrine-to-peregrine-copies) from the point of view of the latest [`peregrine-builder`](https://github.com/peregrine-cms/peregrine-builder)?

**Comment by reggie7** [comment]
@reusr1 I noticed that it's no longer possible to install peregrine from `develop-sling12` within running `launcher` built from [`peregrine-builder-sling-12`](https://github.com/headwirecom/peregrine-cms/tree/develop-sling12/sling/peregrine-builder-sling-12). `mvn` build process can't get the bundles to start. Maybe we should consider removing this part of the code in `develop-sling12` since the proper part already lives within [`peregrine-builder`](https://github.com/peregrine-cms/peregrine-builder)?

**Comment by reusr1** [comment]
> @reusr1 I noticed that it's no longer possible to install peregrine from `develop-sling12` within running `launcher` built from [`peregrine-builder-sling-12`](https://github.com/headwirecom/peregrine-cms/tree/develop-sling12/sling/peregrine-builder-sling-12). `mvn` build process can't get the bundles to start. Maybe we should consider removing this part of the code in `develop-sling12` since the proper part already lives within [`peregrine-builder`](https://github.com/peregrine-cms/peregrine-builder)?

@reggie7 I was trying to be nice and did a 'soft remove' through the README.md at https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/sling/peregrine-builder-sling-12/README.md

**Comment by reusr1** [comment]
@ehdatheadwire I think the core of this issue should be added to https://github.com/peregrine-cms/enhancements/discussions/58 - there is a secondary issue here that we dont have a good stage/live setup for testing purposes (should be a 1.0.0 release item together with us trying to move to the latest sling distribution bundles)

**Comment by ehdatheadwire** [comment]
@reusr1 -- understood. I'll add to enhancements -- should there be a new ticket for the setting up of a good stage/live environment for testing purposes?

**Comment by reggie7** [comment]
#773 already provides the fix here, so we should be good once it's merged. It's already in `PR to review` column of [Replication project](https://github.com/headwirecom/peregrine-cms/projects/7#card-54056577).
The environment thing is separate though, not covered in the PR obviously:
> there is a secondary issue here that we dont have a good stage/live setup for testing purposes
