### ISSUE TITLE
uploadFiles() returns unreliable

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#725]
### Description
The `uploadFiles` method in `apiImpl.js` and the stateAction are very unreliable when it comes to feedback handling.

### Example
When uploading a file `A.png` and an asset with that name already exists you get a prompt to `Replace` or `Keep Both`.

When selecting `Keep Both` you don't have ANY CHANCE to have feedback about the new file-name.

**Comment by ehdatheadwire** [comment]
@Felix-Puetz and @reusr1 is this required for 1.0.0 release?

**Comment by reusr1** [comment]
closing as this has been merged
