### ISSUE TITLE
creating a new component through keyboard shortcuts sets the current inline edit text to undefined

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#726]
- create a new site with themecleanflex
- on the homepage edit one of the cards
- while editing insert a new rich text component (example) below with `ctrl-dot`

note: inline text of current component is switched to undefined

**Comment by reusr1** [comment]
![Screenshot from 2021-02-03 07-37-30](https://user-images.githubusercontent.com/779992/106770387-c6660d80-65f2-11eb-84ef-70c0c7067dd1.png)

**Comment by flx-sta** [comment]
@reusr1 should i move this into my project?
if so high prio?
