### ISSUE TITLE
“No status” after publishing an object

### ISSUE THREAD

**Issue by ghost** [headwirecom/peregrine-cms#727]
Web Publishing tab shows “No status” after publishing an object.

**Steps to Reproduce**

1. Open “objects” Peregrine console.
2. Go to the “tags” folder.
3. Add a tag object.
4. Publish the tag.
5. Open tag properties panel (e.g. with info icon).
6. Open “Web Publishing” tab.

**Expected behavior**
After publishing the status should change to “Published”.

**Actual behavior**
The status is “No Status”.

**Screenshots**

![object no status](https://user-images.githubusercontent.com/1230506/107036514-0e835c80-67ba-11eb-8f60-d3dcd3a56a6e.png)

**Environment**

- `develop-sling12`
- Firefox 85
- Windows 10 (64bit)

**Comment by ehdatheadwire** [comment]
Closing and relocating to enhancements, likely to be included in the overall publishing/unpublishing user flow discussion: https://github.com/peregrine-cms/enhancements/issues/63

**Comment by reggie7** [comment]
#785 fixed it, merged already.
