### ISSUE TITLE
The tag can’t be deleted from page properties once added.

### ISSUE THREAD

**Issue by ghost** [headwirecom/peregrine-cms#729]
Once tag is added it can't be removed.

**Step to Reproduce**

1. Open “objects” Peregrine console.
2. Add an object. 
3. Open editing of any page.
4. Click on menu on the right “page-info”
5. Add an object from “Tags”
6. Publish to Web.
7. Delete an object from “Tags”
8. Publish to Web.
9. Go back to the “page-info”.
10. Tag is not removed.

**Expected behavior**
After removing the object from “Tags” and publishing, the object should be deleted.

**Actual behavior**
Tag is not removed from "Tags" after deleting.

**Screencapture video**

https://user-images.githubusercontent.com/1230506/107048758-958c0100-67c9-11eb-946e-78fb6c879416.mp4

**Environment**
 - Firefox
-  85
 - Windows 10 (64bit)

**Comment by reggie7** [comment]
I think that it actually doesn't even involve publishing. Can you confirm @KWoloszczuk the same when the author does not publish the page, but simply does a refresh of the browser tab after saving the change?

**Comment by ghost** [comment]
Yes, you're right.

**Comment by ehdatheadwire** [comment]
Closed and relocated to: https://github.com/peregrine-cms/enhancements/issues/57
