### ISSUE TITLE
Being able to delete page component from template

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#73]
When you create a new site and then edit it under templates you are able to delete the page component which leads to the site being useless since you cant drag any components on it anymore. Is that intended?

**Comment by reusr1** [comment]
@FabianHaupt thank you for the ticket. Definitely not intended. We should block delete actions of the root node of a page.

**Comment by reusr1** [comment]
@FabianHaupt this has been addressed in develop, if you have time, can you please verify and close this issue?

**Comment by FabianHaupt** [comment]
@reusr1 I dont think it has been merged into develop yet

**Comment by reusr1** [comment]
@FabianHaupt you can check out https://github.com/headwirecom/peregrine-cms/pull/121 to see it in action pr branch https://github.com/headwirecom/peregrine-cms/tree/issue/73 - sorry

**Comment by FabianHaupt** [comment]
@reusr1 I checked it out and i cant delete it anymore
