### ISSUE TITLE
Template is not removed after unpublishing

### ISSUE THREAD

**Issue by ghost** [headwirecom/peregrine-cms#730]
After unpublishing template is not removed from page.

**Step to Reproduce**

1. Create new page with template.
2. Click “Publish”.
3. Open “Templates” Peregrine console.
4. Click “Unpublish”
5. Template is still on page.

**Expected behavior**
After unpublishing template should be removed.

**Actual behavior**
Template is not removed from page after unpublishing.

**Screencapture video**

https://user-images.githubusercontent.com/1230506/107055591-bd7f6280-67d1-11eb-8417-80fe37088318.mp4

**Environment**
 - Firefox
-  85
 - Windows 10 (64bit)

**Comment by reusr1** [comment]
@KWoloszczuk what URL are you using to check the page? 

I think its actually dangerous to be able to unpublish a template that is used by published pages. We probably should prohibit that in the first place or also force unpublishing all the pages that use that template

@cmrockwell @ehdatheadwire you guys may have an opinion here as well I'd assume?

**Comment by ghost** [comment]
I'm using the usual link to the page on my local http-server - http://localhost:1080/content/local_fs/pages/test01.html

**Comment by reggie7** [comment]
@reusr1 `localhost:1080` comes from running `http-server . -p 1080` inside `staticreplication` on @KWoloszczuk's local machine I guess.

@KWoloszczuk the current shape of the bug that you described will most likely need to be adjusted just as @reusr1 mentioned above. There is no way possibly to remove the template from a page. But your perception of this as a bug indeed highlights an issue - we need to make this less confusing. @reusr1 gives good examples of the direction we might want to go.

We should remember that `local file replication` will work differently from `remote` and `local intra` approaches. Static files inside `staticreplication` got rendered with a template already and they don't care how the status of the template changes later. It's not the case with the other replications.

**Comment by ehdatheadwire** [comment]
> @KWoloszczuk what URL are you using to check the page?
> 
> I think its actually dangerous to be able to unpublish a template that is used by published pages. We probably should prohibit that in the first place or also force unpublishing all the pages that use that template
> 
> @cmrockwell @ehdatheadwire you guys may have an opinion here as well I'd assume?

Yes, @reusr1 we should look at this user flow in a little more detail. Certainly from a permissions level. There would need to be more stopgaps to unpublishing a template, if we even allow it in the first place. 

I'll move this to the enhancement queue as a UI task to look into a bit more.

**Comment by ehdatheadwire** [comment]
Closed and relocated to: https://github.com/peregrine-cms/enhancements/issues/56
