### ISSUE TITLE
Put branch and/or commit somewhere in the about screen?

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#731]
Maybe we should show the version information of the currently installed Peregrine instance somewhere in the about section?

<img width="1022" alt="about screen" src="https://user-images.githubusercontent.com/5563546/107216503-269eea00-6a0d-11eb-8e70-3860a7d89b09.png">

From technical standpoint there's[ a plugin for that ](https://github.com/git-commit-id/git-commit-id-maven-plugin), example usage [here](https://stackoverflow.com/questions/21553304/put-current-git-branch-to-project-version).

**Comment by ehdatheadwire** [comment]
@reggie7 and @reusr1 -- looks like a candidate for the enhancement queue but didn't want to assume. Let me know if it's required for 1.0.0 release or not and I'll mark accordingly.

**Comment by reusr1** [comment]
@reggie7 is there something in particular you are trying to solve with this? the git branch probably wont be a good idea for the 'product' itself - seems very developer focused. Would be great to start an enhancement ticket describing the issue we are trying to solve with this.

**Comment by ehdatheadwire** [comment]
@reggie7 I went ahead and opened up an enhancement ticket here: https://github.com/peregrine-cms/enhancements/issues/64 but I'll keep this open so you can respond to @reusr1 's question. Not sure if we've opened up the new repository yet but if you have access to the above link, you can go ahead and note your questions/proposal there.

**Comment by reggie7** [comment]
@ehdatheadwire, just answered in [64](https://github.com/peregrine-cms/enhancements/issues/64#issuecomment-801028019).
