### ISSUE TITLE
Template is not published after publishing

### ISSUE THREAD

**Issue by ghost** [headwirecom/peregrine-cms#732]
Template is not published after publishing.

**Steps to Reproduce**

1. Create a template.
2. Create a page with this template.
3. Publish them both.
4. Edit template and add a picture.
5. Publish only template.
6. There is no picture in browser, although it is on the page in editor. 

**Expected behavior**
After publishing template, picture should appear in browser. 

**Actual behavior**
It only appears after publishing page. 

**Screencapture video**

https://user-images.githubusercontent.com/1230506/107221239-a8921180-6a13-11eb-92a1-ab3694dcfd1d.mp4

**Environment**
 - Local FS
 - develop-sling12
 - Firefox
 - 85
 - Windows 10 (64bit)

**Comment by reusr1** [comment]
@reggie7 is this an issue with the static replication? do we render the pages that depend on the template when a template is published again? - @ehdatheadwire removing the 'move' label as this affects editors and imho should be fixed for 1.0.0

**Comment by reusr1** [comment]
@ehdatheadwire please move to the enhancements and add the ticket to https://github.com/peregrine-cms/enhancements/discussions/58

**Comment by ehdatheadwire** [comment]
Sure thing. Find your new ticket here: https://github.com/peregrine-cms/enhancements/issues/65.
