### ISSUE TITLE
Show full username in `create a website / choose name` screen

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#734]
Currently we only show a recipe info for getting the tenant user name:

<img width="1294" alt="Zrzut ekranu 2021-02-9 o 12 29 12" src="https://user-images.githubusercontent.com/5563546/107357911-fcaffb00-6ad2-11eb-91ef-3e272fe4c509.png">

I think that we should display a label with the resulting username explicitly. And add a _copy to clipboard_ button just as in #498

**Comment by reusr1** [comment]
@reggie7 the password field is only shown to admins (if a regular user creates a new site the field does not exist). I honestly would vote against keeping this bug, would love to hear others voice their opinion about this issue as well.

**Comment by reggie7** [comment]
@reusr1 it's not a bug from my PoV. It's an enhancement proposal. And the proposed solution (even if only for the admin) could look like this (minus the annotations obviously), after a password is supplied:

<img width="1301" alt="proposed solution mock" src="https://user-images.githubusercontent.com/5563546/107521976-77e8de00-6bb3-11eb-97fd-2745046beacb.png">

The idea being - instead of showing an instruction on how to fetch the username - we simply display it.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/34
