### ISSUE TITLE
Make sure peregrine-builder is still in line with sling-org-apache-sling-starter

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#741]
From [Slack](https://peregrine-cms.slack.com/archives/CHCV4882U/p1613147547077600):

> @Reggie do you mind looking at [peregrine-builder](https://github.com/peregrine-cms/peregrine-builder) and making sure its still in line with [sling-org-apache-sling-starter](https://github.com/apache/sling-org-apache-sling-starter)? (its our own starter with the basic sling content removed)

> and can you make sure that starter then is compatible with https://github.com/headwirecom/peregrine-cms/pull/736 and removes more of the error messages?

![Slack Message](https://user-images.githubusercontent.com/5563546/107801545-80324c00-6d60-11eb-908a-1de67d98c052.png)

**Comment by reusr1** [comment]
peregrine-builder has been updated, a new release has been cut (pushed to github) and is now used by issues/707 branch to create the docker image

**Comment by reusr1** [comment]
changes above also fix https://github.com/headwirecom/peregrine-cms/issues/604

**Comment by ehdatheadwire** [comment]
@reggie7 and @reusr1 is this ticket still needed? It's listed as an enhancement but also as related to Sling12 and it's unclear if to work has been done to support this. Just let me know either way so I can relocate it or leave it be! Thx.

**Comment by reggie7** [comment]
I guess it's done, but let @reusr1 confirm for sure.

**Comment by reusr1** [comment]
agreee. closing this
