### ISSUE TITLE
Make step wizard (e.g. creating tenant) support pressing enter for next step

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#746]
When creating a tenant I'd love to be able to press `[Enter]` to get to the next page.
RIght now this wont work.

I remember trying to tinker that feature into it in the past and not being successful so this might not be as easy at it sounds since we dont have direct access to the buttons

**Comment by reusr1** [comment]
@Felix-Puetz wondering if we would want to wait with this ticket and deal with it once we know if we can switch the admin forms/wizards to the jsonforms vue version

**Comment by flx-sta** [comment]
Agree.
