### ISSUE TITLE
Tag is still on the page after unpublishing

### ISSUE THREAD

**Issue by ghost** [headwirecom/peregrine-cms#774]
Tag is still on the page after unpublishing.

**Steps to Reproduce**

1. Create a tag and add it to the page.
2. Publish tag.
3. Check on the page.
4. Unpublish tag.
5. Check on the page.

**Expected behavior**
After unpublishing tag, it should disappear in browser. 

**Actual behavior**
Tag is still on the page after unpublishing.

**Screencapture video**

https://user-images.githubusercontent.com/1230506/109670057-0af1b400-7b73-11eb-92bd-863768959e3e.mp4

**Environment**
-  LocalFS
 - develop-sling12
 - Chrome 88
 - Windows 10 (64bit)

**Comment by reusr1** [comment]
@ehdatheadwire please move to the enhancements and link to the unpublishing discussion at https://github.com/peregrine-cms/enhancements/discussions/58

**Comment by ehdatheadwire** [comment]
Moved to: https://github.com/peregrine-cms/enhancements/issues/66
