### ISSUE TITLE
Create a script to check replication consistency

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#782]
From @reusr1 

> I'd like a script (shell script preferably nodejs) that can check if the current state of the static replication folder for 1 tenant matches the state peregrine has in the repo
> and if not a lot of effort it should also be able to do the same for author/publish replicated

**Comment by ehdatheadwire** [comment]
Unclear if this should be moved as an enhancement or if it is a low enough effort to be completed in a short time and will assist with the replication process in the 1.0.0 release. @reggie7 if this is not an immediate need, might we move it? I'll mark as Move just in case you want to work on it.

**Comment by reusr1** [comment]
@ehdatheadwire would like to keep this - this will help us making sure we can test changes to publishing/unpublishing better in the future and helps with the integrity of the platform - I removed the 'move' label

**Comment by reggie7** [comment]
Fixed in [PR percli/27](https://github.com/headwirecom/percli/pull/27).
