### ISSUE TITLE
pageView.view state is not persistent

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#81]
When you are editing a page/template and you switch to preview-mode the state of `pageView.view` is `preview`:
<img width="200" alt="Screenshot 2019-05-28 at 14 31 56" src="https://user-images.githubusercontent.com/50131232/58479635-ef18dd00-8158-11e9-92cc-f09e33ec1f7d.png">
<img width="400" alt="Screenshot 2019-05-28 at 14 59 25" src="https://user-images.githubusercontent.com/50131232/58479844-53d43780-8159-11e9-864f-fc1d6a8da792.png">

Reloading the page resets this value to `desktop`: 
<img width="200" alt="Screenshot 2019-05-28 at 14 32 03" src="https://user-images.githubusercontent.com/50131232/58479663-f93adb80-8158-11e9-9562-d4a17c78a1ce.png">
<img width="400" alt="Screenshot 2019-05-28 at 15 00 04" src="https://user-images.githubusercontent.com/50131232/58479835-5040b080-8159-11e9-8a43-2d4218b8f94a.png">

There seems to be a problem with the init sequence. The iframe seems to be faster initialised than its parent.

**Comment by reusr1** [comment]
@bkheadwire can you please test out this change and give your ok?

**Comment by bkheadwire** [comment]
Tested issues/81 commit, pageView state now persists through page refreshes.
