### ISSUE TITLE
Cannot read property 'preview' of undefined

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#82]
### Reproduction:
1. checkout develop branch
1. build and deploy project
1. open browser (chrome in my case) and open a new tab **(the new tab is very important!)**
1. open http://localhost:8080/ 
1. open Dev-Tools and have the option "disable cache" active 
<kbd><img width="331" alt="Screenshot 2019-05-29 at 12 37 36" src="https://user-images.githubusercontent.com/50131232/58550682-99067100-820e-11e9-8eb7-400d9ce7508e.png"></kbd>
1. click the Link "sites and pages"
<kbd><img width="329" alt="Screenshot 2019-05-29 at 12 39 48" src="https://user-images.githubusercontent.com/50131232/58550807-e1be2a00-820e-11e9-8964-7a4e1b9a88ee.png"></kbd>
1. click on "public" to open the page-editor
<kbd><img width="206" alt="Screenshot 2019-05-29 at 12 40 44" src="https://user-images.githubusercontent.com/50131232/58550924-23e76b80-820f-11e9-9014-e451189d78bc.png"></kbd>
1. click on the preview button
<kbd><img width="73" alt="Screenshot 2019-05-29 at 12 40 48" src="https://user-images.githubusercontent.com/50131232/58550936-2944b600-820f-11e9-8006-39b439018188.png"></kbd>
1. check the JS-console and you will see the error
<kbd><img width="539" alt="Screenshot 2019-05-29 at 12 32 41" src="https://user-images.githubusercontent.com/50131232/58550944-2f3a9700-820f-11e9-8729-344a3ef9fd1f.png"></kbd>

----------------

### Workaround
_The current workaround for this issue is to select a different viewport before clicking the preview buttons_

**Comment by reusr1** [comment]
this issue should be resolved in develop with https://github.com/headwirecom/peregrine-cms/commit/c744df24d3bdfd2188491994d725ef984ac78c0f

**Comment by flx-sta** [comment]
Issue has been resolved 👍
