### ISSUE TITLE
preview-mode not sticky in template-editor

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#83]
In commit [a242d344354946f8f5cb30986f9e55693e7a8c96](https://github.com/headwirecom/peregrine-cms/commit/a242d344354946f8f5cb30986f9e55693e7a8c96#diff-b945faa965143a893942472b00834ca3) the preview mode was made sticky for the page-editor but not for the template-editor

**Comment by flx-sta** [comment]
I've provided a fix for this issue since its just a tiny bug
See #84

**Comment by reusr1** [comment]
thank you for the fix
