### ISSUE TITLE
Issues with vfg groups in component-panel

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#832]
> ℹ️ This bug-list is derived from branch TCF branch [`issue/160`](https://github.com/headwirecom/themeclean-flex/tree/issues/160)

### List of known issues:

- [x] Switching any `show <e.g. title>` switch to off and back to on the field pops up in the collapsed `Content` group
    - <img src="https://user-images.githubusercontent.com/50131232/113259892-f0c00880-92cd-11eb-9525-cd7f49211ddf.png" width="150"/>
- [x] `Advanced` group -> `semantic element` show an infinte loading animation
    - <img src="https://user-images.githubusercontent.com/50131232/113276942-8e243800-92e0-11eb-9f9e-7542546caab0.gif" width="200"/>

- [x] ~~Using a fresh `teaser-horizontal` component (not example content) you can not open the `content` group~~
    - that was because of all "visible" switches being "off"

**Comment by reusr1** [comment]
when testing this PR please also apply the version of themecleanflex with grouping ( https://github.com/headwirecom/themeclean-flex/pull/187 )
