### ISSUE TITLE
Add healthcheck to peregrine docker 

### ISSUE THREAD

**Issue by devintuffy** [headwirecom/peregrine-cms#85]
When setting up automated testing to use docker, we need to have the test runner sleep for 30 seconds before starting tests to give the container time to start up. 

Ideally, the container will implement a HEALTHCHECK ( https://docs.docker.com/engine/reference/builder/#/healthcheck ) so we can use docker inspect to check the status.

DoD: The following returns 'healthy' only when peregrine is in a state where users can connect and login:

docker inspect -f {{.State.Health.Status}}

**Comment by GastonGonzalez** [comment]
This feature was implemented in this [commit](https://github.com/headwirecom/peregrine-cms/commit/302553f8d96411ab592231879aff050be2323f8d). The image in Docker Hub has not yet been updated with this feature, so the steps below are required. They provide details on how to build a local Docker image. 

1. Checkout the `feature/docker` branch.

```
$ git checkout feature/docker
```

2. Build the Docker image as this image is not yet available in Docker Hub.

```
$ cd docker
$ ./builddocker.sh 
```

3. Start the container.

```
$ docker run -it --rm -p 8080:8080 peregrine-cms
```

4. Find your container ID.

```
$ docker ps
```

5. Inspect the health state. Replace `<CONTAINER_ID>` with ID from the ps command above.

```
$ docker inspect --format='{{json .State.Health}}' <CONTAINER_ID> 
```

If you have `jq` installed on your machine, you can also run:

```
$ docker inspect <CONTAINER_ID> | jq '.[0].State.Health'
```

@devintuffy - Please verify and let me know if you require any further changes.

**Comment by GastonGonzalez** [comment]
@devintuffy  - You no longer need to build the Docker image yourself as the `develop` image has been pushed to Docker Hub.  

```
$ docker pull peregrinecms/peregrine-cms:develop
$ docker run -it -p 8080:8080 peregrinecms/peregrine-cms:develop
$ docker inspect --format='{{json .State.Health}}' <CONTAINER_ID> 
```

**Comment by devintuffy** [comment]
@GastonGonzalez ~~Where was this pushed? The image I'm using:~~

~~https://hub.docker.com/r/reusr1/peregrine-cms~~

~~Doesn't show as updated on docker hub, and when I pulled I got a "Status: Image is up to date for reusr1/peregrine-cms:develop" response.~~

**Comment by devintuffy** [comment]
@GastonGonzalez ignore the previous comment -- @reusr1 directed me to the correct location.

**Comment by devintuffy** [comment]
@GastonGonzalez This is all working as expected, thanks for the quick turnaround on this.
