### ISSUE TITLE
inputType: number is laggy

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#86]
When using `"inputType": "number"` for a component the delay between changing the value and watching the component apply the value (for example changing its width) is annoyingly long.

I've used the following field in my dialog.json:
```
{
      "type": "input",
      "inputType": "number",
      "placeholder": "Width",
      "label": "width",
      "model.number": "width",
      "min": 1
    },
```

When using an alternative like `material-slider` or `"inputType": "text"` it works perfectly fine without any noticeable delay

**Comment by devintuffy** [comment]
@Felix-Puetz Hi, I am taking a look at this issue -- can you provide the full dialog.json you used, as well as the associated model.json? Thanks!

**Comment by flx-sta** [comment]
I didn't use model.json since we avoid using the "fragments" approach because we ran into too many issues.

I've added a branch for you in our fork-repo and provided an example component where you can have a look at the bug.
When changing the value for the first time it does apply after a short delay. Changing for a second time does not work at all

- Branch: [bug/laggy-number-input](https://github.com/meta-proc/peregrine-cms/tree/bug/laggy-number-input)
- Files: [themeclean/components/laggynumberinput](https://github.com/meta-proc/peregrine-cms/tree/bug/laggy-number-input/themes/themeclean/ui.apps/src/main/content/jcr_root/apps/themeclean/components/laggynumberinput)
- Model: [LaggynumberinputModel.java](https://github.com/meta-proc/peregrine-cms/blob/bug/laggy-number-input/themes/themeclean/core/src/main/java/com/themeclean/models/LaggynumberinputModel.java)

**Comment by devintuffy** [comment]
Thank you @Felix-Puetz , I was able to reproduce based on your code and am looking into this now.

After some initial debugging, this appears to be a delay within vue-form-generator; once the form emits the model-updated event everything else updates immediately, the delay is between the input being updated and FormGenerator's vue updating the model. 

Will continue to investigate.

**Comment by flx-sta** [comment]
@devintuffy any updates?

**Comment by flx-sta** [comment]
bump

I've created a new branch: [issue/86](https://github.com/headwirecom/peregrine-cms/tree/issue/86)

**Comment by flx-sta** [comment]
dismissed!
