### ISSUE TITLE
integrate vue-codemirror as editor for object-definitions

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#862]
When clicking `edit` on an object (e.g. json files, js files etc.) it opens the composum editor right now.

We want to change that to vue-codemirror-lite whch is already present as a dependency in the project (`see admin/ui.apps/package.json`)

**Comment by reusr1** [comment]
https://github.com/headwirecom/peregrine-cms/blob/1b19de2f7cfb64f802d44305971a21ce85382610/admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorer/template.vue#L503 is currently used to check if we open the composum editor

files are opened here: 

https://github.com/headwirecom/peregrine-cms/blob/1b19de2f7cfb64f802d44305971a21ce85382610/admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorer/template.vue#L709

**Comment by reusr1** [comment]
@Felix-Puetz code mirror is already available in the admin ui - the base HTML for the admin console includes ` Vue.use(VueCodeMirror)`
