### ISSUE TITLE
Checkbox in Pathbrowser not working

### ISSUE THREAD

**Issue by FabianHaupt** [headwirecom/peregrine-cms#89]
We are currently creating our own Components and created a Link Component which uses the Pathbrowser for setting the link.  When you open the Pathbrowser and then click on the link tab you cant check the checkbox.
<img width="666" alt="Bildschirmfoto 2019-06-12 um 15 29 22" src="https://user-images.githubusercontent.com/50013766/59357569-5e7ef700-8d2b-11e9-945b-8692dd966f4a.png">

**Comment by reusr1** [comment]
analysis: need a better way to set all possible options for a link. We should also consider noreferrer, nofollow - should there instead be a way to manage outgoing links better?

**Comment by flx-sta** [comment]
@reusr1 I'd say we remove this checkbox for now

I mean: why provide a checkbox with no functionallity and this seems to be the wrong place to put this function in my opinion. I'd rather put checkboxes like these in the specific component that is suppoed to create a link

**Comment by flx-sta** [comment]
I've set the default visiblity of the checkbox to `false`  in the pagebrowser component
