### ISSUE TITLE
evaluate if the icon edit functionality in the rich text editor can use a web component

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#903]
@Felix-Puetz - our rich text editor currently inserts [icon:iconname] into the text - can you please explore if we can change that to insert a web component instead and write a web component that can render the icon? 

z.B.
- slimjs

**Comment by flx-sta** [comment]
well we can always just use `<img>` but i don't really kow where you wanna head with this

**Comment by reusr1** [comment]
@Felix-Puetz please find attached a super simple web component that can display an icon and some instructions that show us how we could use it in our text editor

[simpleicon.zip](https://github.com/headwirecom/peregrine-cms/files/6469513/simpleicon.zip)

unzip the zip file, open up the index.html file in your browser

**Comment by flx-sta** [comment]
@reusr1 

- ~~Alright but what is the gain from this? this is what I still don't get..
The icons might still be way oversized.
And for me an `<img/>` tag would have produced the same result (except maybe new line but we were able to solve that with css technically)~~
  - > **@reusr1 in Slack:**
    > better determination what elements the cursor is on and more "flexibility"

- ~~Also we should verify if this is doable "dynmically" (insert it into a text-flow without breaking the text) as the whole `exec()` method structure is not that easy unfortunately.~~
  - easy

- ~~And last but not least Im not 100% sure if the pergrine environment supports `class` keyword .~~
  - well that didn't work 100% but its now imported as an external resource into the themclean-flex template

**Comment by flx-sta** [comment]
It works now but there is still some issues that are noted in #928
