### ISSUE TITLE
site switcher (<section>/<tenant> to <tenant>/<section>)

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#93]
concern: 

currently all consoles in peregrine start at the /content/{concept} level. It may be better to switch this and add a drop down to the top toolbar where one can select the site (or tenant) the user is currently working with. This should also allow us to have better path browsers to choose assets or links to other pages as we would always know the context the user is working in

this issue has been created to discuss this topic and solicit feedback from the community

**Comment by GastonGonzalez** [comment]
I agree that introducing a top-level concept/tenant node is needed in Peregrine to easily allow support for multiple tenants on a single Peregrine instance. +1 for this feature.

**Comment by schaefa** [comment]
Sling has no OOTB handling of tenants based on the (Servlet) Resource Resolver. This means we must handle the separation of the tenants. Do you intend to have the tenant info in a context object or as part of the path?
I am all for it but it's not easy as Adobe has quite some problems with it.

**Comment by reusr1** [comment]
@schaefa @GastonGonzalez this issue is more at the UI level in general (UX of peregrine). I agree however we should at one point come up with a strategy for tenant separation.

**Comment by flx-sta** [comment]
### see [Project 3](https://github.com/headwirecom/peregrine-cms/projects/3)
