### ISSUE TITLE
Rich text editor needs improved styling.

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#96]
![image](https://user-images.githubusercontent.com/2624171/59779320-e35a9b00-926c-11e9-8715-7d99697ed468.png)

Currently very awkward to edit anything besides small text in the editor

**Comment by flx-sta** [comment]
you could open the side-bar in full-screen 🤷‍♂

**Comment by reusr1** [comment]
I think I fixed this already @dna113p - added the rest css property to the trumbowyg editor

**Comment by flx-sta** [comment]
@reusr1 `resetCss` does not really increase the size of the editor and i think that's the issue

**Comment by reusr1** [comment]
@Felix-Puetz I don't think so - it was the fact that any h1 in the editor had such a big font a while back

**Comment by flx-sta** [comment]
@reusr1 alright i misunderstood then
