### ISSUE TITLE
Rich text editor link editing has not been styled

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#97]
![image](https://user-images.githubusercontent.com/2624171/59779445-1f8dfb80-926d-11e9-8f65-ef88db93b55a.png)

**Comment by dna113p** [comment]
Editing a link in the rich text editor should open up the path browser dialog that we already have built.

**Comment by reusr1** [comment]
@dna113p I added the ability to override the modals from trumbowyg in the issues/97 branch - can you please hook this up to the url pathbrowser and the image browser?

**Comment by bkheadwire** [comment]
Still has issues, see comments on the PR: https://github.com/headwirecom/peregrine-cms/pull/224
